import type { Program, ProgramDay } from './types'

function day(
  n: number,
  title: string,
  minutes: number,
  summary: string,
  blocks: ProgramDay['blocks'],
  sentence: string,
  scene: string,
  release: string,
  gratitude: string,
  nightSeed?: string,
): ProgramDay {
  return {
    day: n,
    title,
    minutes,
    summary,
    blocks,
    sentence,
    scene,
    release,
    gratitude,
    nightSeed,
  }
}

export const programs: Program[] = [
  {
    id: 'panic',
    title: 'Panik — 7 gün',
    subtitle: 'Dalga haritası. 1. gün açık, sonrası Pro.',
    freeDays: 1,
    days: [
      day(
        1,
        'Dalga haritası',
        8,
        'Alarmın bir kehanet olmadığını bedenle hatırla.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Otur, ağırlığı bırak',
            body: 'Sandalye seni taşıyor. Çeneyi milim bırak. Omuzları kulaklardan uzaklaştır. Eller yumuşak. Bu bir tedavi seansı değil; sinir sistemine kısa bir mola.',
          },
          {
            kicker: 'Harita',
            title: 'Tepe ve iniş',
            body: 'Panik bir dağ değil, bir dalgadır. Tırmanır, tepe yapar, iner. Sen dalganın içinde kaybolmazsın; kıyıda duran kişisin. Süre tutmana gerek yok. Sadece “şimdi yoğun, sonra daha az” cümlesini aklında tut.',
          },
        ],
        'Bu anda güvende oturuyorum.',
        'Bildığın bir oda. Kapı görünür. Bir lamba. Ayakların yerde. Pencereden sakin bir ışık.',
        'Zihne işi bırak diyorum. Ben zorlamıyorum.',
        'Nefes alabildiğim için teşekkür ederim.',
        'Kapalı kapı, loş lamba, yorganın ağırlığı.',
      ),
      day(
        2,
        'Ayaklar yerde',
        9,
        'Taban, topuk, yer. Alarm ayakta değil, yerde söner.',
        [
          {
            kicker: 'Rahat beden',
            title: 'İki taban',
            body: 'Ayakkabı veya çorap fark etmez. Tabanın tamamını hisset. Sol topuk, sağ topuk. Ağırlığı eşit böl. Dizleri kilitleme.',
          },
          {
            kicker: 'Temas',
            title: 'Yerin adı',
            body: 'Yer sert mi, yumuşak mı, serin mi. Bir kelime seç ve içinden tekrarla. Zihin kaçarsa kelimeye dön. Kaçış yok, sadece dönüş.',
          },
        ],
        'Ayaklarım yerde, ben buradayım.',
        'Taş bir eşik. Serin. Sabah ışığı eşikte duruyor. Sen eşikte duruyorsun.',
        'Kontrolü bırakıyorum. Yer zaten beni taşıyor.',
        'Bu zemine teşekkür ederim.',
        'Eşik, serin taş, kapı tokmağı.',
      ),
      day(
        3,
        'Nefes dalgası',
        10,
        'Al 4, tut 2, ver 6. Veriş iniştir.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Kaburgalar yanlara',
            body: 'Omuzları kaldırma. Nefes göğsü şişirmek zorunda değil. Yan kaburgalar hafifçe açılır, karın yumuşak kalır.',
          },
          {
            kicker: 'Ritim',
            title: '4-2-6',
            body: 'Dört sayıyla al, iki tut, altı ver. Verişte ağız hafif açık olabilir. Baş dönmesi olursa normale dön, zorlama. Bu bir performans değil.',
          },
        ],
        'Nefesim beni şimdi tutuyor.',
        'Deniz yok, sadece bir kuyunun içindeki yavaş su. Su iner, sen kıyıda oturursun.',
        'Nefesi mükemmel yapmaya çalışmayı bırakıyorum.',
        'Bu veriş için teşekkür ederim.',
        'Yavaş su, taş kenar, sessiz kuyu.',
      ),
      day(
        4,
        'Cümle ve sahne',
        10,
        'Kısa şimdiki zaman. Sonra tek bir oda.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Çene ve dil',
            body: 'Dili dişlerin arasından çek. Çene menteşesini bırak. Alın düzelsin. Yüz bir maske değil, bir örtü.',
          },
          {
            kicker: 'Cümle',
            title: 'Tek satır',
            body: 'Uzun manifesto yok. Sekiz kelimeyi geçme. Şimdiki zaman, olumlu, bedenli. Tekrar et, tartışma.',
          },
        ],
        'Bu oda gerçek, ben içindeyim.',
        'Kendi mutfağın veya bildiğin bir mutfak. Masa. Bir bardak. Pencere. Hiç kimse yok, tehlike yok.',
        'Cümleyi kanıtlamayı bırakıyorum. Sadece söylüyorum.',
        'Bu sessiz mutfak için teşekkür ederim.',
        'Masa, bardak, gece lambası.',
      ),
      day(
        5,
        'Isı ve temas',
        9,
        'Soğuk su, sıcak kupa, kumaş. Beden kanıt ister.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Eller',
            body: 'Avuçları birbirine sürt, sonra bırak. Isıyı fark et. Parmak uçları. Bu, alarmın “yokum” iddiasına küçük bir itiraz.',
          },
          {
            kicker: 'Nesne',
            title: 'Bir şey tut',
            body: 'Kupa, yastık, anahtarlık. Sıcaklık, ağırlık, kenar. Üç kelimeyle tanımla. Yüksek sesle daha iyi.',
          },
        ],
        'Ellerim gerçek, bu kupa gerçek.',
        'İki elin arasında ılık bir kupa. Buhar yok olsa da ısı var. Parmaklar kupanın kavisini biliyor.',
        'Nesneleri sorgulamayı bırakıyorum.',
        'Bu ısı için teşekkür ederim.',
        'Ilık kupa, karanlık masa.',
      ),
      day(
        6,
        'Geçti ritüeli',
        8,
        'Dalga inince kayıt ve on dokunuş. Bugün prova.',
        [
          {
            kicker: 'Rahat beden',
            title: 'İniş',
            body: 'Omuzlar, çene, karın. Alarmın artığını silkelemeden bırak. Ritüel SOS’taki Geçti ile aynı mantık: süre, cümle, dokunuş.',
          },
          {
            kicker: 'Prova',
            title: 'Sakinken öğren',
            body: 'Krizde yeni ritüel icat edilmez. Bugün sakinken on dokunuşu yap. Yarın beden yolu bilir.',
          },
        ],
        'Dalga geçti, ben kaldım.',
        'Kıyıda bir tahta iskele. Su çekilmiş. Islak tahta, tuz kokusu, sen ayaktasın.',
        'Hesap sormayı bırakıyorum.',
        'İndiğim için teşekkür ederim.',
        'Islak iskele, çekilmiş su.',
      ),
      day(
        7,
        'Küçük şükran',
        8,
        'Büyük anlam yok. Küçük gerçek.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Tüm günün artığı',
            body: 'Alın, göz çevresi, ağız kenarı. Günün alarm artıklarını yere bırak. Yedi gün bir tedavi kürü değil, bir alışkanlık iskeleti.',
          },
          {
            kicker: 'Şükran',
            title: 'Üç küçük şey',
            body: 'Su, yer, bir kişi veya bir nesne. Abartma. “Hayat muhteşem” deme. Sadece üç somut şey.',
          },
        ],
        'Bugün bedenim beni taşıdı.',
        'Aynı oda. Aynı lamba. Sen biraz daha yavaşsın. Sahne değişmek zorunda değil.',
        'Programı bitirmiş olmayı bir zafer gibi şişirmiyorum. Bırakıyorum.',
        'Taşınmış olduğum için teşekkür ederim.',
        'Aynı lamba, aynı yorgan, sakin nefes.',
      ),
    ],
  },
  {
    id: 'anxiety',
    title: 'Anksiyete — 7 gün',
    subtitle: 'Yarını rafa almak. Tamamı Pro.',
    freeDays: 0,
    days: [
      day(
        1,
        'Prova yasağı',
        10,
        'Zihin yarını çalıştırır. Sen şimdiye sandalye koyarsın.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Çene kilidi',
            body: 'Azı dişlerini ayır. Dil alt damağa. Anksiyete çoğu zaman çenede oturur.',
          },
          {
            kicker: 'Sınır',
            title: 'Pencere',
            body: 'Kaygıyı yok etmeyeceksin. Ona on dakikalık bir defter penceresi vereceksin. Pencere kapanınca prova yasak.',
          },
        ],
        'Şimdi bu sandalyedeyim, yarın burada değil.',
        'Bildiğin bir masa, kapalı bir defter, üstünde bir bardak. Defter işini bitirdi.',
        'Yarını çözmeyi bırakıyorum.',
        'Bu duruş için teşekkür ederim.',
        'Kapalı defter, sönük lamba.',
      ),
      day(
        2,
        'Omuzlardan indir',
        9,
        'Gerginlik fikir değil, kas.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Omuz döngüsü',
            body: 'Omuzları kulaklara yaklaştır, üç saniye, bırak. İki kez. Bırakış asıl iş.',
          },
          {
            kicker: 'Tarama',
            title: 'Üç bölge',
            body: 'Çene, omuz, karın. Her birine “yumuşak” de. Doğru yapmak yok, fark etmek var.',
          },
        ],
        'Omuzlarım iniyor, ben iniyorum.',
        'Geniş bir pencere önü. Perde ağır. Dışarıda durgun bir sokak.',
        'Kasları ikna etmeyi bırakıyorum, sadece bırakıyorum.',
        'Bu yumuşaklık için teşekkür ederim.',
        'Ağır perde, durgun sokak.',
      ),
      day(
        3,
        'Kutu ritim',
        10,
        'Eşit kenarlar, eşit zihin.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Sırt düz, çaba yok',
            body: 'Sırtı yasla. Nefes kutuya girsin diye zorlama. Sayılar bir çerçeve, bir sınav değil.',
          },
          {
            kicker: 'Kutu',
            title: '4-4-4-4',
            body: 'Al, tut, ver, boşluk. Dörder. Zihin kenarlardan kaçarsa sayıya dön.',
          },
        ],
        'Ritimim şimdi sakin ve eşit.',
        'Dört kenarlı bir avlu. Ortada sakin bir ağaç. Sen kenarda oturuyorsun.',
        'Kutuyu mükemmelleştirmeyi bırakıyorum.',
        'Bu eşitlik için teşekkür ederim.',
        'Avlu, ağaç, gece.',
      ),
      day(
        4,
        'İşe yarayan cümle',
        8,
        'Gelecek zaman yok. Şimdi var.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Alın',
            body: 'Kaşların arasındaki düğümü çöz. Gözleri yum. Işık yine de orada.',
          },
          {
            kicker: 'Cümle',
            title: 'Kısa ve şimdi',
            body: '“Yarın iyi olacak” değil. “Bu saatte bedenim oturuyor.” Kanıt arama.',
          },
        ],
        'Bu saatte bedenim sakin oturuyor.',
        'Saat olmayan bir oda. Sadece ışık ve kumaş. Zaman dışarıda bekliyor.',
        'Geleceği yazmayı bırakıyorum.',
        'Bu saat için teşekkür ederim.',
        'Kumaş, loş ışık, saatsiz oda.',
      ),
      day(
        5,
        'Sahne: bilinen yer',
        11,
        'Yeni cennet icat etme. Eski bir odayı ısıt.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Ayak bilekleri',
            body: 'Ayak bileklerini serbest bırak. Üst üste atma. İki ayak yerde.',
          },
          {
            kicker: 'Sahne',
            title: 'Detay',
            body: 'Kapının rengi, yerin sesi, bir koku. Üç duyudan fazlasına gitme. Sahne sade kalsın.',
          },
        ],
        'Bildiğim bu yerde duruyorum.',
        'Çocukluktan veya geçen yıldan sakin bir oda. Abartısız. Bir pencere yeter.',
        'Sahneyi süslemeyi bırakıyorum.',
        'Bu bildik yer için teşekkür ederim.',
        'O pencere, o pervaz.',
      ),
      day(
        6,
        'Bırakış denemesi',
        8,
        'Kontrol kaygının yakıtı.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Elleri aç',
            body: 'Avuç içleri yukarı. Tutulan şeyi bırakır gibi. Bir dakika.',
          },
          {
            kicker: 'Bırakış',
            title: 'Cümle',
            body: '“Bunu bu gece çözmeyeceğim.” Zihin itiraz eder. Sen cümleyi bir kez daha söylersin.',
          },
        ],
        'Bu gece çözmek zorunda değilim.',
        'Kapalı bir dükkân kepengi. İş yarın. Sokak boş.',
        'Kepengi zorla açmayı bırakıyorum.',
        'Bu boş sokak için teşekkür ederim.',
        'Kapalı kepenk, boş sokak.',
      ),
      day(
        7,
        'Gece tohumu',
        9,
        'Uykuya tek görüntü.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Yatış provası',
            body: 'Oturarak da olur. Gözler kapalı. Dil ağır. Gün kapanıyor.',
          },
          {
            kicker: 'Tohum',
            title: 'Tek kare',
            body: 'Bir kandil, bir taş bahçe, bir koy. Film değil, kartpostal. Bırak, gece işlesin.',
          },
        ],
        'Gece bu tohumu taşıyor.',
        'Kapalı bahçe, ılık taş, tek kandil. Rüzgâr yok.',
        'Anlam çıkarmayı bırakıyorum. Tohumu bırakıyorum.',
        'Bu kandil için teşekkür ederim.',
        'Kandil, ılık taş, kapalı bahçe.',
      ),
    ],
  },
  {
    id: 'derealization',
    title: 'Derealizasyon — 7 gün',
    subtitle: 'Dünyanın kenarları. Tamamı Pro. DP değil.',
    freeDays: 0,
    days: [
      day(
        1,
        'Kenar çiz',
        10,
        'Sis bir yorumdur. Dikdörtgen bir penceredir.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Otur ve bak',
            body: 'Gözleri kısma. Odak zorlaması sisı artırır. Yumuşak bakış.',
          },
          {
            kicker: 'Kenar',
            title: 'Üç dikdörtgen',
            body: 'Kapı, pencere, telefon değil: bir çerçeve daha. Kenarları içinden çiz. DR, dünyanın sahne gibi durmasıdır; sen sahne dekorunu değil, marangozluğu sayarsın.',
          },
        ],
        'Bu odanın kenarları gerçek.',
        'Bir pencere pervazı. Ahşap damarı. Dışarıda durağan bir duvar.',
        'Sisle tartışmayı bırakıyorum.',
        'Bu pervaz için teşekkür ederim.',
        'Pervaz, ahşap damar.',
      ),
      day(
        2,
        'Renk ve ısı',
        9,
        'Karton dünya iddiasına ısı ile cevap.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Avuç ısısı',
            body: 'Avuçları yanağa değdir, kaldır. Isı kalır. Dünya tamamen sahte olsa bu ısı yine de olurdu — o yüzden ısıyı say.',
          },
          {
            kicker: 'Renk',
            title: 'Üç ad',
            body: 'Bir koyu, bir açık, bir ara. “Pembe” değil, “soluk gül” de değil: senin kelimen. Sade.',
          },
        ],
        'Isı ve renk bu odada.',
        'Gün ışığı bir duvara vuruyor. Duvar mat. Sen duvarı görüyorsun.',
        'Dünyayı kanıtlamayı bırakıyorum, sayıyorum.',
        'Bu ışık için teşekkür ederim.',
        'Mat duvar, gün ışığı.',
      ),
      day(
        3,
        'Ses katmanı',
        8,
        'Sis görseldir. Kulak delik açar.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Çene yumuşak',
            body: 'Kulaklar çalışsın diye yüzü bırak. Ağız kapalı, dişler ayrı.',
          },
          {
            kicker: 'Katman',
            title: 'Yakın, orta, uzak',
            body: 'Bir iç ses (nefes), bir oda sesi, bir dış ses. Üçünü sırayla adlandır. DR’de dünya “film müziği” gibi durabilir; sen kaynakları ayır.',
          },
        ],
        'Sesler ayrı ayrı geliyor.',
        'Açık pencere, uzak bir araba, yakında bir saat. Film yok, kaynak var.',
        'Tek bir sis kuyusuna inmeyi bırakıyorum.',
        'Bu katmanlar için teşekkür ederim.',
        'Açık pencere, uzak araba.',
      ),
      day(
        4,
        'Doku yürüyüşü',
        10,
        'Parmak uçları kamera değildir.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Ayakta veya oturarak',
            body: 'Bir metre yeter. Halı, duvar, masa kenarı.',
          },
          {
            kicker: 'Doku',
            title: 'Pürüz',
            body: 'Pürüzlü, düz, soğuk. Üç dokunuş, üç kelime. Acele yok. DP kapısındaki “ben yokum” değil, “dünya var” işi bu.',
          },
        ],
        'Dokunduğum yüzey burada.',
        'Sıvalı bir duvar. İnce kum. Parmak izi kalmaz, duvar kalır.',
        'Yüzeyleri test etmeyi bırakıyorum, temas ederim.',
        'Bu sıva için teşekkür ederim.',
        'Sıva, ince kum.',
      ),
      day(
        5,
        'Pencere ışığı',
        9,
        'Işığın yönü bir koordinattır.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Göz çevresi',
            body: 'Gözleri ovuşturma. Yumuşak kapak. Sonra tekrar bak.',
          },
          {
            kicker: 'Yön',
            title: 'Kaynak',
            body: 'Işık soldan mı, tavandan mı, ekrandan mı. Bir cümle: “Işık soldan geliyor.” Sis yön bilmez, sen bilirsin.',
          },
        ],
        'Işık bir yerden geliyor.',
        'Sol pencereden giren akşam. Toz görünür. Toz, havanın olduğunu söyler.',
        'Görüntüyü düzeltmeyi bırakıyorum.',
        'Bu yön için teşekkür ederim.',
        'Sol pencere, akşam tozu.',
      ),
      day(
        6,
        'Adlandırma turu',
        8,
        'Beş nesne, yüksek ses.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Nefes sade',
            body: 'Dalga nefesi zorunlu değil. Burun al, ağız ver, kısa.',
          },
          {
            kicker: 'Liste',
            title: 'Beş',
            body: 'Sandalye, perde, bardak, zemin, tavan. “Sanki” ekini kullanma. İsim yeter.',
          },
        ],
        'Bu beş şey odada duruyor.',
        'Aynı beş nesne, aynı yer. Sahne değişmez. Sen listelersin.',
        'Listeyi yorumlamayı bırakıyorum.',
        'Bu beş şey için teşekkür ederim.',
        'Beş nesne, sakin oda.',
      ),
      day(
        7,
        'Gece: dışarıdaki koy',
        10,
        'Dünya uyurken de durur.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Yatış',
            body: 'Yorganın ağırlığı bir kenardır. Onu da say.',
          },
          {
            kicker: 'Tohum',
            title: 'Koy',
            body: 'Gece koyu, yavaş su, çakıl. Dünya orada. Sen yataktasın. İkisi birden gerçek olabilir.',
          },
        ],
        'Oda ve koy, ikisi de duruyor.',
        'Ay çizgili sakin bir koy. Su siyah, kıyı soluk. Rüzgâr yok.',
        'Dünyayı uyanık tutmayı bırakıyorum.',
        'Bu duruş için teşekkür ederim.',
        'Ay çizgisi, sakin koy.',
      ),
    ],
  },
  {
    id: 'depersonalization',
    title: 'Depersonalizasyon — 7 gün',
    subtitle: 'Bedenin ağırlığı. Tamamı Pro. DR değil.',
    freeDays: 0,
    days: [
      day(
        1,
        'Ağırlık',
        10,
        'İzleyici koltuğundan kumaşa.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Oturak',
            body: 'Sol kalça, sağ kalça. Sırt. DP’de kişi kendini dışarıdan izler. Sen basıncı içeriden say.',
          },
          {
            kicker: 'Ağırlık',
            title: 'Dört nokta',
            body: 'İki oturak, iki ayak. Dörder saniye. Ayna yok. DR’deki “dünya sis” değil, “ben camdayım” işi bu.',
          },
        ],
        'Ağırlığım bu sandalyede.',
        'Kumaşlı bir sandalye. Sen içindesin, karşısında değil.',
        'Kendimi seyretmeyi bırakıyorum.',
        'Bu ağırlık için teşekkür ederim.',
        'Kumaş sandalye, loş oda.',
      ),
      day(
        2,
        'Ad ve tarih',
        8,
        'Kulak kendi sesini alsın.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Göğüs',
            body: 'Göğsün üstüne el. Nefes eli kaldırır, indirir. İzlemek değil, hissetmek.',
          },
          {
            kicker: 'Ses',
            title: 'Üç satır',
            body: 'Adın. Bugünün tarihi. Bulunduğun şehir. Fısıltı yeter. Kanıt mahkemesi değil, kulak teması.',
          },
        ],
        'Adım bu, bugün bu, ben buradayım.',
        'Kendi odan. Takvim yoksa bile tarih senin dilinde.',
        'Kimlik tartışmasını bırakıyorum.',
        'Bu ses için teşekkür ederim.',
        'El göğüste, karanlık oda.',
      ),
      day(
        3,
        'Eller',
        9,
        'Parmaklar birer kıyı.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Parmak araları',
            body: 'Parmakları aç, kapat. Yavaş. Eldiven hissi varsa da hareket gerçek.',
          },
          {
            kicker: 'İş',
            title: 'Bir düğme, bir kumaş',
            body: 'Gömlek düğmesi veya yorgan. Küçük motor iş bedeni içeri çağırır.',
          },
        ],
        'Ellerim bu işi yapıyor.',
        'Bir düğme, bir ilik, sabır. Sahne bu kadar.',
        'Elleri yabancı ilan etmeyi bırakıyorum.',
        'Bu parmaklar için teşekkür ederim.',
        'Düğme, ilik, yavaş el.',
      ),
      day(
        4,
        'İç çekiş',
        8,
        'Çift al, uzun ver. Bedeni içeri.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Omuzlar aşağı',
            body: 'İç çekiş omuz tiyatrosu değildir. Burun, burun, ağız.',
          },
          {
            kicker: 'Ritim',
            title: 'Fizyolojik',
            body: 'Kısa ikinci alış, uzun veriş. Üç-beş tur. Sersemlik olursa dur. Bu, DP’de bedeni “kullanılabilir” hale getirir, tedavi iddiası değil.',
          },
        ],
        'Nefes bedenimin içinde.',
        'Göğüs kafesi bir oda. Hava girer, çıkar. Sen odasın.',
        'Nefesi izlemeyi bırakıp nefes oluyorum.',
        'Bu iç çekiş için teşekkür ederim.',
        'Göğüs odası, yavaş hava.',
      ),
      day(
        5,
        'Yürüme sayımı',
        10,
        'On adım, on temas.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Dik ama yumuşak',
            body: 'Koridorda veya odada. On adım yeter. Koşu yok.',
          },
          {
            kicker: 'Sayım',
            title: 'Taban',
            body: 'Her adımda topuk-parmak. “Bir, yer. İki, yer.” İzleyici kamerasını kapat, tabanı aç.',
          },
        ],
        'Adımlarımı içeriden atıyorum.',
        'Kısa bir koridor. Halı veya tahta. Pencere sonda. Sen yürüyorsun.',
        'Kendimi filmde izlemeyi bırakıyorum.',
        'Bu on adım için teşekkür ederim.',
        'Koridor, halı, sonda pencere.',
      ),
      day(
        6,
        'Sıcaklık haritası',
        9,
        'El, yüz, ayak. Üç iklim.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Hareketsiz',
            body: 'Bir dakika hiç kıpırdama. Sonra harita.',
          },
          {
            kicker: 'Harita',
            title: 'Üç bölge',
            body: 'El serin, yüz ılık, ayak… neyse o. Yanlış yok. DP “hissizim” der; sen milim ısıyı yazarsın.',
          },
        ],
        'Bedenimde ısı var.',
        'Üç bölgeli sakin bir ev. Mutfak ılık, hol serin, oda loş. Sen evsin.',
        'Hissizliği kanıtlamayı bırakıyorum.',
        'Bu milim ısı için teşekkür ederim.',
        'Üç odalı ev, loş lamba.',
      ),
      day(
        7,
        'Gece tohumu: battaniye',
        9,
        'Örtü seni tutar.',
        [
          {
            kicker: 'Rahat beden',
            title: 'Yatış',
            body: 'Yorganı çek. Ağırlığı dört noktada say. Gözler kapalı.',
          },
          {
            kicker: 'Tohum',
            title: 'Örtü',
            body: 'Kalın bir battaniye, çene altı, ayak uçları kapalı. İzleyici yok. Sadece örtü ve nefes. Bırak, gece işlesin.',
          },
        ],
        'Örtü beni tutuyor, ben buradayım.',
        'Kalın battaniye, loş lamba sönük, kapı kapalı.',
        'Uyanık nöbeti bırakıyorum.',
        'Bu örtü için teşekkür ederim.',
        'Battaniye, kapalı kapı, sönük lamba.',
      ),
    ],
  },
]

export function programByDoor(id: string): Program | undefined {
  return programs.find((p) => p.id === id)
}

export function programDay(id: string, dayNum: number): ProgramDay | undefined {
  return programByDoor(id)?.days.find((d) => d.day === dayNum)
}
