/** UI ekleri. strings.ts içinde CORE üzerine yayılır. */
import { R } from './locales'

export const EXTRA = {
  hello: R('Merhaba|Hello|Salam|Привет|Hola|Bonjour|Hallo|Ciao|Olá|مرحبا|Hallo|Cześć|Привіт|こんにちは|سلام|你好'),
  mood_check: R('Ruh hâli|Mood check-in|Əhval|Настроение|Ánimo|Humeur|Stimmung|Umore|Humor|المزاج|Stemming|Nastrój|Настрій|気分|حال|心情'),
  mood_calm: R('Sakin|Calm|Sakit|Спокойно|Tranquilo|Calme|Ruhig|Calmo|Calmo|هادئ|Kalm|Spokój|Спокій|穏やか|آرام|平静'),
  mood_tense: R('Gergin|Tense|Gərgin|Напряжённо|Tenso|Tendu|Angespannt|Teso|Tenso|متوتر|Gespannen|Napięcie|Напруга|緊張|تنش|紧张'),
  mood_sleepless: R('Uykusuz|Sleepless|Yuxusuz|Бессонница|Sin sueño|Sans sommeil|Schlaflos|Insonne|Sem sono|أرق|Slapeloos|Bezsenność|Безсоння|眠れない|بی‌خواب|失眠'),
  mood_wave: R('Dalgalı|Wavy|Dalğalı|Волнами|Oleaje|Vague|Wellig|Ondoso|Ondulado|موج|Golvend|Falujący|Хвилями|波打つ|موج‌دار|波动'),
  mood_distant: R('Uzak|Distant|Uzaq|Далеко|Lejano|Lointain|Fern|Lontano|Distante|بعيد|Ver|Odległy|Далеко|遠い|دور|疏远'),
  search: R('Ara|Search|Axtar|Поиск|Buscar|Rechercher|Suchen|Cerca|Pesquisar|بحث|Zoeken|Szukaj|Пошук|検索|جستجو|搜索'),
  search_ph: R('Meditasyon, ses, hikâye…|Meditation, sound, story…|Meditasiya, səs, hekayə…|Медитация, звук, история…|Meditación, sonido, historia…|Méditation, son, histoire…|Meditation, Klang, Geschichte…|Meditazione, suono, storia…|Meditação, som, história…|تأمل، صوت، قصة…|Meditatie, geluid, verhaal…|Medytacja, dźwięk, historia…|Медитація, звук, історія…|瞑想、音、物語…|مدیتیشن، صدا، داستان…|冥想、声音、故事…'),
  view_details: R('Ayrıntı|View details|Ətraflı|Подробнее|Ver detalles|Voir|Details|Dettagli|Detalhes|التفاصيل|Details|Szczegóły|Деталі|詳細|جزئیات|详情'),
  daily_rec: R('Günün önerileri|Daily recommendations|Günün tövsiyələri|Рекомендации дня|Recomendaciones|Recommandations|Empfehlungen|Consigli del giorno|Recomendações|توصيات اليوم|Aanbevelingen|Rekomendacje|Рекомендації|今日のおすすめ|پیشنهادهای امروز|今日推荐'),
  favorites: R('Favoriler|Favorites|Sevimlilər|Избранное|Favoritos|Favoris|Favoriten|Preferiti|Favoritos|المفضلة|Favorieten|Ulubione|Обране|お気に入り|علاقه‌مندی‌ها|收藏'),
  fav_empty: R('Henüz yok. Bir karta uzun basınca eklenir.|None yet. Long-press a card to add one.|Hələ yoxdur. Kartı basılı saxla.|Пока пусто. Долгое нажатие на карточку.|Aún no. Mantén pulsada una tarjeta.|Pas encore. Appui long sur une carte.|Noch keine. Karte lange drücken.|Ancora nessuno. Tieni premuta una scheda.|Ainda não. Pressione e segure um cartão.|لا شيء بعد. اضغط مطولاً على بطاقة.|Nog geen. Houd een kaart ingedrukt.|Jeszcze brak. Przytrzymaj kartę.|Поки порожньо. Утримуй картку.|まだありません。カードを長押し。|هنوز نیست. کارت را نگه دارید.|暂无。长按卡片添加。'),
  breathing: R('Nefes|Breathing|Nəfəs|Дыхание|Respiración|Respiration|Atmung|Respiro|Respiração|التنفس|Adem|Oddech|Дихання|呼吸|تنفس|呼吸'),
  start_med: R('Meditasyona başla|Start meditating|Meditasiyaya başla|Начать медитацию|Empezar a meditar|Commencer|Meditation starten|Inizia a meditare|Começar|ابدأ التأمل|Begin mediteren|Zacznij medytować|Почати медитацію|瞑想を始める|شروع مدیتیشن|开始冥想'),
  programs: R('Programlar|Meditation programs|Proqramlar|Программы|Programas|Programmes|Programme|Programmi|Programas|برامج|Programma\'s|Programy|Програми|プログラム|برنامه‌ها|课程'),
  premium_banner: R('Ücretsiz deneme ile Pro’yu aç.|Start your Premium membership with free trial now.|Pulsuz sınaqla Pro-nu aç.|Откройте Pro с бесплатным пробным периодом.|Empieza Premium con prueba gratis.|Ouvre Pro avec l’essai gratuit.|Pro mit kostenloser Testphase starten.|Apri Pro con la prova gratuita.|Abra o Pro com o teste grátis.|ابدأ التجربة المجانية لـ Pro.|Start Pro met gratis proefperiode.|Otwórz Pro z bezpłatnym okresem próbnym.|Відкрий Pro з безкоштовним пробним.|無料トライアルでProを始める。|آزمایش رایگان Pro را شروع کنید.|免费试用开启 Pro。'),
  view_all_short: R('Tümü|View all|Hamısı|Все|Ver todo|Tout voir|Alle|Vedi tutto|Ver tudo|عرض الكل|Alles|Zobacz wszystko|Усі|すべて|همه|查看全部'),
  personal_stats: R('Kişisel özet|Personal stats|Şəxsi statistika|Личная статистика|Estadísticas|Statistiques|Statistiken|Statistiche|Estatísticas|إحصائيات|Statistieken|Statystyki|Статистика|個人統計|آمار شخصی|个人数据'),
  last_30: R('Son 30 gün|Last 30 days|Son 30 gün|Последние 30 дней|Últimos 30 días|30 derniers jours|Letzte 30 Tage|Ultimi 30 giorni|Últimos 30 dias|آخر 30 يوماً|Laatste 30 dagen|Ostatnie 30 dni|Останні 30 днів|過去30日|۳۰ روز گذشته|近30天'),
  total_min: R('TOPLAM DAKİKA|TOTAL MINUTES|CƏMİ DƏQİQƏ|ВСЕГО МИНУТ|MINUTOS TOTALES|MINUTES TOTALES|MINUTEN GESAMT|MINUTI TOTALI|MINUTOS TOTAIS|إجمالي الدقائق|TOTALE MINUTEN|ŁĄCZNIE MINUT|УСЬОГО ХВИЛИН|合計分|مجموع دقیقه|总分钟'),
  active_days: R('AKTİF GÜN|ACTIVE DAYS|AKTİV GÜN|АКТИВНЫЕ ДНИ|DÍAS ACTIVOS|JOURS ACTIFS|AKTIVE TAGE|GIORNI ATTIVI|DIAS ATIVOS|أيام نشطة|ACTIEVE DAGEN|DNI AKTYWNE|АКТИВНІ ДНІ|活動日|روز فعال|活跃天数'),
  current_streak: R('ŞİMDİKİ SERİ|CURRENT STREAK|İNDİKİ SERİYA|ТЕКУЩАЯ СЕРИЯ|RACHA ACTUAL|SÉRIE ACTUELLE|AKTUELLE SERIE|SERIE ATTUALE|SEQUÊNCIA ATUAL|السلسلة الحالية|HUIDIGE REEKS|OBECNA SERIA|ПОТОЧНА СЕРІЯ|現在の連続|رشته فعلی|当前连续'),
  longest_streak: R('EN UZUN SERİ|LONGEST STREAK|ƏN UZUN SERİYA|САМАЯ ДЛИННАЯ|RACHA MÁS LARGA|PLUS LONGUE SÉRIE|LÄNGSTE SERIE|SERIE PIÙ LUNGA|MAIOR SEQUÊNCIA|أطول سلسلة|LANGSTE REEKS|NAJDŁUŻSZA SERIA|НАЙДОВША СЕРІЯ|最長連続|طولانی‌ترین رشته|最长连续'),
  share: R('Paylaş|Share|Paylaş|Поделиться|Compartir|Partager|Teilen|Condividi|Partilhar|مشاركة|Delen|Udostępnij|Поділитися|共有|اشتراک|分享'),
  chip_journey: R('YOL|JOURNEY|YOL|ПУТЬ|CAMINO|PARCOURS|WEG|PERCORSO|JORNADA|رحلة|REIS|DROGA|ШЛЯХ|旅|مسیر|旅程'),
  chip_program: R('PROGRAM|PROGRAM|PROQRAM|ПРОГРАММА|PROGRAMA|PROGRAMME|PROGRAMM|PROGRAMMA|PROGRAMA|برنامج|PROGRAMMA|PROGRAM|ПРОГРАМА|プログラム|برنامه|课程'),
  chip_sleep: R('UYKU|SLEEP|YUXU|СОН|SUEÑO|SOMMEIL|SCHLAF|SONNO|SONO|نوم|SLAAP|SEN|СОН|睡眠|خواب|睡眠'),
  chip_music: R('MÜZİK|MUSIC|MUSİQİ|МУЗЫКА|MÚSICA|MUSIQUE|MUSIK|MUSICA|MÚSICA|موسيقى|MUZIEK|MUZYKA|МУЗИКА|音楽|موسیقی|音乐'),
  chip_sound: R('SES|SOUND|SƏS|ЗВУК|SONIDO|SON|KLANG|SUONO|SOM|صوت|GELUID|DŹWIĘK|ЗВУК|サウンド|صدا|声音'),
  sleep_med: R('Uyku meditasyonları|Sleep meditations|Yuxu meditasiyaları|Медитации для сна|Meditaciones de sueño|Méditations sommeil|Schlafmeditationen|Meditazioni sonno|Meditações de sono|تأملات النوم|Slaapmeditaties|Medytacje snu|Медитації сну|睡眠瞑想|مدیتیشن خواب|睡眠冥想'),
  viz_med: R('Görselleştirme|Visualization meditations|Vizualizasiya|Визуализации|Visualización|Visualisation|Visualisierung|Visualizzazione|Visualização|التخيل|Visualisatie|Wizualizacja|Візуалізація|イメージ|تصویرسازی|可视化'),
  all_sounds: R('Tüm sesler|All Sounds|Bütün səslər|Все звуки|Todos los sonidos|Tous les sons|Alle Klänge|Tutti i suoni|Todos os sons|كل الأصوات|Alle geluiden|Wszystkie dźwięki|Усі звуки|すべての音|همه صداها|全部声音'),
  all_music: R('Tüm müzik|All Music|Bütün musiqi|Вся музыка|Toda la música|Toute la musique|Alle Musik|Tutta la musica|Toda a música|كل الموسيقى|Alle muziek|Cała muzyka|Вся музика|すべての音楽|همه موسیقی|全部音乐'),
  trending: R('Öne çıkan|Trending|Trend|В тренде|Tendencias|Tendances|Im Trend|Di tendenza|Em alta|رائج|Trending|Popularne|В тренді|トレンド|پرطرفدار|热门'),
  relaxing: R('RAHATLATICI|RELAXING SOUNDS|RAHATLADICI|РАССЛАБЛЯЮЩИЕ|RELAJANTES|RELAXANTS|BERUHIGEND|RILASSANTI|RELAXANTES|مهدئة|ONTSPANNEND|RELAKSUJĄCE|РОЗСЛАБЛЯЮЧІ|リラックス|آرام‌بخش|放松'),
  notify: R('Bildirim|Notifications|Bildiriş|Уведомления|Notificaciones|Notifications|Mitteilungen|Notifiche|Notificações|إشعارات|Meldingen|Powiadomienia|Сповіщення|通知|اعلان|通知'),
  level_badge: R('Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady'),
  month_aug: R('Ağustos|August|Avqust|Август|Agosto|Août|August|Agosto|Agosto|أغسطس|Augustus|Sierpień|Серпень|8月|اوت|八月'),
  close: R('Kapat|Close|Bağla|Закрыть|Cerrar|Fermer|Schließen|Chiudi|Fechar|إغلاق|Sluiten|Zamknij|Закрити|閉じる|بستن|关闭'),
  no_results: R('Eşleşme yok.|No matches.|Uyğunluq yox.|Нет совпадений.|Sin resultados.|Aucun résultat.|Keine Treffer.|Nessun risultato.|Sem resultados.|لا نتائج.|Geen resultaten.|Brak wyników.|Немає збігів.|一致なし。|نتیجه‌ای نیست.|无结果。'),
  saved: R('Kaydedildi.|Saved.|Yadda saxlandı.|Сохранено.|Guardado.|Enregistré.|Gespeichert.|Salvato.|Guardado.|تم الحفظ.|Opgeslagen.|Zapisano.|Збережено.|保存しました。|ذخیره شد.|已保存。'),

  disc_title: R('Keşfet|Explore|Kəşf et|Обзор|Explorar|Explorer|Entdecken|Esplora|Explorar|استكشف|Ontdek|Odkryj|Огляд|探す|کاوش|探索'),
  timer: R('Zamanlayıcı|Timer|Taymer|Таймер|Temporizador|Minuteur|Timer|Timer|Temporizador|مؤقت|Timer|Minutnik|Таймер|タイマー|تایمر|计时'),
  thunder_rain: R('Gök ve yağmur|Thunder and Rain|Şimşək və yağış|Гром и дождь|Trueno y lluvia|Tonnerre et pluie|Donner und Regen|Tuono e pioggia|Trovão e chuva|رعد ومطر|Donder en regen|Grzmot i deszcz|Грім і дощ|雷と雨|رعد و باران|雷雨'),
  new_badge: R('YENİ|NEW|YENİ|НОВОЕ|NUEVO|NOUVEAU|NEU|NUOVO|NOVO|جديد|NIEUW|NOWE|НОВЕ|新着|جدید|新'),
  sos_short: R('SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS'),
  hold_save: R('Uzun bas, kaydet.|Long-press to save.|Basılı saxla, yadda saxla.|Долгое нажатие — сохранить.|Mantén pulsado para guardar.|Appui long pour enregistrer.|Lange drücken zum Speichern.|Tieni premuto per salvare.|Pressiona para guardar.|اضغط مطولاً للحفظ.|Lang indrukken om te bewaren.|Przytrzymaj, aby zapisać.|Утримуй, щоб зберегти.|長押しで保存。|برای ذخیره نگه دارید.|长按保存。'),
  home_kicker: R('Steady · 6 dil|Steady · 6 languages|Steady · 6 idiomas|Steady · 6 langues|Steady · 6 Sprachen|Steady · 6 lingue'),
  listen: R('Dinle|Listen|Escuchar|Écouter|Hören|Ascolta'),
  tonight: R('Bu gece|Tonight|Esta noche|Cette nuit|Heute Nacht|Stasera'),
  for_you: R('Sana göre|For you|Para ti|Pour toi|Für dich|Per te'),
  now_playing: R('Çalıyor|Now playing|Reproduciendo|En lecture|Läuft|In riproduzione'),
  voice: R('Okuma sesi|Reading voice|Voz de lectura|Voix de lecture|Lesestimme|Voce di lettura'),
  voice_hint: R('En doğal sesi seç. Cihazındaki sesler değişir. Chrome veya Safari genelde daha insansı.|Pick the most natural voice. Voices depend on this device. Chrome or Safari usually sound more human.|Elige la voz más natural. Las voces dependen de este dispositivo. Chrome o Safari suenan más humanas.|Choisis la voix la plus naturelle. Les voix dépendent de cet appareil. Chrome ou Safari sonnent plus humain.|Wähle die natürlichste Stimme. Stimmen hängen von diesem Gerät ab. Chrome oder Safari klingen menschlicher.|Scegli la voce più naturale. Le voci dipendono da questo dispositivo. Chrome o Safari suonano più umane.'),
  voice_try: R('Dene|Try|Probar|Essayer|Testen|Prova'),
  voice_none: R('Bu dil için ses yok. Chrome veya Safari dene.|No voice for this language. Try Chrome or Safari.|No hay voz para este idioma. Prueba Chrome o Safari.|Pas de voix pour cette langue. Essaie Chrome ou Safari.|Keine Stimme für diese Sprache. Chrome oder Safari versuchen.|Nessuna voce per questa lingua. Prova Chrome o Safari.'),
  voice_auto: R('Otomatik (en doğal)|Automatic (most natural)|Automático (más natural)|Automatique (le plus naturel)|Automatisch (am natürlichsten)|Automatico (più naturale)'),
  voice_pace: R('Okuma hızı|Reading pace|Ritmo de lectura|Rythme de lecture|Lesetempo|Ritmo di lettura'),
  voice_natural: R('Normal|Normal|Normal|Normal|Normal|Normale'),
  voice_calm: R('Meditasyon|Meditation|Meditación|Méditation|Meditation|Meditazione'),
  voice_slow: R('Yavaş|Slow|Lento|Lent|Langsam|Lento'),
  voice_pace_hint: R('Normal: günlük okuma. Meditasyon: uzun cümle, nefes boşluğu. Yavaş: eski kesik tempo.|Normal: everyday reading. Meditation: long phrases with breath space. Slow: the old chopped tempo.|Normal: lectura cotidiana. Meditación: frases largas y pausas. Lento: el tempo troceado.|Normal : lecture du quotidien. Méditation : phrases longues, silences. Lent : l’ancien tempo coupé.|Normal: Alltag. Meditation: lange Sätze, Atempausen. Langsam: das alte zerteilte Tempo.|Normale: lettura quotidiana. Meditazione: frasi lunghe e pause. Lento: il vecchio ritmo spezzato.'),
  tonight_sub: R('Açık bırak, yavaş kalsın.|Leave it on, keep it slow.|Déjalo puesto, despacio.|Laisse tourner, tout doucement.|Lass es laufen, bleib langsam.|Lascialo acceso, piano.'),
  for_you_sub: R('Bu ruh hâline göre.|Matched to this mood.|Según este ánimo.|Selon cette humeur.|Passend zu dieser Stimmung.|In base a questo umore.'),
  new_sounds: R('Yeni sesler|New sounds|Sonidos nuevos|Nouveaux sons|Neue Klänge|Suoni nuovi'),
  stop_now: R('Durdur|Stop|Parar|Arrêter|Stopp|Ferma'),
  now_rail: R('Şimdi|Now|Ahora|Maintenant|Jetzt|Adesso'),
  bed_on: R('Yatak sesi|Bed sound|Sonido de fondo|Fond sonore|Bettklang|Suono di letto'),
  lang_now: R('Dil|Language|Idioma|Langue|Sprache|Lingua'),
  dim: R('Loş|Dim|Tenue|Tamisé|Gedimmt|Soffuso'),
  sos_ground: R('3 nesne|3 objects|3 objetos|3 objets|3 Dinge|3 oggetti'),
  sos_ground_sub: R('Odaya bak. Bir nesne seç. Rengini söyle. Dokun.|Look around. Pick one object. Name its color. Touch it.|Mira la habitación. Elige un objeto. Di el color. Tócalo.|Regarde la pièce. Choisis un objet. Dis sa couleur. Touche-le.|Schau in den Raum. Wähle einen Gegenstand. Sag die Farbe. Berühre ihn.|Guarda la stanza. Scegli un oggetto. Dì il colore. Toccalo.'),
  sos_obj_1: R('Birinci nesne. Bak. Rengini seç.|First object. Look. Pick the color.|Primer objeto. Mira. Elige el color.|Premier objet. Regarde. Choisis la couleur.|Erstes Ding. Schau. Wähle die Farbe.|Primo oggetto. Guarda. Scegli il colore.'),
  sos_obj_2: R('İkinci nesne. Başka bir şey. Renk.|Second object. A different one. Color.|Segundo objeto. Otro. Color.|Deuxième objet. Un autre. Couleur.|Zweites Ding. Ein anderes. Farbe.|Secondo oggetto. Un altro. Colore.'),
  sos_obj_3: R('Üçüncü. Buna dokun. Isı, ağırlık, pürüz.|Third. Touch it. Heat, weight, texture.|Tercero. Tócalo. Calor, peso, textura.|Troisième. Touche-le. Chaleur, poids, grain.|Drittes. Berühre es. Wärme, Gewicht, Struktur.|Terzo. Toccalo. Calore, peso, trama.'),
  sos_touched: R('Dokundum|I touched it|Lo toqué|Je l’ai touché|Berührt|L’ho toccato'),
  sos_feet: R('İki tabanı yere bas. Ağırlığını ver.|Press both feet into the floor. Give them the weight.|Presiona los dos pies en el suelo. Dales el peso.|Pose les deux pieds au sol. Donne-leur le poids.|Drücke beide Füße in den Boden. Gib ihnen das Gewicht.|Spingi entrambi i piedi a terra. Dà loro il peso.'),
  sos_feet_btn: R('Bastım|Pressed|Pisado|Posé|Gedrückt|Premuto'),
  sos_then_breath: R('Sonra nefes|Then breath|Luego la respiración|Ensuite le souffle|Dann der Atem|Poi il respiro'),
  sos_c_red: R('Kırmızı|Red|Rojo|Rouge|Rot|Rosso'),
  sos_c_blue: R('Mavi|Blue|Azul|Bleu|Blau|Blu'),
  sos_c_green: R('Yeşil|Green|Verde|Vert|Grün|Verde'),
  sos_c_yellow: R('Sarı|Yellow|Amarillo|Jaune|Gelb|Giallo'),
  sos_c_white: R('Beyaz|White|Blanco|Blanc|Weiß|Bianco'),
  sos_c_black: R('Siyah|Black|Negro|Noir|Schwarz|Nero'),
  sos_c_wood: R('Ahşap|Wood|Madera|Bois|Holz|Legno'),
  sos_c_gray: R('Gri|Gray|Gris|Gris|Grau|Grigio'),
  sos_left: R('Sol taban|Left sole|Planta izquierda|Plante gauche|Linke Sohle|Pianta sinistra'),
  sos_right: R('Sağ taban|Right sole|Planta derecha|Plante droite|Rechte Sohle|Pianta destra'),
  more_objects: R('3 nesne|3 objects|3 objetos|3 objets|3 Dinge|3 oggetti'),
  more_room: R('Odadaki ses|Room sound|Sonido de la habitación|Son de la pièce|Raumklang|Suono della stanza'),
  more_colors: R('Üç renk|Three colors|Tres colores|Trois couleurs|Drei Farben|Tre colori'),
  tab_natural: R('Doğa|Natural|Natural|Naturel|Natur|Natura'),
  tab_meditation: R('Meditasyon|Meditation|Meditación|Méditation|Meditation|Meditazione'),
  tab_tones: R('Tonlar|Tones|Tonos|Tones|Töne|Toni'),
  tab_indoor: R('İç mekân|Indoor|Interior|Intérieur|Innen|Interno'),
  chip_quick: R('Kısa pratikler|Quick practices|Prácticas rápidas|Pratiques rapides|Kurze Übungen|Pratiche rapide'),
  chip_talks: R('Konuşmalar|Talks|Charlas|Causeries|Gespräche|Discorsi'),
  chip_work: R('İş için|For work|Para el trabajo|Pour le travail|Für die Arbeit|Per il lavoro'),
  chip_exercises: R('Egzersizler|Exercises|Ejercicios|Exercices|Übungen|Esercizi'),
  chip_newsletter: R('Bülten|Newsletter|Boletín|Lettre|Brief|Lettera'),
  chip_journeys: R('Yolculuklar|Journeys|Viajes|Parcours|Reisen|Percorsi'),
  chip_guide: R('Rehber|Guide|Guía|Guide|Leitfaden|Guida'),
  chip_podcast: R('Podcast|Podcast|Podcast|Podcast|Podcast|Podcast'),
  sleep_stories: R('Uyku hikâyeleri|Sleep stories|Relatos de sueño|Récits du sommeil|Schlafgeschichten|Racconti del sonno'),
  sleep_sounds: R('Uyku sesleri|Sleep sounds|Sonidos de sueño|Sons du sommeil|Schlafklänge|Suoni del sonno'),
  sleep_music: R('Uyku müziği|Sleep music|Música de sueño|Musique sommeil|Schlafmusik|Musica del sonno'),
  for_kids: R('Çocuklar için|For kids|Para niños|Pour enfants|Für Kinder|Per bambini'),
  myth_stories: R('Mitolojik hikâyeler|Mythological stories|Relatos míticos|Récits mythiques|Mythische Geschichten|Racconti mitici'),
  instrumental: R('Enstrümantal|Instrumental sounds|Instrumental|Instrumental|Instrumental|Strumentali'),
  noise: R('Gürültü|Noise|Ruido|Bruit|Rauschen|Rumore'),
  rain_sounds: R('Yağmur sesleri|Rain sounds|Sonidos de lluvia|Sons de pluie|Regenklänge|Suoni di pioggia'),
  more_sleep: R('Uyku hakkında|More about sleep|Más sobre el sueño|Plus sur le sommeil|Mehr über Schlaf|Di più sul sonno'),
  focus_mode: R('Odak|Focus mode|Modo foco|Mode focus|Fokusmodus|Modalità focus'),
  mystical: R('Mistik sesler|Mystical sounds|Sonidos místicos|Sons mystiques|Mystische Klänge|Suoni mistici'),
  music_radio: R('Müzik radyosu|Music radio|Radio de música|Radio musique|Musikradio|Radio musica'),
  meditative_music: R('Meditatif müzik|Meditative music|Música meditativa|Musique méditative|Meditative Musik|Musica meditativa'),
  nature_sounds: R('Doğa sesleri|Nature sounds|Sonidos de la naturaleza|Sons de nature|Naturklänge|Suoni della natura'),
  theme: R('Görünüm|Appearance|Apariencia|Apparence|Erscheinung|Aspetto'),
  theme_dark: R('Koyu|Dark mode|Oscuro|Sombre|Dunkel|Scuro'),
  theme_light: R('Açık|Light mode|Claro|Clair|Hell|Chiaro'),
  presence_now: R('Şu anda da nefes alanlar var|People are meditating right now|Ahora también hay quien respira|Il y a aussi, maintenant, des souffles|Auch jetzt atmen Menschen|Anche ora c’è chi respira'),
  presence_sub: R('Canlı bir sayaç değil. Bu saatte de bir oda, bir nefes.|Not a live counter. A reminder that a room and a breath exist at this hour too.|No es un contador en vivo. Un recordatorio: a esta hora también hay una habitación, un aliento.|Ce n’est pas un compteur en direct. Un rappel : à cette heure aussi, une pièce, un souffle.|Kein Live-Zähler. Eine Erinnerung: auch um diese Stunde gibt es einen Raum, einen Atem.|Non è un contatore dal vivo. Un richiamo: anche a quest’ora c’è una stanza, un respiro.'),
  presence_live: R('{n} kişi meditasyon yapıyor|{n} people meditating|{n} personas meditando|{n} personnes méditent|{n} Menschen meditieren|{n} persone meditano'),
  mood_history: R('Ruh hâli geçmişi|Mood history|Historial de ánimo|Historique d’humeur|Stimmungsverlauf|Cronologia umore'),
  freeze_title: R('Seri donması|Streak freeze|Congelación de racha|Gel de série|Serien-Freeze|Blocco serie'),
  freeze_left: R('Bu hafta {n} donma hakkı kaldı|{n} freeze left this week|Queda {n} congelación esta semana|{n} gel restant cette semaine|{n} Freeze diese Woche übrig|{n} blocco rimasto questa settimana'),
  freeze_use: R('Dünü ört|Cover yesterday|Cubrir ayer|Couvrir hier|Gestern abdecken|Copri ieri'),
  freeze_used: R('Bu hafta kullanıldı|Used this week|Usado esta semana|Utilisé cette semaine|Diese Woche benutzt|Usato questa settimana'),
  freeze_ok: R('Dün örtüldü. Seri duruyor.|Yesterday is covered. The streak holds.|Ayer quedó cubierto. La racha sigue.|Hier est couvert. La série tient.|Gestern ist gedeckt. Die Serie hält.|Ieri è coperto. La serie tiene.'),
  skills_title: R('Beceriler|Skills|Habilidades|Compétences|Fähigkeiten|Abilità'),
  skill_wellbeing: R('İyi oluş|Wellbeing|Bienestar|Bien-être|Wohlbefinden|Benessere'),
  skill_performance: R('Performans|Performance|Rendimiento|Performance|Leistung|Prestazione'),
  skill_focus: R('Odak|Focus|Foco|Focus|Fokus|Focus'),
  skill_sleep: R('Uyku|Sleep|Sueño|Sommeil|Schlaf|Sonno'),
  skill_breath: R('Nefes|Breath|Aliento|Souffle|Atem|Respiro'),
  skill_ground: R('Yer|Ground|Suelo|Ancrage|Boden|Terra'),
  skill_kindness: R('Nezaket|Kindness|Amabilidad|Gentillesse|Güte|Gentilezza'),
  skill_patience: R('Sabır|Patience|Paciencia|Patience|Geduld|Pazienza'),
  skill_presence: R('Hazır oluş|Presence|Presencia|Présence|Gegenwart|Presenza'),
  skill_body: R('Beden|Body|Cuerpo|Corps|Körper|Corpo'),
  skill_night: R('Gece|Night|Noche|Nuit|Nacht|Notte'),
  skill_courage: R('Cesaret|Courage|Coraje|Courage|Mut|Coraggio'),
  skill_locked: R('Göstermeye devam et.|Keep showing up.|Sigue apareciendo.|Continue à te montrer.|Weiter erscheinen.|Continua a presentarti.'),
  breath_rail: R('Nefes egzersizleri|Breath exercises|Ejercicios de respiración|Exercices de souffle|Atemübungen|Esercizi di respiro'),
  med_pct: R('{n}% tamamlandı|{n}% complete|{n}% completado|{n}% terminé|{n}% fertig|{n}% completato'),
  med_step: R('{n}. seans|Session {n}|Sesión {n}|Séance {n}|Sitzung {n}|Sessione {n}'),
  med_locked: R('Önceki seansı bitir|Finish the previous session|Termina la sesión anterior|Termine la séance précédente|Vorherige Sitzung beenden|Termina la sessione precedente'),
  med_done: R('Tamamlandı|Done|Hecho|Terminé|Fertig|Fatto'),
  med_tap: R('Dokun: süre|Tap: time|Toca: tiempo|Toucher : temps|Tippen: Zeit|Tocca: tempo'),
} as const
