/** 16-dil ekleri. strings.ts içinde CORE üzerine yayılır. */
import { R } from './locales'

export const EXTRA = {
  hello: R('Merhaba|Hello|Salam|Привет|Hola|Bonjour|Hallo|Ciao|Olá|مرحبا|Hallo|Cześć|Привіт|こんにちは|سلام|你好'),
  mood_check: R('Ruh hâli|Mood check-in|Əhval|Настроение|Ánimo|Humeur|Stimmung|Umore|Humor|المزاج|Stemming|Nastrój|Настрій|気分|حال|心情'),
  mood_calm: R('Sakin|Calm|Sakit|Спокойно|Tranquilo|Calme|Ruhig|Calmo|Calmo|هادئ|Kalm|Spokój|Спокій|穏やか|آرام|平静'),
  mood_tense: R('Gergin|Tense|Gərgin|Напряжённо|Tenso|Tendu|Angespannt|Teso|Tenso|متوتر|Gespannen|Napięcie|Напруга|緊張|تنش|紧张'),
  mood_sleepless: R('Uykusuz|Sleepless|Yuxusuz|Бессонница|Sin sueño|Sans sommeil|Schlaflos|Insonne|Sem sono|أرق|Slapeloos|Bezsenność|Безсоння|眠れない|بی‌خواب|失眠'),
  mood_wave: R('Dalgalı|Wavy|Dalğalı|Волнами|Oleaje|Vague|Wellig|Ondoso|Ondulado|موج|Golvend|Falujący|Хвилями|波打つ|موج‌دار|波动'),
  mood_distant: R('Uzak|Distant|Uzaq|Далеко|Lejano|Lointain|Fern|Lontano|Distante|بعيد|Ver|Odległy|Далеко|遠い|دور|疏远'),
  search: R('Ara|Search|Axtar|Поиск|Buscar|Rechercher|Suchen|Cerca|Pesquisar|بحث|Zoeken|Szukaj|Пошук|検索|جستجو|搜索'),
  search_ph: R('Meditasyon, ses, hikâye…|Meditation, sound, story…|Meditasiya, səs, hekayə…|Медитация, звук, история…|Meditación, sonido, historia…|Méditation, son, histoire…|Meditation, Klang, Geschichte…|Meditazione, suono, storia…|Meditação, som, história…|تأمل، صوت، قصة…|Meditatie, geluid, verhaal…|Medytacja, dźwięk, historia…|Медитація, звук, історія…|瞑想、音、物語…|مدیتیشن، صدا، داستان…|冥想、声音、故事…'),
  view_details: R('Ayrıntı|View details|Ətraflı|Подробнее|Ver detalles|Voir|Details|Dettagli|Detalhes|التفاصيل|Details|Szczegóły|Деталі|詳細|جزئیات|详情'),
  daily_rec: R('Günün önerileri|Daily recommendations|Günün tövsiyələri|Рекомендации дня|Recomendaciones|Recommandations|Empfehlungen|Consigli del giorno|Recomendações|توصيات اليوم|Aanbevelingen|Rekomendacje|Рекомендації|今日のおすすめ|پیشنهادهای امروز|今日推荐'),
  favorites: R('Favoriler|Favorites|Sevimlilər|Избранное|Favoritos|Favoris|Favoriten|Preferiti|Favoritos|المفضلة|Favorieten|Ulubione|Обране|お気に入り|علاقه‌مندی‌ها|收藏'),
  fav_empty: R('Henüz yok. Bir karta uzun basınca eklenir.|None yet. Long-press a card to add one.|Hələ yoxdur. Kartı basılı saxla.|Пока пусто. Долгое нажатие на карточку.|Aún no. Mantén pulsada una tarjeta.|Pas encore. Appui long sur une carte.|Noch keine. Karte lange drücken.|Ancora nessuno. Tieni premuta una scheda.|Ainda não. Pressione e segure um cartão.|لا شيء بعد. اضغط مطولاً على بطاقة.|Nog geen. Houd een kaart ingedrukt.|Jeszcze brak. Przytrzymaj kartę.|Поки порожньо. Утримуй картку.|まだありません。カードを長押し。|هنوز نیست. کارت را نگه دارید.|暂无。长按卡片添加。'),
  breathing: R('Nefes|Breathing|Nəfəs|Дыхание|Respiración|Respiration|Atmung|Respiro|Respiração|التنفس|Adem|Oddech|Дихання|呼吸|تنفس|呼吸'),
  start_med: R('Meditasyona başla|Start meditating|Meditasiyaya başla|Начать медитацию|Empezar a meditar|Commencer|Meditation starten|Inizia a meditare|Começar|ابدأ التأمل|Begin mediteren|Zacznij medytować|Почати медитацію|瞑想を始める|شروع مدیتیشن|开始冥想'),
  programs: R('Programlar|Meditation programs|Proqramlar|Программы|Programas|Programmes|Programme|Programmi|Programas|برامج|Programma\'s|Programy|Програми|プログラム|برنامه‌ها|课程'),
  premium_banner: R('Ücretsiz deneme ile Pro’yu aç.|Start your Premium membership with free trial now.|Pulsuz sınaqla Pro-nu aç.|Откройте Pro с бесплатным пробным периодом.|Empieza Premium con prueba gratis.|Ouvre Pro avec l’essai gratuit.|Pro mit kostenloser Testphase starten.|Apri Pro con la prova gratuita.|Abra o Pro com o teste grátis.|ابدأ التجربة المجانية لـ Pro.|Start Pro met gratis proefperiode.|Otwórz Pro z bezpłatnym okresem próbnym.|Відкрий Pro з безкоштовним пробним.|無料トライアルでProを始める。|آزمایش رایگان Pro را شروع کنید.|免费试用开启 Pro。'),
  view_all_short: R('Tümü|View all|Hamısı|Все|Ver todo|Tout voir|Alle|Vedi tutto|Ver tudo|عرض الكل|Alles|Zobacz wszystko|Усі|すべて|همه|查看全部'),
  personal_stats: R('Kişisel özet|Personal stats|Şəxsi statistika|Личная статистика|Estadísticas|Statistiques|Statistiken|Statistiche|Estatísticas|إحصائيات|Statistieken|Statystyki|Статистика|個人統計|آمار شخصی|个人数据'),
  last_30: R('Son 30 gün|Last 30 days|Son 30 gün|Последние 30 дней|Últimos 30 días|30 derniers jours|Letzte 30 Tage|Ultimi 30 giorni|Últimos 30 dias|آخر 30 يوماً|Laatste 30 dagen|Ostatnie 30 dni|Останні 30 днів|過去30日|۳۰ روز گذشته|近30天'),
  total_min: R('TOPLAM DAKİKA|TOTAL MINUTES|CƏMİ DƏQİQƏ|ВСЕГО МИНУТ|MINUTOS TOTALES|MINUTES TOTALES|MINUTEN GESAMT|MINUTI TOTALI|MINUTOS TOTAIS|إجمالي الدقائق|TOTALE MINUTEN|ŁĄCZNIE MINUT|УСЬОГО ХВИЛИН|合計分|مجموع دقیقه|总分钟'),
  active_days: R('AKTİF GÜN|ACTIVE DAYS|AKTİV GÜN|АКТИВНЫЕ ДНИ|DÍAS ACTIVOS|JOURS ACTIFS|AKTIVE TAGE|GIORNI ATTIVI|DIAS ATIVOS|أيام نشطة|ACTIEVE DAGEN|DNI AKTYWNE|АКТИВНІ ДНІ|活動日|روز فعال|活跃天数'),
  current_streak: R('ŞİMDİKİ SERİ|CURRENT STREAK|İNDİKİ SERİYA|ТЕКУЩАЯ СЕРИЯ|RACHA ACTUAL|SÉRIE ACTUELLE|AKTUELLE SERIE|SERIE ATTUALE|SEQUÊNCIA ATUAL|السلسلة الحالية|HUIDIGE REEKS|OBECNA SERIA|ПОТОЧНА СЕРІЯ|現在の連続|رشته فعلی|当前连续'),
  longest_streak: R('EN UZUN SERİ|LONGEST STREAK|ƏN UZUN SERİYA|САМАЯ ДЛИННАЯ|RACHA MÁS LARGA|PLUS LONGUE SÉRIE|LÄNGSTE SERIE|SERIE PIÙ LUNGA|MAIOR SEQUÊNCIA|أطول سلسلة|LANGSTE REEKS|NAJDŁUŻSZA SERIA|НАЙДОВША СЕРІЯ|最長連続|طولانی‌ترین رشته|最长连续'),
  share: R('Paylaş|Share|Paylaş|Поделиться|Compartir|Partager|Teilen|Condividi|Partilhar|مشاركة|Delen|Udostępnij|Поділитися|共有|اشتراک|分享'),
  chip_journey: R('YOL|JOURNEY|YOL|ПУТЬ|CAMINO|PARCOURS|WEG|PERCORSO|JORNADA|رحلة|REIS|DROGA|ШЛЯХ|旅|مسیر|旅程'),
  chip_program: R('PROGRAM|PROGRAM|PROQRAM|ПРОГРАММА|PROGRAMA|PROGRAMME|PROGRAMM|PROGRAMMA|PROGRAMA|برنامج|PROGRAMMA|PROGRAM|ПРОГРАМА|プログラム|برنامه|课程'),
  chip_sleep: R('UYKU|SLEEP|YUXU|СОН|SUEÑO|SOMMEIL|SCHLAF|SONNO|SONO|نوم|SLAAP|SEN|СОН|睡眠|خواب|睡眠'),
  chip_music: R('MÜZİK|MUSIC|MUSİQİ|МУЗЫКА|MÚSICA|MUSIQUE|MUSIK|MUSICA|MÚSICA|موسيقى|MUZIEK|MUZYKA|МУЗИКА|音楽|موسیقی|音乐'),
  chip_sound: R('SES|SOUND|SƏS|ЗВУК|SONIDO|SON|KLANG|SUONO|SOM|صوت|GELUID|DŹWIĘK|ЗВУК|サウンド|صدا|声音'),
  sleep_med: R('Uyku meditasyonları|Sleep meditations|Yuxu meditasiyaları|Медитации для сна|Meditaciones de sueño|Méditations sommeil|Schlafmeditationen|Meditazioni sonno|Meditações de sono|تأملات النوم|Slaapmeditaties|Medytacje snu|Медитації сну|睡眠瞑想|مدیتیشن خواب|睡眠冥想'),
  viz_med: R('Görselleştirme|Visualization meditations|Vizualizasiya|Визуализации|Visualización|Visualisation|Visualisierung|Visualizzazione|Visualização|التخيل|Visualisatie|Wizualizacja|Візуалізація|イメージ|تصویرسازی|可视化'),
  all_sounds: R('Tüm sesler|All Sounds|Bütün səslər|Все звуки|Todos los sonidos|Tous les sons|Alle Klänge|Tutti i suoni|Todos os sons|كل الأصوات|Alle geluiden|Wszystkie dźwięki|Усі звуки|すべての音|همه صداها|全部声音'),
  all_music: R('Tüm müzik|All Music|Bütün musiqi|Вся музыка|Toda la música|Toute la musique|Alle Musik|Tutta la musica|Toda a música|كل الموسيقى|Alle muziek|Cała muzyka|Вся музика|すべての音楽|همه موسیقی|全部音乐'),
  trending: R('Öne çıkan|Trending|Trend|В тренде|Tendencias|Tendances|Im Trend|Di tendenza|Em alta|رائج|Trending|Popularne|В тренді|トレンド|پرطرفدار|热门'),
  relaxing: R('RAHATLATICI|RELAXING SOUNDS|RAHATLADICI|РАССЛАБЛЯЮЩИЕ|RELAJANTES|RELAXANTS|BERUHIGEND|RILASSANTI|RELAXANTES|مهدئة|ONTSPANNEND|RELAKSUJĄCE|РОЗСЛАБЛЯЮЧІ|リラックス|آرام‌بخش|放松'),
  notify: R('Bildirim|Notifications|Bildiriş|Уведомления|Notificaciones|Notifications|Mitteilungen|Notifiche|Notificações|إشعارات|Meldingen|Powiadomienia|Сповіщення|通知|اعلان|通知'),
  level_badge: R('Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady|Steady'),
  month_aug: R('Ağustos|August|Avqust|Август|Agosto|Août|August|Agosto|Agosto|أغسطس|Augustus|Sierpień|Серпень|8月|اوت|八月'),
  close: R('Kapat|Close|Bağla|Закрыть|Cerrar|Fermer|Schließen|Chiudi|Fechar|إغلاق|Sluiten|Zamknij|Закрити|閉じる|بستن|关闭'),
  no_results: R('Eşleşme yok.|No matches.|Uyğunluq yox.|Нет совпадений.|Sin resultados.|Aucun résultat.|Keine Treffer.|Nessun risultato.|Sem resultados.|لا نتائج.|Geen resultaten.|Brak wyników.|Немає збігів.|一致なし。|نتیجه‌ای نیست.|无结果。'),
  saved: R('Kaydedildi.|Saved.|Yadda saxlandı.|Сохранено.|Guardado.|Enregistré.|Gespeichert.|Salvato.|Guardado.|تم الحفظ.|Opgeslagen.|Zapisano.|Збережено.|保存しました。|ذخیره شد.|已保存。'),

  disc_title: R('Keşfet|Explore|Kəşf et|Обзор|Explorar|Explorer|Entdecken|Esplora|Explorar|استكشف|Ontdek|Odkryj|Огляд|探す|کاوش|探索'),
  timer: R('Zamanlayıcı|Timer|Taymer|Таймер|Temporizador|Minuteur|Timer|Timer|Temporizador|مؤقت|Timer|Minutnik|Таймер|タイマー|تایمر|计时'),
  thunder_rain: R('Gök ve yağmur|Thunder and Rain|Şimşək və yağış|Гром и дождь|Trueno y lluvia|Tonnerre et pluie|Donner und Regen|Tuono e pioggia|Trovão e chuva|رعد ومطر|Donder en regen|Grzmot i deszcz|Грім і дощ|雷と雨|رعد و باران|雷雨'),
  new_badge: R('YENİ|NEW|YENİ|НОВОЕ|NUEVO|NOUVEAU|NEU|NUOVO|NOVO|جديد|NIEUW|NOWE|НОВЕ|新着|جدید|新'),
  sos_short: R('SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS'),
  hold_save: R('Uzun bas, kaydet.|Long-press to save.|Basılı saxla, yadda saxla.|Долгое нажатие — сохранить.|Mantén pulsado para guardar.|Appui long pour enregistrer.|Lange drücken zum Speichern.|Tieni premuto per salvare.|Pressiona para guardar.|اضغط مطولاً للحفظ.|Lang indrukken om te bewaren.|Przytrzymaj, aby zapisać.|Утримуй, щоб зберегти.|長押しで保存。|برای ذخیره نگه دارید.|长按保存。'),
} as const
