import { pickLocale, R, type LocaleId } from './locales'

export function sosSentences(locale: LocaleId): string[] {
  const rows = [
    R('Bu anda bedenim güvenli bir yerde.|Right now my body is in a safe place.|Bu anda bədənim təhlükəsiz yerdədir.|Сейчас моё тело в безопасном месте.|Ahora mismo mi cuerpo está en un lugar seguro.|En cet instant mon corps est en lieu sûr.|In diesem Moment ist mein Körper an einem sicheren Ort.|In questo momento il mio corpo è in un posto sicuro.|Neste instante o meu corpo está num lugar seguro.|في هذه اللحظة جسدي في مكان آمن.|Op dit moment is mijn lijf op een veilige plek.|W tej chwili moje ciało jest w bezpiecznym miejscu.|Зараз моє тіло в безпечному місці.|いま、私の体は安全な場所にある。|در این لحظه بدنم در جای امن است.|此刻，我的身体在安全的地方。'),
    R('Dalga geçiyor, ben burada kalıyorum.|The wave is passing; I stay here.|Dalğa keçir, mən burada qalıram.|Волна проходит, я остаюсь здесь.|La ola pasa; yo me quedo aquí.|La vague passe ; je reste ici.|Die Welle geht vorbei; ich bleibe hier.|L’onda passa; io resto qui.|A onda passa; eu fico aqui.|الموج يمر؛ أنا أبقى هنا.|De golf gaat voorbij; ik blijf hier.|Fala mija; ja tu zostaję.|Хвиля минає; я лишаюся тут.|波は過ぎていく。私はここにいる。|موج می‌گذرد؛ من اینجا می‌مانم.|浪在过去；我留在这里。'),
    R('Nefesim şu an bana yeter.|This breath is enough for me now.|Nəfəsim indilik mənə bəsdir.|Этого дыхания мне сейчас довольно.|Esta respiración me basta ahora.|Ce souffle me suffit maintenant.|Dieser Atem reicht mir jetzt.|Questo respiro mi basta ora.|Este fôlego basta-me agora.|هذا النفس يكفيني الآن.|Deze adem is nu genoeg.|Ten oddech mi teraz wystarczy.|Цього подиху мені зараз досить.|この息で、今は足りる。|این نفس حالا برایم بس است.|这一口气，此刻够了。'),
    R('Ayaklarım yerde, odam gerçek.|My feet are on the ground; the room is real.|Ayaqlarım yerdədir, otağım gerçəkdir.|Ноги на земле, комната настоящая.|Mis pies están en el suelo; la habitación es real.|Mes pieds sont au sol ; la pièce est réelle.|Meine Füße sind auf dem Boden; der Raum ist wirklich.|I piedi sono a terra; la stanza è reale.|Os pés estão no chão; o quarto é real.|قدماي على الأرض؛ الغرفة حقيقية.|Mijn voeten staan op de grond; de kamer is echt.|Stopy na ziemi; pokój jest prawdziwy.|Стопи на землі; кімната справжня.|足は地面。部屋は本物だ。|پاهایم روی زمین است؛ اتاق واقعی است.|脚在地上；房间是真的。'),
    R('Bu his yoğun, ve geçici.|This feeling is intense, and temporary.|Bu hiss güclüdür və keçicidir.|Это чувство сильно — и временно.|Esta sensación es intensa, y temporal.|Cette sensation est intense, et temporaire.|Dieses Gefühl ist heftig — und vorübergehend.|Questa sensazione è intensa, e temporanea.|Esta sensação é intensa, e temporária.|هذا الإحساس شديد وهو مؤقت.|Dit gevoel is hevig, en tijdelijk.|To uczucie jest intensywne i chwilowe.|Це відчуття сильне — і тимчасове.|この感覚は強い。そして一時的だ。|این حس شدید است، و گذرا.|这感觉很强，也是暂时的。'),
    R('Göğsüm açılıyor, omuzlarım iniyor.|My chest opens; my shoulders drop.|Sinəm açılır, çiyinlərim enir.|Грудь раскрывается, плечи опускаются.|El pecho se abre; los hombros bajan.|La poitrine s’ouvre ; les épaules descendent.|Die Brust öffnet sich; die Schultern sinken.|Il petto si apre; le spalle scendono.|O peito abre-se; os ombros descem.|صدري ينفتح؛ كتفاي تهبطان.|Mijn borst opent; mijn schouders zakken.|Klatka się otwiera; ramiona opadają.|Груди розкриваються; плечі опускаються.|胸が開く。肩が下りる。|سینه‌ام باز می‌شود؛ شانه‌هایم فرو می‌آیند.|胸口打开，肩膀落下。'),
    R('Şimdi sadece bu nefes var.|Right now there is only this breath.|İndi yalnız bu nəfəs var.|Сейчас есть только это дыхание.|Ahora solo está este aliento.|Il n’y a maintenant que ce souffle.|Jetzt gibt es nur diesen Atem.|Adesso c’è solo questo respiro.|Agora só existe este fôlego.|الآن ليس سوى هذا النفس.|Nu is er alleen deze adem.|Teraz jest tylko ten oddech.|Зараз є лише цей подих.|いま、この息だけがある。|اکنون فقط همین نفس هست.|此刻只有这一口气。'),
    R('Kendi adımı, bu odayı biliyorum.|I know my name, and this room.|Öz adımı, bu otağı bilirəm.|Я знаю своё имя и эту комнату.|Sé mi nombre y esta habitación.|Je connais mon nom et cette pièce.|Ich kenne meinen Namen und diesen Raum.|Conosco il mio nome e questa stanza.|Sei o meu nome e este quarto.|أعرف اسمي وهذه الغرفة.|Ik ken mijn naam en deze kamer.|Znam swoje imię i ten pokój.|Знаю своє ім’я і цю кімнату.|自分の名と、この部屋を知っている。|نام خود و این اتاق را می‌دانم.|我知道自己的名字，也知道这间房。'),
  ]
  return rows.map((row) => pickLocale(row, locale, row.en))
}

export function tapSentences(locale: LocaleId): string[] {
  const rows = [
    R('Dalga geçti, ben buradayım.|The wave passed; I am here.|Dalğa keçdi, mən buradayam.|Волна прошла; я здесь.|La ola pasó; estoy aquí.|La vague est passée ; je suis ici.|Die Welle ist vorbei; ich bin hier.|L’onda è passata; sono qui.|A onda passou; estou aqui.|مرّ الموج؛ أنا هنا.|De golf is voorbij; ik ben hier.|Fala minęła; jestem tutaj.|Хвиля минула; я тут.|波は過ぎた。私はここにいる。|موج گذشت؛ من اینجام.|浪过了；我在这里。'),
    R('Bedenim şimdi yavaşlıyor.|My body is slowing now.|Bədənim indi yavaşlayır.|Тело сейчас замедляется.|Mi cuerpo ahora se ralentiza.|Mon corps ralentit maintenant.|Mein Körper wird jetzt langsamer.|Il mio corpo ora rallenta.|O meu corpo agora abranda.|جسدي يتباطأ الآن.|Mijn lijf vertraagt nu.|Moje ciało teraz zwalnia.|Тіло зараз сповільнюється.|体が、いま遅くなっている。|بدنم حالا آرام می‌شود.|身体正在放慢。'),
    R('Bu oda, bu gece, bu nefes.|This room, this night, this breath.|Bu otaq, bu gecə, bu nəfəs.|Эта комната, эта ночь, это дыхание.|Esta habitación, esta noche, este aliento.|Cette pièce, cette nuit, ce souffle.|Dieser Raum, diese Nacht, dieser Atem.|Questa stanza, questa notte, questo respiro.|Este quarto, esta noite, este fôlego.|هذه الغرفة، هذه الليلة، هذا النفس.|Deze kamer, deze nacht, deze adem.|Ten pokój, ta noc, ten oddech.|Ця кімната, ця ніч, цей подих.|この部屋、この夜、この息。|این اتاق، این شب، این نفس.|这间房，这一夜，这一口气。'),
    R('Güvenliyim ve duruyorum.|I am safe, and I am staying.|Təhlükəsizəm və dururam.|Я в безопасности и остаюсь.|Estoy a salvo y me quedo.|Je suis en sécurité et je reste.|Ich bin sicher und ich bleibe.|Sono al sicuro e resto.|Estou em segurança e fico.|أنا في أمان وأبقى.|Ik ben veilig en ik blijf.|Jestem bezpieczny i zostaję.|Я в безпеці і лишаюся.|安全だ。そして、ここにいる。|امن هستم و می‌مانم.|我安全，我留着。'),
  ]
  return rows.map((row) => pickLocale(row, locale, row.en))
}
