import { R, type LocaleId } from './locales'
import { EXTRA } from './extra-strings'
import { ONBOARD_I18N } from './onboard-i18n'

export type StringKey = keyof typeof RAW

const CORE = {
  nav_home: R('Bugün|Today|Bu gün|Сегодня|Hoy|Aujourd’hui|Heute|Oggi|Hoje|اليوم|Vandaag|Dziś|Сьогодні|今日|امروز|今天'),
  nav_discover: R('Keşfet|Explore|Kəşf et|Обзор|Explorar|Explorer|Entdecken|Esplora|Explorar|استكشف|Ontdek|Odkryj|Огляд|探す|کاوش|探索'),
  nav_sleep: R('Uyku|Sleep|Yuxu|Сон|Sueño|Sommeil|Schlaf|Sonno|Sono|نوم|Slaap|Sen|Сон|睡眠|خواب|睡眠'),
  nav_sounds: R('Sesler|Sounds|Səslər|Звуки|Sonidos|Sons|Klänge|Suoni|Sons|أصوات|Geluiden|Dźwięki|Звуки|サウンド|صداها|声音'),
  nav_more: R('Daha|More|Daha|Ещё|Más|Plus|Mehr|Altro|Mais|المزيد|Meer|Więcej|Ще|もっと|بیشتر|更多'),
  nav_me: R('Profil|Profile|Profil|Профиль|Perfil|Profil|Profil|Profilo|Perfil|حساب|Profiel|Profil|Профіль|プロフィール|نمایه|我的'),

  home_kicker: R('Steady · 6 dil|Steady · 6 languages|Steady · 6 idiomas|Steady · 6 langues|Steady · 6 Sprachen|Steady · 6 lingue'),
  home_headline: R('Buradasın.|You’re here.|Buradasan.|Ты здесь.|Estás aquí.|Tu es là.|Du bist hier.|Sei qui.|Você está aqui.|أنت هنا.|Je bent hier.|Jesteś tutaj.|Ти тут.|ここにいる。|اینجایی.|你在这里。'),
  home_calm: R('Yavaş. Bugün bir şey yeter.|Slow. One thing is enough today.|Yavaş. Bu gün bir şey bəsdir.|Медленно. Сегодня хватит одного.|Despacio. Hoy basta una cosa.|Lentement. Une chose suffit aujourd’hui.|Langsam. Heute reicht eines.|Piano. Oggi basta una cosa.|Devagar. Hoje uma coisa chega.|على مهل. شيء واحد يكفي اليوم.|Traag. Vandaag is één ding genoeg.|Powoli. Dziś wystarczy jedno.|Повільно. Сьогодні досить одного.|ゆっくり。今日は一つで足りる。|آرام. امروز یک چیز بس است.|慢慢来。今天一件就够。'),
  disc_calm: R('Bugün yalnızca birini seç.|Choose only one, today.|Bu gün yalnız birini seç.|Сегодня выбери только одно.|Hoy elige solo uno.|Aujourd’hui, n’en choisis qu’un.|Heute nur eines wählen.|Oggi scegline solo uno.|Hoje escolhe só um.|اليوم اختر واحدًا فقط.|Kies er vandaag maar één.|Dziś wybierz tylko jedno.|Сьогодні обери лише одне.|今日は一つだけ選ぶ。|امروز فقط یکی را انتخاب کن.|今天只选一个。'),
  see_all: R('Tümünü göster|Show all|Hamısını göstər|Показать все|Ver todo|Tout voir|Alle zeigen|Mostra tutto|Ver tudo|عرض الكل|Alles tonen|Pokaż wszystko|Показати все|すべて見る|همه را ببین|显示全部'),
  see_less: R('Daha az|Show less|Daha az|Меньше|Ver menos|Voir moins|Weniger|Mostra meno|Ver menos|أقل|Minder|Mniej|Менше|少なく|کمتر|收起'),
  home_sub: R('Panik tek kapı değil. Uyku, nefes, sözler ve hikâyeler burada.|Panic is only one door. Sleep, breath, lines and stories are here.|Panik tək qapı deyil. Yuxu, nəfəs, sözlər və hekayələr buradadır.|Паника — не единственная дверь. Сон, дыхание, слова и истории здесь.|El pánico no es la única puerta. Sueño, respiración, palabras e historias.|La panique n’est pas la seule porte. Sommeil, souffle, mots et récits.|Panik ist nicht die einzige Tür. Schlaf, Atem, Worte und Geschichten.|Il panico non è l’unica porta. Sonno, respiro, parole e storie.|O pânico não é a única porta. Sono, respiração, palavras e histórias.|الهلع ليس الباب الوحيد. نوم وتنفس وكلمات وقصص.|Paniek is niet de enige deur. Slaap, adem, woorden en verhalen.|Panik to nie jedyne drzwi. Sen, oddech, słowa i historie.|Паніка — не єдині двері. Сон, подих, слова й історії.|パニックだけが扉ではない。睡眠、呼吸、言葉、物語.|پانیک تنها در نیست. خواب، نفس، واژه‌ها و داستان.|恐慌不是唯一的门。睡眠、呼吸、字句与故事。'),
  home_sos: R('Kriz anı|Crisis moment|Kriz anı|Момент кризиса|Momento de crisis|Moment de crise|Krisenmoment|Momento di crisi|Momento de crise|لحظة الأزمة|Crisismoment|Moment kryzysu|Момент кризи|クライシス|لحظه بحران|危机时刻'),
  home_sos_sub: R('174 Hz · kahverengi gürültü · sesli nefes · kilitlenmez|174 Hz · brown noise · voiced breath · never locked|174 Hz · qəhvəyi küy · səsli nəfəs · kilidlənmir|174 Гц · коричневый шум · голос дыхания · не блокируется|174 Hz · ruido marrón · respiración hablada · nunca se bloquea|174 Hz · bruit brun · souffle parlé · jamais verrouillé|174 Hz · Braunrauschen · gesprochener Atem · nie gesperrt|174 Hz · rumore bruno · respiro parlato · mai bloccato|174 Hz · ruído marrom · respiração falada · nunca trava|174 هرتز · ضوضاء بنية · تنفس صوتي · لا يُقفل|174 Hz · bruine ruis · gesproken adem · nooit vergrendeld|174 Hz · szum brązowy · głos oddechu · nigdy nie zablokowany|174 Гц · коричневий шум · голосовий подих · не блокується|174Hz · ブラウンノイズ · 音声呼吸 · ロックされない|۱۷۴ هرتز · نویز قهوه‌ای · نفس گفتاری · قفل نمی‌شود|174 Hz · 棕噪声 · 语音呼吸 · 永不锁定'),
  home_now: R('Şimdi|Now|İndi|Сейчас|Ahora|Maintenant|Jetzt|Ora|Agora|الآن|Nu|Teraz|Зараз|いま|اکنون|此刻'),
  home_trial: R('Deneme|Trial|Sınaq|Проба|Prueba|Essai|Test|Prova|Teste|تجربة|Proef|Próba|Проба|体験|آزمایش|试用'),
  home_clarity: R('Netlik|Clarity|Aydınlıq|Ясность|Claridad|Clarté|Klarheit|Chiarezza|Clareza|صفاء|Helderheid|Jasność|Ясність|明晰|شفافیت|清明'),
  home_free: R('ücretsiz|free|pulsuz|бесплатно|gratis|gratuit|kostenlos|gratis|grátis|مجاني|gratis|za darmo|безкоштовно|無料|رایگان|免费'),
  home_night: R('Gece|Night|Gecə|Ночь|Noche|Nuit|Nacht|Notte|Noite|ليل|Nacht|Noc|Ніч|夜|شب|夜'),
  home_story_free: R('Ücretsiz hikâye · sesli okuma|Free story · spoken aloud|Pulsuz hekayə · səsli oxu|Бесплатная история · вслух|Relato gratis · lectura en voz|Récit gratuit · lu à voix haute|Gratisgeschichte · vorgelesen|Racconto libero · letto ad alta voce|História grátis · leitura em voz|قصة مجانية · قراءة صوتية|Gratis verhaal · voorgelezen|Darmowa opowieść · czytana|Безкоштовна історія · вголос|無料の物語 · 読み上げ|داستان رایگان · خوانش صوتی|免费故事 · 朗读'),
  home_quote: R('Günün cümlesi|Line of the day|Günün cümləsi|Фраза дня|Frase del día|Phrase du jour|Satz des Tages|Frase del giorno|Frase do dia|جملة اليوم|Zin van de dag|Zdanie dnia|Фраза дня|今日の一文|جملهٔ امروز|今日一句'),
  home_lang: R('Dil|Language|Dil|Язык|Idioma|Langue|Sprache|Lingua|Idioma|اللغة|Taal|Język|Мова|言語|زبان|语言'),

  disc_title: R('Keşfet|Discover|Kəşf et|Обзор|Descubrir|Découvrir|Entdecken|Scopri|Descobrir|اكتشف|Ontdekken|Odkrywaj|Огляд|探す|کشف کن|发现'),
  disc_sub: R('Çok yol yok. Seçilmiş içerikler. Teşhis yok.|Not a thousand paths. Chosen pieces. No diagnosis.|Çox yol yoxdur. Seçilmiş məzmun. Diaqnoz yoxdur.|Не тысяча путей. Выбранное. Без диагноза.|No mil caminos. Piezas elegidas. Sin diagnóstico.|Pas mille chemins. Pièces choisies. Pas de diagnostic.|Keine tausend Wege. Ausgewählte Stücke. Keine Diagnose.|Non mille vie. Pezzi scelti. Nessuna diagnosi.|Não mil caminhos. Peças escolhidas. Sem diagnóstico.|ليست ألف طريق. قطع مختارة. بلا تشخيص.|Geen duizend paden. Gekozen stukken. Geen diagnose.|Nie tysiąc dróg. Wybrane rzeczy. Bez diagnozy.|Не тисяча шляхів. Обране. Без діагнозу.|千の道ではない。選ばれたもの。診断なし。|هزار راه نیست. گزیده. بدون تشخیص.|不是一千条路。精选内容。无诊断。'),
  cat_meditate: R('Meditasyonlar|Meditations|Meditasiyalar|Медитации|Meditaciones|Méditations|Meditationen|Meditazioni|Meditações|تأملات|Meditaties|Medytacje|Медитації|瞑想|مدیتیشن|冥想'),
  cat_stories: R('Uyku hikâyeleri|Sleep stories|Yuxu hekayələri|Истории для сна|Relatos de sueño|Récits du sommeil|Schlafgeschichten|Racconti del sonno|Histórias de sono|قصص النوم|Slaapverhalen|Opowieści senne|Історії сну|睡眠物語|داستان خواب|助眠故事'),
  cat_breath: R('Nefes|Breath|Nəfəs|Дыхание|Respiración|Souffle|Atem|Respiro|Respiração|تنفس|Adem|Oddech|Подих|呼吸|نفس|呼吸'),
  cat_write: R('Yazılar|Writings|Yazılar|Записи|Escritos|Écrits|Texte|Scritture|Escritos|كتابات|Teksten|Zapiski|Записи|書きもの|نوشته‌ها|书写'),
  cat_nature: R('Doğa sesleri|Nature sounds|Təbiət səsləri|Звуки природы|Sonidos de la naturaleza|Sons de nature|Naturklänge|Suoni della natura|Sons da natureza|أصوات الطبيعة|Natuurgeluiden|Dźwięki natury|Звуки природи|自然音|صدای طبیعت|自然声'),
  cat_quotes: R('Sözler|Lines|Sözlər|Слова|Palabras|Paroles|Worte|Parole|Palavras|كلمات|Woorden|Słowa|Слова|言葉|کلمه‌ها|字句'),
  cat_cope: R('Kapılar|Doors|Qapılar|Двери|Puertas|Portes|Türen|Porte|Portas|أبواب|Deuren|Drzwi|Двері|扉|درها|门'),
  cat_tones: R('Tonlar|Tones|Tonlar|Тона|Tonos|Tons|Töne|Toni|Tons|نغمات|Tonen|Tony|Тони|トーン|تون‌ها|音调'),
  cat_more: R('Ve daha fazlası|And more|Və daha çoxu|И ещё|Y más|Et plus|Und mehr|E altro|E mais|والمزيد|En meer|I więcej|І ще|その他|و بیشتر|以及更多'),
  cat_sos: R('SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS|SOS'),
  cat_clarity: R('Günlük netlik|Daily clarity|Gündəlik aydınlıq|Ежедневная ясность|Claridad diaria|Clarté du jour|Tägliche Klarheit|Chiarezza quotidiana|Clareza diária|صفاء يومي|Dagelijkse helderheid|Codzienna jasność|Щоденна ясність|日々の明晰|شفافیت روزانه|每日清明'),

  quotes_title: R('Sözler|Lines|Sözlər|Слова|Palabras|Paroles|Worte|Parole|Palavras|كلمات|Woorden|Słowa|Слова|言葉|کلمه‌ها|字句'),
  quotes_sub: R('Eski metinlerin kendi anlatımımız. Modern kitap kopyası yok.|Our own wording of old public lines. No modern book text.|Köhnə mətnləri öz sözümüzlə yazırıq. Müasir kitab yoxdur.|Старые строки своими словами. Без современных книг.|Textos antiguos con nuestras palabras. Sin libros modernos.|Anciennes lignes en nos mots. Pas de livre moderne.|Alte Zeilen in eigenen Worten. Keine modernen Bücher.|Righe antiche con parole nostre. Niente libri moderni.|Textos antigos nas nossas palavras. Sem livros modernos.|صياغتنا لنصوص قديمة. لا كتب حديثة.|Oude regels in eigen woorden. Geen moderne boeken.|Stare zdania własnymi słowami. Bez współczesnych książek.|Старі рядки своїми словами. Без сучасних книжок.|古い言葉を私たちの文で。現代の書籍なし。|متن‌های کهن با واژه‌های خودمان. بدون کتاب مدرن.|用我们自己的话写旧文。无现代书籍。'),
  quotes_pd: R('Kamu malı|Public domain|İctimai domen|Общественное достояние|Dominio público|Domaine public|Gemeinfrei|Pubblico dominio|Domínio público|ملك عام|Publiek domein|Domena publiczna|Суспільне надбання|パブリックドメイン|مالکیت عمومی|公有领域'),
  quotes_essence: R('Yaklaşım özü · alıntı değil|Approach essence · not a quotation|Yanaşma özü · sitat deyil|Суть подхода · не цитата|Esencia de enfoque · no es cita|Essence d’approche · pas une citation|Ansatzkern · kein Zitat|Essenza di approccio · non una citazione|Essência de abordagem · não é citação|جوهر منهج · ليست اقتباسًا|Aanpak-kern · geen citaat|Esencja podejścia · nie cytat|Суть підходу · не цитата|アプローチの核 · 引用ではない|جوهر رویکرد · نقل‌قول نیست|方法精要 · 非引文'),
  quotes_tap: R('Özü aç|Open the essence|Özü aç|Открыть суть|Abrir la esencia|Ouvrir l’essence|Kern öffnen|Apri l’essenza|Abrir a essência|افتح الجوهر|Kern openen|Otwórz esencję|Відкрити суть|核を開く|جوهر را باز کن|打开精句'),
  quotes_listen: R('Sesli oku|Read aloud|Səsli oxu|Прочитать вслух|Leer en voz alta|Lire à voix haute|Vorlesen|Leggi ad alta voce|Ler em voz alta|اقرأ بصوت|Voorlezen|Czytaj głośno|Читати вголос|読み上げ|با صدا بخوان|朗读'),
  quotes_close: R('Kapat|Close|Bağla|Закрыть|Cerrar|Fermer|Schließen|Chiudi|Fechar|إغلاق|Sluiten|Zamknij|Закрити|閉じる|بستن|关闭'),

  more_title: R('Daha fazla|More|Daha çox|Ещё|Más|Plus|Mehr|Altro|Mais|المزيد|Meer|Więcej|Ще|もっと|بیشتر|更多'),
  more_sub: R('Küçük araçlar. Tedavi iddiası yok.|Small tools. No treatment claim.|Kiçik alətlər. Müalicə iddiası yoxdur.|Малые инструменты. Без претензии на лечение.|Herramientas pequeñas. Sin pretensión de tratamiento.|Petits outils. Sans prétention de soin.|Kleine Werkzeuge. Kein Behandlungsanspruch.|Piccoli strumenti. Nessuna pretesa di cura.|Pequenas ferramentas. Sem pretensão de tratamento.|أدوات صغيرة. بلا ادعاء علاج.|Kleine tools. Geen behandelclaim.|Małe narzędzia. Bez roszczenia leczenia.|Малі знаряддя. Без заяви про лікування.|小さな道具。治療の主張なし。|ابزارهای کوچک. بدون ادعای درمان.|小工具。无治疗宣称。'),
  more_ground: R('5-4-3-2-1 yer|5-4-3-2-1 ground|5-4-3-2-1 yer|5-4-3-2-1 земля|5-4-3-2-1 suelo|5-4-3-2-1 ancrage|5-4-3-2-1 Boden|5-4-3-2-1 terra|5-4-3-2-1 chão|5-4-3-2-1 أرض|5-4-3-2-1 grond|5-4-3-2-1 grunt|5-4-3-2-1 земля|5-4-3-2-1 接地|۵-۴-۳-۲-۱ زمین|5-4-3-2-1 落地'),
  more_gratitude: R('Üç küçük şükran|Three small thanks|Üç kiçik minnətdarlıq|Три малые благодарности|Tres gracias pequeñas|Trois petites grâces|Drei kleine Danke|Tre piccoli ringraziamenti|Três pequenos agradecimentos|ثلاث شكر صغيرة|Drie kleine dank|Trzy małe wdzięczności|Три малі подяки|小さな感謝が三つ|سه سپاس کوچک|三件小感恩'),
  more_bodyscan: R('Beden taraması|Body scan|Bədən tarama|Сканирование тела|Barrido corporal|Balayage du corps|Körperreise|Scansione del corpo|Varredura do corpo|مسح الجسد|Lichaamsscan|Skan ciała|Скан тіла|ボディスキャン|اسکن بدن|身体扫描'),
  more_seed: R('Gece tohumu|Night seed|Gecə toxumu|Ночное семя|Semilla nocturna|Graine de nuit|Nachtkern|Seme notturno|Semente da noite|بذرة الليل|Nachtzaad|Nocne ziarno|Нічне зерно|夜の種|دانه شب|夜种'),
  more_worry: R('Kaygı penceresi|Worry window|Narahatlıq pəncərəsi|Окно тревоги|Ventana de preocupación|Fenêtre d’inquiétude|Sorgenfenster|Finestra di preoccupazione|Janela da preocupação|نافذة القلق|Zorgenvenster|Okno zmartwień|Вікно тривоги|心配の窓|پنجره نگرانی|忧虑窗'),
  more_values: R('Değer pusulası|Values compass|Dəyər kompası|Компас ценностей|Brújula de valores|Boussole des valeurs|Wertekompass|Bussola dei valori|Bússola de valores|بوصلة القيم|Waardenkompas|Kompas wartości|Компас цінностей|価値の羅針盤|قطب‌نمای ارزش|价值罗盘'),
  more_kind: R('Nazik arkadaş|Kind friend|Zərif dost|Добрый друг|Amigo amable|Ami bienveillant|Guter Freund|Amico gentile|Amigo gentil|صديق لطيف|Lieve vriend|Życzliwy przyjaciel|Добрий друг|やさしい友|دوست مهربان|友善的朋友'),
  more_walk: R('On adım|Ten steps|On addım|Десять шагов|Diez pasos|Dix pas|Zehn Schritte|Dieci passi|Dez passos|عشر خطوات|Tien stappen|Dziesięć kroków|Десять кроків|十歩|ده گام|十步'),
  more_tension: R('Gerilim bırakışı|Tension drop|Gərginlik buraxılışı|Сброс напряжения|Soltar tensión|Lâcher la tension|Spannung abgeben|Rilasciare la tensione|Soltar tensão|إفلات التوتر|Spanning loslaten|Zrzut napięcia|Скид напруги|緊張を落とす|رها کردن تنش|放下紧绷'),
  more_morning: R('Sabah ışığı|Morning light|Səhər işığı|Утренний свет|Luz de mañana|Lumière du matin|Morgenlicht|Luce del mattino|Luz da manhã|ضوء الصباح|Ochtendlicht|Światło poranka|Ранкове світло|朝の光|نور صبح|晨光'),

  me_title: R('Profil|Profile|Profil|Профиль|Perfil|Profil|Profil|Profilo|Perfil|حساب|Profiel|Profil|Профіль|プロフィール|نمایه|我的'),
  me_sub: R('Dil telefon Ayarları’ndan gelir.|Language comes from phone Settings.|Dil telefon Ayarlarından gəlir.|Язык берётся из настроек телефона.|El idioma sale de Ajustes.|La langue vient des Réglages.|Die Sprache kommt aus den Einstellungen.|La lingua arriva da Impostazioni.|O idioma vem dos Ajustes.|اللغة تأتي من إعدادات الهاتف.|De taal komt uit de telefooninstellingen.|Język pochodzi z Ustawień.|Мова з налаштувань телефону.|言語は設定から。|زبان از تنظیمات گوشی است.|语言来自手机设置。'),
  me_tier: R('Durum|Status|Vəziyyət|Статус|Estado|Statut|Status|Stato|Estado|الحالة|Status|Status|Статус|状態|وضعیت|状态'),
  me_settings: R('Ayarlar|Settings|Ayarlar|Настройки|Ajustes|Réglages|Einstellungen|Impostazioni|Definições|إعدادات|Instellingen|Ustawienia|Налаштування|設定|تنظیمات|设置'),
  me_pro: R('Pro (cihaz demosu)|Pro (device demo)|Pro (cihaz demosu)|Pro (демо устройства)|Pro (demo del dispositivo)|Pro (démo appareil)|Pro (Geräte-Demo)|Pro (demo dispositivo)|Pro (demo do aparelho)|برو (عرض الجهاز)|Pro (apparaatdemo)|Pro (demo urządzenia)|Pro (демо пристрою)|Pro（端末デモ）|پرو (دموی دستگاه)|Pro（设备演示）'),
  me_free: R('Ücretsiz|Free|Pulsuz|Бесплатно|Gratis|Gratuit|Kostenlos|Gratis|Grátis|مجاني|Gratis|Darmowy|Безкоштовно|無料|رایگان|免费'),
  me_pin: R('Dört haneli kilit|Four-digit lock|Dörd rəqəmli kilid|Четырёхзначный замок|Candado de cuatro dígitos|Verrou à quatre chiffres|Vierstellige Sperre|Blocco a quattro cifre|Bloqueio de quatro dígitos|قفل من أربع أرقام|Viercijferig slot|Zamek czterocyfrowy|Чотиризначний замок|4桁ロック|قفل چهاررقمی|四位锁'),
  me_pin_body: R('SOS kilit ekranından da açılır. PIN yalnızca bu tarayıcıda özetlenir.|SOS still opens from the lock screen. The PIN is hashed in this browser only.|SOS kilid ekranından da açılır.|SOS открывается и с экрана блокировки.|SOS también abre desde la pantalla de bloqueo.|SOS s’ouvre encore depuis le verrou.|SOS öffnet auch vom Sperrbildschirm.|SOS si apre anche dalla schermata di blocco.|SOS ainda abre do bloqueio.|SOS يفتح من شاشة القفل.|SOS opent ook vanaf het slot.|SOS otwiera się też z blokady.|SOS відкривається і з екрана блокування.|SOSはロック画面からも開く。|SOS از صفحه قفل هم باز می‌شود.|SOS 仍可从锁屏打开。'),
  me_lock_now: R('Şimdi kilitle|Lock now|İndi kilidlə|Заблокировать|Bloquear ahora|Verrouiller|Jetzt sperren|Blocca ora|Bloquear agora|اقفل الآن|Nu vergrendelen|Zablokuj teraz|Заблокувати|今すぐロック|همین حالا قفل کن|立即锁定'),
  me_lock_off: R('Kilit kaldır|Remove lock|Kilidi götür|Снять замок|Quitar candado|Retirer le verrou|Sperre entfernen|Rimuovi blocco|Remover bloqueio|إزالة القفل|Slot verwijderen|Usuń zamek|Зняти замок|ロック解除|برداشتن قفل|移除锁'),
  me_lock_set: R('Kilit kur|Set lock|Kilid qur|Установить замок|Crear candado|Créer un verrou|Sperre setzen|Imposta blocco|Definir bloqueio|تعيين القفل|Slot instellen|Ustaw zamek|Встановити замок|ロック設定|تنظیم قفل|设置锁'),
  me_pin_new: R('Yeni PIN|New PIN|Yeni PIN|Новый PIN|Nuevo PIN|Nouveau PIN|Neue PIN|Nuovo PIN|Novo PIN|رمز جديد|Nieuwe PIN|Nowy PIN|Новий PIN|新しいPIN|پین تازه|新 PIN'),
  me_pin_again: R('Yeniden gir|Enter again|Yenidən yaz|Повторите|Otra vez|Encore|Nochmal|Di nuovo|De novo|مرة أخرى|Opnieuw|Ponownie|Ще раз|もう一度|دوباره|再输入'),
  me_pin_match: R('Onay için aynı dört hane|Same four digits to confirm|Təsdiq üçün eyni dörd rəqəm|Те же четыре цифры|Los mismos cuatro dígitos|Les quatre mêmes chiffres|Dieselben vier Ziffern|Le stesse quattro cifre|Os mesmos quatro dígitos|نفس الأرقام الأربعة|Dezelfde vier cijfers|Te same cztery cyfry|Ті самі чотири цифри|確認のため同じ4桁|همان چهار رقم|相同四位'),
  me_pin_fail: R('Eşleşmedi. Baştan.|No match. Start over.|Uyğun gəlmədi. Başdan.|Не совпало. Сначала.|No coincide. De nuevo.|Échec. Recommencez.|Passt nicht. Von vorn.|Non coincide. Riparti.|Não coincidiu. De novo.|غير متطابق. من جديد.|Komt niet overeen. Opnieuw.|Nie zgadza się. Od nowa.|Не збіглося. З початку.|不一致。やり直してください。|همخوان نیست. از نو.|不匹配。重来。'),
  me_history: R('Geçti geçmişi|Passed history|Keçdi tarixçəsi|История «прошло»|Historial de Pasó|Historique Passé|Verlauf Vorbei|Cronologia Passato|Histórico Passou|سجل مرّ|Geschiedenis Voorbij|Historia Minęło|Історія Минуло|過ぎた履歴|تاریخچه گذشت|已过记录'),
  me_history_locked: R('Kayıtlar tutulur, liste Pro’dadır.|Records are kept; the list is Pro.|Qeydlər saxlanır, siyahı Pro-dadır.|Записи хранятся; список — Pro.|Se guardan; la lista es Pro.|Enregistrés ; la liste est Pro.|Gespeichert; die Liste ist Pro.|Salvati; l’elenco è Pro.|Guardados; a lista é Pro.|تُحفظ السجلات؛ القائمة برو.|Bijgehouden; de lijst is Pro.|Zapisane; lista jest Pro.|Збережено; список — Pro.|記録は残る。一覧はPro。|ثبت می‌شود؛ فهرست پرو است.|有记录；列表为 Pro。'),
  me_history_empty: R('Henüz Geçti yok.|No Passed yet.|Hələ Keçdi yoxdur.|Пока нет «прошло».|Aún no hay Pasó.|Pas encore de Passé.|Noch kein Vorbei.|Nessun Passato ancora.|Ainda sem Passou.|لا يوجد «مرّ» بعد.|Nog geen Voorbij.|Brak Minęło.|Ще немає Минуло.|まだ「過ぎた」はない。|هنوز «گذشت» نیست.|尚无「已过」。'),
  me_approach: R('Rahat beden. Kısa şimdiki zaman cümle. Sahne. Gece tohumu. Bırakış. Şükran. Murphy alıntısı yok.|Relaxed body. Short present-tense line. Scene. Night seed. Release. Thanks. No Murphy quotation.|Rahat bədən. Qısa indiki zaman. Səhnə. Gecə toxumu. Buraxılış. Minnətdarlıq. Murphy yoxdur.|Расслабленное тело. Короткая фраза в настоящем. Сцена. Ночное семя. Отпускание. Благодарность. Без Мёрфи.|Cuerpo relajado. Frase breve en presente. Escena. Semilla nocturna. Soltar. Gracias. Sin Murphy.|Corps relâché. Phrase courte au présent. Scène. Graine de nuit. Lâcher. Gratitude. Pas de Murphy.|Lockerer Körper. Kurzer Präsenssatz. Szene. Nachtkern. Loslassen. Dank. Kein Murphy.|Corpo morbido. Frase breve al presente. Scena. Seme notturno. Rilascio. Grazia. Niente Murphy.|Corpo frouxo. Frase curta no presente. Cena. Semente da noite. Soltar. Graça. Sem Murphy.|جسد مرتخٍ. جملة قصيرة في المضارع. مشهد. بذرة الليل. إفلات. شكر. لا ميرفي.|Ontspannen lijf. Korte presenszin. Scène. Nachtzaad. Loslaten. Dank. Geen Murphy.|Rozluźnione ciało. Krótka teraźniejszość. Scena. Nocne ziarno. Puszczenie. Wdzięczność. Bez Murphy’ego.|Розслаблене тіло. Коротка теперішня фраза. Сцена. Нічне зерно. Відпускання. Подяка. Без Мерфі.|ゆるめた体。短い現在形。場面。夜の種。手放し。感謝。マーフィー引用なし。|بدن رها. جمله کوتاه در حال. صحنه. دانه شب. رها کردن. سپاس. بدون مورفی.|放松的身体。短的现在句。场景。夜种。放下。感恩。无墨菲引文。'),
  me_demo_off: R('Demo Pro’yu kapat|Turn off demo Pro|Demo Pro-nu bağla|Выключить демо Pro|Cerrar demo Pro|Fermer la démo Pro|Demo-Pro aus|Chiudi demo Pro|Desligar demo Pro|إيقاف عرض برو|Demo-Pro uit|Wyłącz demo Pro|Вимкнути демо Pro|デモProをオフ|خاموش کردن دموی پرو|关闭演示 Pro'),
  me_vitrine: R('Pro’yu aç|Open Pro|Pro-nu aç|Открыть Pro|Abrir Pro|Ouvrir Pro|Pro öffnen|Apri Pro|Abrir Pro|افتح برو|Pro openen|Otwórz Pro|Відкрити Pro|Proを開く|پرو را باز کن|打开 Pro'),

  legal_full: R('Steady tıbbi teşhis veya tedavi sunmaz. Başa çıkma araçlarıdır. Krizde yerel acil hat.|Steady does not diagnose or treat. These are coping tools. In crisis call local emergency services.|Steady tibbi diaqnoz və ya müalicə vermir. Öhdəlik alətləridir. Krizdə yerli təcili yardım.|Steady не ставит диагноз и не лечит. Это инструменты совладания. В кризисе — местная служба.|Steady no diagnostica ni trata. Son herramientas de afrontamiento. En crisis, emergencia local.|Steady ne diagnostique ni ne soigne. Outils d’appui. En crise, les secours locaux.|Steady diagnostiziert und behandelt nicht. Bewältigungswerkzeuge. Im Ernstfall örtliche Notnummer.|Steady non diagnostica né cura. Strumenti di fronteggiamento. In crisi, i soccorsi locali.|Steady não diagnostica nem trata. Ferramentas de enfrentamento. Em crise, emergência local.|Steady لا يشخص ولا يعالج. أدوات تعامل. في الأزمة اتصل بالطوارئ المحلية.|Steady diagnosticeert of behandelt niet. Omgaan-tools. Bij crisis lokale hulpdiensten.|Steady nie stawia diagnozy ani nie leczy. Narzędzia radzenia sobie. W kryzysie lokalne pogotowie.|Steady не ставить діагноз і не лікує. Знаряддя опанування. У кризі — місцева допомога.|Steadyは診断も治療もしない。対処の道具。危機では地元の救急へ。|Steady تشخیص یا درمان نمی‌کند. ابزار کنار آمدن است. در بحران با اورژانس محلی تماس بگیرید.|Steady 不做诊断或治疗。这些是应对工具。危急时拨打当地急救。'),
  legal_short: R('Tıbbi tedavi değildir.|Not medical treatment.|Tibbi müalicə deyil.|Это не лечение.|No es tratamiento médico.|Ce n’est pas un soin médical.|Keine medizinische Behandlung.|Non è una cura medica.|Não é tratamento médico.|ليس علاجًا طبيًا.|Geen medische behandeling.|To nie leczenie medyczne.|Це не медичне лікування.|医療行為ではない。|درمان پزشکی نیست.|非医疗治疗。'),
  crisis: R('Krizde acil hat|In crisis, emergency line|Krizdə təcili xətt|В кризисе — экстренная линия|En crisis, línea de emergencia|En crise, ligne d’urgence|Im Ernstfall Notruf|In crisi, linea di emergenza|Em crise, linha de emergência|في الأزمة، خط الطوارئ|Bij crisis, hulplijn|W kryzysie numer alarmowy|У кризі — екстрена лінія|危機では救急|در بحران، خط اضطراری|危急时急救电话'),
  not_medical: R('Tıbbi teşhis veya tedavi değil.|Not a medical diagnosis or treatment.|Tibbi diaqnoz və ya müalicə deyil.|Не диагноз и не лечение.|No es diagnóstico ni tratamiento.|Ni diagnostic ni traitement.|Keine Diagnose, keine Behandlung.|Né diagnosi né cura.|Nem diagnóstico nem tratamento.|ليس تشخيصًا ولا علاجًا.|Geen diagnose of behandeling.|To nie diagnoza ani leczenie.|Не діагноз і не лікування.|診断でも治療でもない。|نه تشخیص است نه درمان.|既非诊断也非治疗。'),

  sos_ready: R('Hazır|Ready|Hazır|Готово|Listo|Prêt|Bereit|Pronto|Pronto|جاهز|Klaar|Gotowe|Готово|準備|آماده|就绪'),
  sos_title: R('Dur.|Pause.|Dayan.|Стоп.|Pausa.|Pause.|Halt.|Pausa.|Pausa.|قف.|Pauze.|Stop.|Стоп.|止まる。|بایست.|停。'),
  sos_sub: R('Önce 3 nesne. Renk. Dokun. Sonra nefes.|First 3 objects. Color. Touch. Then breath.|Primero 3 objetos. Color. Tocar. Luego respirar.|D’abord 3 objets. Couleur. Toucher. Puis le souffle.|Zuerst 3 Dinge. Farbe. Berühren. Dann atmen.|Prima 3 oggetti. Colore. Toccare. Poi il respiro.'),
  sos_in: R('Nefes al|Breathe in|Nəfəs al|Вдох|Inhala|Inspire|Einatmen|Inspira|Inspira|شهيق|Inademen|Wdech|Вдих|吸う|دم بگیر|吸气'),
  sos_hold: R('Tut|Hold|Tut|Пауза|Sostén|Tiens|Halten|Tieni|Segura|احبس|Vasthouden|Trzymaj|Тримай|止める|نگه‌دار|停'),
  sos_out: R('Ver|Breathe out|Ver|Выдох|Suelta|Expire|Ausatmen|Espira|Solta|زفير|Uitademen|Wydech|Видих|吐く|بازدم|呼气'),
  sos_line: R('Cümle|Line|Cümlə|Фраза|Frase|Phrase|Satz|Frase|Frase|جملة|Zin|Zdanie|Речення|一文|جمله|一句'),
  sos_passed: R('Geçti|It passed|Keçdi|Прошло|Pasó|C’est passé|Vorbei|È passato|Passou|مرّ|Voorbij|Minęło|Минуло|過ぎた|گذشت|已过'),
  sos_tap: R('Bu cümleye on kez dokun|Tap this line ten times|Bu cümləyə on dəfə toxun|Нажми эту фразу десять раз|Toca esta frase diez veces|Touche cette phrase dix fois|Tippe diesen Satz zehnmal|Tocca questa frase dieci volte|Toque esta frase dez vezes|المس هذا السطر عشر مرات|Tik tien keer op deze zin|Dotknij tego zdania dziesięć razy|Натисни цей рядок десять разів|この文を十回タップ|این جمله را ده بار بزن|点按这句十次'),
  sos_done: R('Geçti. Sen buradasın.|It passed. You are here.|Keçdi. Sən buradasan.|Прошло. Ты здесь.|Pasó. Estás aquí.|C’est passé. Tu es ici.|Vorbei. Du bist hier.|È passato. Sei qui.|Passou. Você está aqui.|مرّ. أنت هنا.|Voorbij. Jij bent hier.|Minęło. Jesteś tutaj.|Минуло. Ти тут.|過ぎた。あなたはここにいる。|گذشت. تو اینجایی.|已过。你在这里。'),
  sos_back: R('Ana sayfa|Home|Ana səhifə|Домой|Inicio|Accueil|Startseite|Home|Início|الرئيسية|Home|Strona główna|На головну|ホーム|خانه|首页'),
  sos_stop: R('Sesleri durdur|Stop sounds|Səsləri dayandır|Остановить звуки|Parar sonidos|Arrêter les sons|Klänge stoppen|Ferma i suoni|Parar sons|إيقاف الأصوات|Geluiden stoppen|Zatrzymaj dźwięki|Зупинити звуки|音を止める|توقف صدا|停止声音'),
  sos_open_lock: R('SOS — kilitten açılır|SOS — opens from the lock|SOS — kiliddən açılır|SOS — открывается с замка|SOS — abre desde el candado|SOS — s’ouvre depuis le verrou|SOS — öffnet von der Sperre|SOS — si apre dal blocco|SOS — abre do bloqueio|SOS — يفتح من القفل|SOS — opent vanaf het slot|SOS — otwiera się z zamka|SOS — відкривається із замка|SOS — ロックからも開く|SOS — از قفل باز می‌شود|SOS — 可从锁打开'),
  sos_lock_title: R('Steady kilitli|Steady is locked|Steady kilidlidir|Steady заблокирован|Steady está cerrado|Steady est verrouillé|Steady ist gesperrt|Steady è bloccato|Steady está bloqueado|Steady مقفل|Steady is vergrendeld|Steady jest zablokowany|Steady заблоковано|Steadyはロック中|Steady قفل است|Steady 已锁定'),
  sos_four: R('Dört hane|Four digits|Dörd rəqəm|Четыре цифры|Cuatro dígitos|Quatre chiffres|Vier Ziffern|Quattro cifre|Quatro dígitos|أربع أرقام|Vier cijfers|Cztery cyfry|Чотири цифри|4桁|چهار رقم|四位'),
  sos_wave_in: R('Dalga inince Geçti.|When the wave recedes, It passed.|Dalğa enəndə Keçdi.|Когда волна спадает — Прошло.|Cuando baja la ola: Pasó.|Quand la vague redescend : C’est passé.|Wenn die Welle fällt: Vorbei.|Quando l’onda cala: È passato.|Quando a onda baixa: Passou.|عندما ينحسر الموج: مرّ.|Als de golf zakt: Voorbij.|Gdy fala opada: Minęło.|Коли хвиля спадає: Минуло.|波が引いたら「過ぎた」。|وقتی موج فروکش کرد: گذشت.|浪退后点「已过」。'),
  sos_tap_btn: R('Dokun|Tap|Toxun|Нажми|Toca|Touche|Tippen|Tocca|Toque|المس|Tik|Dotknij|Натисни|タップ|بزن|点按'),
  sos_thanks: R('Bırakıyorum. Küçük bir şükran yeter. Nefes alabildiğim için.|I release. A small thanks is enough. For being able to breathe.|Buraxıram. Kiçik minnətdarlıq bəsdir.|Отпускаю. Малой благодарности довольно.|Suelto. Basta una pequeña gracia.|Je lâche. Un petit merci suffit.|Ich lasse los. Ein kleines Danke reicht.|Rilascio. Basta un piccolo grazie.|Solto. Um pequeno obrigado basta.|أفلت. شكر صغير يكفي.|Ik laat los. Een klein dank is genoeg.|Puszczam. Małe dziękuję wystarczy.|Відпускаю. Малої подяки досить.|手放す。小さな感謝で足りる。息ができたことに。|رها می‌کنم. یک سپاس کوچک بس است.|我放下。小小感恩就够。因为还能呼吸。'),

  pay_kicker: R('Vitrin|Storefront|Vitrin|Витрина|Escaparate|Vitrine|Schaufenster|Vetrina|Vitrine|واجهة|Etalage|Witryna|Вітрина|ショーウィンドウ|ویترین|橱窗'),
  pay_title: R('Pro|Pro|Pro|Pro|Pro|Pro|Pro|Pro|Pro|برو|Pro|Pro|Pro|Pro|پرو|Pro'),
  pay_sub: R('SOS her zaman açık. Gerisi bu cihazda kalır.|SOS is always open. The rest stays on this device.|SOS həmişə açıqdır. Qalanı bu cihazdadır.|SOS всегда открыт. Остальное на этом устройстве.|SOS siempre está abierto. Lo demás queda en este dispositivo.|SOS est toujours ouvert. Le reste reste sur l’appareil.|SOS ist immer offen. Der Rest bleibt auf diesem Gerät.|SOS è sempre aperto. Il resto resta su questo dispositivo.|SOS está sempre aberto. O resto fica neste aparelho.|SOS مفتوح دائمًا. الباقي على هذا الجهاز.|SOS is altijd open. De rest blijft op dit apparaat.|SOS jest zawsze otwarte. Reszta zostaje na tym urządzeniu.|SOS завжди відкритий. Решта на цьому пристрої.|SOSはいつも開く。残りはこの端末に。|SOS همیشه باز است. بقیه روی این دستگاه می‌ماند.|SOS 始终可用。其余留在本机。'),
  pay_open: R('Cihazda Pro’yu aç|Turn on Pro on this device|Cihazda Pro-nu aç|Включить Pro на устройстве|Activar Pro en este dispositivo|Activer Pro sur l’appareil|Pro auf diesem Gerät öffnen|Attiva Pro su questo dispositivo|Ativar Pro neste aparelho|تفعيل برو على الجهاز|Pro op dit apparaat|Włącz Pro na tym urządzeniu|Увімкнути Pro на пристрої|この端末でProをオン|در این دستگاه پرو را روشن کن|在本机打开 Pro'),
  pay_stripe: R('Stripe sonra. Bu buton yalnızca yerel vitrin demosu.|Stripe later. This button is a local storefront demo only.|Stripe sonra. Bu düymə yalnız yerli vitrin demosudur.|Stripe позже. Эта кнопка — только демо витрины.|Stripe después. Este botón es solo una demo local.|Stripe plus tard. Ce bouton n’est qu’une démo locale.|Stripe später. Nur lokale Schaufenster-Demo.|Stripe dopo. Questo pulsante è solo una demo locale.|Stripe depois. Este botão é só uma demo local.|سترايب لاحقًا. هذا الزر عرض محلي فقط.|Stripe later. Deze knop is alleen een lokale demo.|Stripe później. Ten przycisk to tylko lokalne demo.|Stripe пізніше. Ця кнопка лише локальне демо.|Stripeは後で。このボタンは端末デモのみ。|استرایپ بعداً. این دکمه فقط دموی محلی است.|Stripe 稍后。此按钮仅为本地演示。'),
  pay_week: R('Haftalık|Weekly|Həftəlik|Неделя|Semanal|Hebdomadaire|Wöchentlich|Settimanale|Semanal|أسبوعي|Wekelijks|Tygodniowo|Тиждень|週ごと|هفتگی|每周'),
  pay_month: R('Aylık|Monthly|Aylıq|Месяц|Mensual|Mensuel|Monatlich|Mensile|Mensal|شهري|Maandelijks|Miesięcznie|Місяць|月ごと|ماهانه|每月'),
  pay_year: R('Yıllık|Yearly|İllik|Год|Anual|Annuel|Jährlich|Annuale|Anual|سنوي|Jaarlijks|Rocznie|Рік|年ごと|سالانه|每年'),
  pay_featured: R('önerilen|suggested|tövsiyə|рекомендуем|sugerido|suggéré|empfohlen|consigliato|sugerido|مقترح|aanbevolen|sugerowane|рекомендовано|おすすめ|پیشنهادی|推荐'),
  pay_note: R('3 gün deneme · vitrin fiyatı|3-day trial · storefront price|3 gün sınaq · vitrin qiyməti|3 дня пробы · витринная цена|Prueba de 3 días · precio vitrina|Essai 3 jours · prix vitrine|3 Tage Test · Schaufensterpreis|Prova 3 giorni · prezzo vetrina|Teste 3 dias · preço vitrine|تجربة 3 أيام · سعر الواجهة|3 dagen proef · etalageprijs|3 dni próby · cena witryny|3 дні проби · вітринна ціна|3日体験 · 表示価格|۳ روز آزمایش · قیمت ویترین|3 天试用 · 标价'),
  pay_year_note: R('3 gün deneme · en sakin tempo|3-day trial · the calmest pace|3 gün sınaq · ən sakit tempo|3 дня пробы · самый спокойный темп|Prueba de 3 días · el ritmo más calmo|Essai 3 jours · le tempo le plus calme|3 Tage Test · ruhigstes Tempo|Prova 3 giorni · il ritmo più calmo|Teste 3 dias · o ritmo mais calmo|تجربة 3 أيام · الوتيرة الأهدأ|3 dagen proef · het kalmste tempo|3 dni próby · najspokojniejsze tempo|3 дні проби · найспокійніший темп|3日体験 · いちばん静かな速さ|۳ روز آزمایش · آرام‌ترین ریتم|3 天试用 · 最缓节奏'),
  pay_back: R('Geri dön|Go back|Geri qayıt|Назад|Volver|Retour|Zurück|Indietro|Voltar|رجوع|Terug|Wstecz|Назад|戻る|بازگشت|返回'),
  pay_on: R('Pro bu cihazda açık|Pro is on for this device|Pro bu cihazda açıqdır|Pro включён на устройстве|Pro está activo en este dispositivo|Pro est actif sur cet appareil|Pro ist auf diesem Gerät an|Pro è attivo su questo dispositivo|Pro está ativo neste aparelho|برو مفعّل على هذا الجهاز|Pro staat aan op dit apparaat|Pro jest włączone na tym urządzeniu|Pro увімкнено на цьому пристрої|この端末でProはオン|پرو روی این دستگاه روشن است|本机已打开 Pro'),
  pay_free_k: R('Ücretsiz|Free|Pulsuz|Бесплатно|Gratis|Gratuit|Kostenlos|Gratis|Grátis|مجاني|Gratis|Darmowe|Безкоштовно|無料|رایگان|免费'),
  pay_pro_k: R('Pro|Pro|Pro|Pro|Pro|Pro|Pro|Pro|Pro|برو|Pro|Pro|Pro|Pro|پرو|Pro'),

  back: R('Geri|Back|Geri|Назад|Atrás|Retour|Zurück|Indietro|Voltar|رجوع|Terug|Wstecz|Назад|戻る|بازگشت|返回'),
  play: R('Çal|Play|Oxut|Играть|Reproducir|Lire|Abspielen|Riproduci|Tocar|تشغيل|Afspelen|Odtwórz|Грати|再生|پخش|播放'),
  stop: R('Durdur|Stop|Dayandır|Стоп|Parar|Arrêter|Stopp|Ferma|Parar|إيقاف|Stop|Stop|Стоп|停止|توقف|停止'),
  speak: R('Sesli oku|Read aloud|Səsli oxu|Вслух|Leer en voz alta|Lire à voix haute|Vorlesen|Leggi ad alta voce|Ler em voz alta|اقرأ بصوت|Voorlezen|Czytaj głośno|Вголос|読み上げ|با صدا بخوان|朗读'),
  speak_stop: R('Okumayı durdur|Stop reading|Oxumanı dayandır|Остановить чтение|Parar lectura|Arrêter la lecture|Lesen stoppen|Ferma lettura|Parar leitura|إيقاف القراءة|Stop met lezen|Zatrzymaj czytanie|Зупити читання|読み上げを止める|توقف خواندن|停止朗读'),
  leave: R('Bırak|Release|Burax|Отпустить|Soltar|Lâcher|Loslassen|Rilascia|Soltar|أفلت|Loslaten|Puść|Відпустити|手放す|رها کن|放下'),
  remaining: R('Kalan deneme|Trial left|Qalan sınaq|Остаток пробы|Prueba restante|Essai restant|Resttest|Prova restante|Teste restante|المتبقي من التجربة|Resterende proef|Pozostała próba|Залишок проби|体験の残り|باقی‌مانده آزمایش|试用剩余'),
  trial_done: R('Deneme bitti|Trial ended|Sınaq bitdi|Проба окончена|Prueba terminada|Essai terminé|Test beendet|Prova finita|Teste encerrado|انتهت التجربة|Proef voorbij|Próba skończona|Пробу закінчено|体験終了|آزمایش تمام شد|试用结束'),
  trial_done_sub: R('3 dakika doldu. Sınırsız dinleme Pro’da. SOS her zaman açık.|3 minutes are up. Unlimited listening is Pro. SOS still never locks.|3 dəqiqə doldu. Limitsiz dinləmə Pro-dadır. SOS həmişə açıqdır.'),
  playing: R('Çalıyor|Playing|Oxuyur|Играет|Reproduciendo|Lecture|Läuft|In riproduzione|A tocar|يعمل|Speelt|Odtwarzanie|Грає|再生中|در حال پخش|播放中'),
  ready: R('Hazır|Ready|Hazır|Готово|Listo|Prêt|Bereit|Pronto|Pronto|جاهز|Klaar|Gotowe|Готово|準備完了|آماده|就绪'),
  start_min: R('{n} dk başlat|Start {n} min|{n} dəq başlat|Старт {n} мин|Empezar {n} min|Démarrer {n} min|{n} Min starten|Avvia {n} min|Iniciar {n} min|ابدأ {n} دق|{n} min starten|Start {n} min|Старт {n} хв|{n}分開始|شروع {n} دقیقه|开始 {n} 分钟'),
  timer_done: R('Süre doldu. Gece tohumu: aynı sahne, gözler kapalı, bırak.|Time is up. Night seed: the same scene, eyes closed, release.|Vaxt bitdi. Gecə toxumu: eyni səhnə, gözlər bağlı, burax.|Время вышло. Ночное семя: та же сцена, глаза закрыты, отпусти.|Se acabó el tiempo. Semilla: la misma escena, ojos cerrados, suelta.|Le temps est écoulé. Graine : même scène, yeux fermés, lâcher.|Zeit um. Nachtkern: dieselbe Szene, Augen zu, loslassen.|Tempo scaduto. Seme: stessa scena, occhi chiusi, rilascia.|Tempo esgotado. Semente: a mesma cena, olhos fechados, solta.|انتهى الوقت. بذرة الليل: نفس المشهد، أعين مغلقة، أفلت.|Tijd om. Nachtzaad: dezelfde scène, ogen dicht, loslaten.|Czas minął. Ziarno: ta sama scena, oczy zamknięte, puść.|Час вийшов. Нічне зерно: та сама сцена, очі закриті, відпусти.|時間切れ。夜の種：同じ場面、目を閉じて、手放す。|زمان تمام شد. دانه شب: همان صحنه، چشم بسته، رها کن.|时间到。夜种：同一场景，闭眼，放下。'),
  nature_k: R('Doğa sahnesi|Nature scene|Təbiət səhnəsi|Сцена природы|Escena de naturaleza|Scène de nature|Naturszene|Scena di natura|Cena da natureza|مشهد طبيعة|Natuurscène|Scena natury|Сцена природи|自然の場面|صحنه طبیعت|自然场景'),
  breath_k: R('Nefes|Breath|Nəfəs|Дыхание|Respiración|Souffle|Atem|Respiro|Respiração|تنفس|Adem|Oddech|Подих|呼吸|نفس|呼吸'),
  voice_start: R('Sesli başlat|Start with voice|Səslə başlat|Начать с голоса|Empezar con voz|Démarrer à la voix|Mit Stimme starten|Avvia con voce|Começar com voz|ابدأ بالصوت|Start met stem|Start z głosem|Почати з голосу|音声で開始|با صدا شروع|语音开始'),
  no_file: R('Web Audio osilatörü. İyileştirme iddiası yok. Kayıtlı dosya yok.|Web Audio oscillator. No healing claim. No recorded files.|Web Audio osilatoru. Müalicə iddiası yoxdur. Fayl yoxdur.|Осциллятор Web Audio. Без претензии на исцеление. Без файлов.|Oscilador Web Audio. Sin pretensión de cura. Sin archivos.|Oscillateur Web Audio. Sans prétention de soin. Pas de fichier.|Web-Audio-Oszillator. Kein Heilanspruch. Keine Dateien.|Oscillatore Web Audio. Nessuna pretesa di cura. Nessun file.|Oscilador Web Audio. Sem pretensão de cura. Sem arquivos.|مذبذب ويب أوديو. بلا ادعاء شفاء. بلا ملفات.|Web Audio-oscillator. Geen geneesclaim. Geen bestanden.|Oscylator Web Audio. Bez roszczenia uzdrowienia. Bez plików.|Осцилятор Web Audio. Без заяви про зцілення. Без файлів.|Web Audioの発振。治癒の主張なし。録音ファイルなし。|نوسان‌ساز وب‌آدیو. بدون ادعای شفا. بدون پرونده.|Web Audio 振荡器。无疗愈宣称。无录音文件。'),
  tones_title: R('Tonlar|Tones|Tonlar|Тона|Tonos|Tons|Töne|Toni|Tons|نغمات|Tonen|Tony|Тони|トーン|تون‌ها|音调'),
  sleep_title: R('Uyku|Sleep|Yuxu|Сон|Sueño|Sommeil|Schlaf|Sonno|Sono|النوم|Slaap|Sen|Сон|睡眠|خواب|睡眠'),
  sleep_sub: R('Orijinal hikâyeler, tarayıcı sesi. Yedi gün bilim uykusu Pro. Doğa Web Audio ile.|Original stories, browser voice. Seven-day science sleep is Pro. Nature via Web Audio.|Orijinal hekayələr, brauzer səsi. Yeddi günlük elm yuxusu Pro-dur.|Оригинальные истории, голос браузера. Семидневный научный сон — Pro.|Relatos originales, voz del navegador. El sueño científico de 7 días es Pro.|Récits originaux, voix du navigateur. Le sommeil science 7 jours est Pro.|Originale Geschichten, Browserstimme. Sieben-Tage-Wissenschaftsschlaf ist Pro.|Racconti originali, voce del browser. Il sonno scienza di 7 giorni è Pro.|Histórias originais, voz do navegador. O sono ciência de 7 dias é Pro.|قصص أصلية، صوت المتصفح. نوم العلم لسبعة أيام هو برو.|Originele verhalen, browsersstem. Zeven dagen wetenschapslaap is Pro.|Oryginalne opowieści, głos przeglądarki. Siedmiodniowy sen nauki to Pro.|Оригінальні історії, голос браузера. Семиденний науковий сон — Pro.|オリジナル物語、ブラウザ音声。7日の科学睡眠はPro。自然はWeb Audio。|داستان‌های اصیل، صدای مرورگر. خواب علمی هفت‌روزه پرو است.|原创故事，浏览器语音。七日科学睡眠为 Pro。自然声来自 Web Audio。'),
  lab_k: R('Yedi gece|Seven nights|Yeddi gecə|Семь ночей|Siete noches|Sept nuits|Sieben Nächte|Sette notti|Sete noites|سبع ليال|Zeven nachten|Siedem nocy|Сім ночей|七つの夜|هفت شب|七夜'),
  practice_title: R('Pratik|Practice|Praktika|Практика|Práctica|Pratique|Übung|Pratica|Prática|تمرين|Oefening|Ćwiczenie|Практика|実践|تمرین|练习'),
  practice_sub: R('Netlik, meditasyon, nefes, yazı. Çoğu Pro.|Clarity, meditation, breath, writing. Most is Pro.|Aydınlıq, meditasiya, nəfəs, yazı. Çoxu Pro-dur.|Ясность, медитация, дыхание, запись. Большинство — Pro.|Claridad, meditación, respiración, escritura. Casi todo es Pro.|Clarté, méditation, souffle, écrit. La plupart est Pro.|Klarheit, Meditation, Atem, Text. Das meiste ist Pro.|Chiarezza, meditazione, respiro, scrittura. Gran parte è Pro.|Clareza, meditação, respiração, escrita. A maior parte é Pro.|صفاء، تأمل، تنفس، كتابة. معظمها برو.|Helderheid, meditatie, adem, tekst. Het meeste is Pro.|Jasność, medytacja, oddech, zapis. Większość to Pro.|Ясність, медитація, подих, запис. Більшість — Pro.|明晰、瞑想、呼吸、書く。多くはPro。|شفافیت، مدیتیشن، نفس، نوشتن. بیشتر پرو است.|清明、冥想、呼吸、书写。多为 Pro。'),
  treat_kicker: R('Başa çıkma kapıları|Coping doors|Öhdəlik qapıları|Двери совладания|Puertas de afrontamiento|Portes d’appui|Bewältigungstüren|Porte di fronteggiamento|Portas de enfrentamento|أبواب التعامل|Omdeuren|Drzwi radzenia|Двері опанування|対処の扉|درهای کنار آمدن|应对之门'),
  treat_title: R('Kapılar|Doors|Qapılar|Двери|Puertas|Portes|Türen|Porte|Portas|أبواب|Deuren|Drzwi|Двері|扉|درها|门'),
  treat_sub: R('Panik dalgadır, anksiyete yarındır, derealizasyon dünyadır, depersonalizasyon bedendir.|Panic is a wave, anxiety is tomorrow, derealization is the world, depersonalization is the body.|Panik dalğadır, narahatlıq sabahdır, derealizasiya dünyadır, depersonallaşma bədəndir.|Паника — волна, тревога — завтра, дереализация — мир, деперсонализация — тело.|El pánico es ola, la ansiedad es mañana, la desrealización es el mundo, la despersonalización es el cuerpo.|La panique est vague, l’anxiété est demain, la déréalisation est le monde, la dépersonnalisation est le corps.|Panik ist Welle, Angst ist morgen, Derealisation ist die Welt, Depersonalisation ist der Körper.|Il panico è onda, l’ansia è domani, la derealizzazione è il mondo, la depersonalizzazione è il corpo.|O pânico é onda, a ansiedade é amanhã, a desrealização é o mundo, a despersonalização é o corpo.|الهلع موجة، القلق غد،derealization العالم، depersonalization الجسد.|Paniek is een golf, angst is morgen, derealisatie is de wereld, depersonalisatie is het lijf.|Panik to fala, lęk to jutro, derealizacja to świat, depersonalizacja to ciało.|Паніка — хвиля, тривога — завтра, дереалізація — світ, деперсоналізація — тіло.|パニックは波、不安は明日、現実感喪失は世界、離人は身体。|پانیک موج است، اضطراب فردا، مسخ واقعیت جهان، مسخ شخصیت بدن.|恐慌是浪，焦虑是明天，现实解体是世界，人格解体是身体。'),
  tools: R('Araçlar|Tools|Alətlər|Инструменты|Herramientas|Outils|Werkzeuge|Strumenti|Ferramentas|أدوات|Tools|Narzędzia|Знаряддя|道具|ابزارها|工具'),
  program: R('Program|Program|Proqram|Программа|Programa|Programme|Programm|Programma|Programa|برنامج|Programma|Program|Програма|プログラム|برنامه|课程'),
  day_n: R('Gün {n}|Day {n}|Gün {n}|День {n}|Día {n}|Jour {n}|Tag {n}|Giorno {n}|Dia {n}|اليوم {n}|Dag {n}|Dzień {n}|День {n}|{n}日目|روز {n}|第 {n} 天'),
  min_n: R('{n} dk|{n} min|{n} dəq|{n} мин|{n} min|{n} min|{n} Min|{n} min|{n} min|{n} دق|{n} min|{n} min|{n} хв|{n}分|{n} دقیقه|{n} 分钟'),
  sec_n: R('{n} sn|{n} s|{n} san|{n} с|{n} s|{n} s|{n} s|{n} s|{n} s|{n} ث|{n} s|{n} s|{n} с|{n}秒|{n} ث|{n} 秒'),
  greet_night: R('Gece yarısı|Late night|Gecəyarı|Глубокая ночь|Madrugada|Nuit profonde|Tiefe Nacht|Notte fonda|Madrugada|منتصف الليل|Diepe nacht|Głęboka noc|Глибока ніч|深夜|نیمه‌شب|深夜'),
  greet_morn: R('Günaydın|Good morning|Sabahın xeyir|Доброе утро|Buenos días|Bonjour|Guten Morgen|Buongiorno|Bom dia|صباح الخير|Goedemorgen|Dzień dobry|Доброго ранку|おはよう|صبح بخیر|早安'),
  greet_day: R('İyi günler|Good day|Günün xeyir|Добрый день|Buen día|Bonne journée|Guten Tag|Buona giornata|Bom dia|نهارك سعيد|Goedendag|Miłego dnia|Доброго дня|こんにちは|روز بخیر|日安'),
  greet_eve: R('İyi akşamlar|Good evening|Axşamın xeyir|Добрый вечер|Buenas tardes|Bonsoir|Guten Abend|Buonasera|Boa noite|مساء الخير|Goedenavond|Dobry wieczór|Доброго вечора|こんばんは|عصر بخیر|晚上好'),
  sentence: R('Cümle|Line|Cümlə|Фраза|Frase|Phrase|Satz|Frase|Frase|جملة|Zin|Zdanie|Речення|一文|جمله|一句'),
  scene: R('Sahne|Scene|Səhnə|Сцена|Escena|Scène|Szene|Scena|Cena|مشهد|Scène|Scena|Сцена|場面|صحنه|场景'),
  release: R('Bırakış|Release|Buraxılış|Отпускание|Soltar|Lâcher|Loslassen|Rilascio|Soltar|إفلات|Loslaten|Puszczenie|Відпускання|手放し|رها کردن|放下'),
  gratitude: R('Şükran|Thanks|Minnətdarlıq|Благодарность|Gracias|Gratitude|Dank|Grazia|Graça|شكر|Dank|Wdzięczność|Подяка|感謝|سپاس|感恩'),
  night_seed: R('Gece tohumu|Night seed|Gecə toxumu|Ночное семя|Semilla nocturna|Graine de nuit|Nachtkern|Seme notturno|Semente da noite|بذرة الليل|Nachtzaad|Nocne ziarno|Нічне зерно|夜の種|دانه شب|夜种'),
  door_panic: R('Panik|Panic|Panik|Паника|Pánico|Panique|Panik|Panico|Pânico|هلع|Paniek|Panik|Паніка|パニック|پانیک|恐慌'),
  door_anxiety: R('Anksiyete|Anxiety|Narahatlıq|Тревога|Ansiedad|Anxiété|Angst|Ansia|Ansiedade|قلق|Angst|Lęk|Тривога|不安|اضطراب|焦虑'),
  door_dr: R('Derealizasyon|Derealization|Derealizasiya|Дереализация|Desrealización|Déréalisation|Derealisation|Derealizzazione|Desrealização|تبدد الواقع|Derealisatie|Derealizacja|Дереалізація|現実感喪失|مسخ واقعیت|现实解体'),
  door_dp: R('Depersonalizasyon|Depersonalization|Depersonallaşma|Деперсонализация|Despersonalización|Dépersonnalisation|Depersonalisation|Depersonalizzazione|Despersonalização|تبدد الشخصية|Depersonalisatie|Depersonalizacja|Деперсоналізація|離人感|مسخ شخصیت|人格解体'),
  list_open: R('Listeyi aç|Open the list|Siyahını aç|Открыть список|Abrir la lista|Ouvrir la liste|Liste öffnen|Apri l’elenco|Abrir a lista|افتح القائمة|Lijst openen|Otwórz listę|Відкрити список|一覧を開く|فهرست را باز کن|打开列表'),
  waves_hidden: R('{n} dalga bu cihazda gizli duruyor.|{n} waves sit hidden on this device.|{n} dalğa bu cihazda gizli durur.|{n} волн скрыты на этом устройстве.|{n} olas quedan ocultas en este dispositivo.|{n} vagues restent cachées sur cet appareil.|{n} Wellen liegen verborgen auf diesem Gerät.|{n} onde restano nascoste su questo dispositivo.|{n} ondas ficam ocultas neste aparelho.|{n} موجات مخفية على هذا الجهاز.|{n} golven blijven verborgen op dit apparaat.|{n} fal ukrywa się na tym urządzeniu.|{n} хвиль сховані на цьому пристрої.|この端末に{n}波が隠れている。|{n} موج روی این دستگاه پنهان است.|本机隐藏着 {n} 道浪。'),
  taps_n: R('{n} dokunuş|{n} taps|{n} toxunuş|{n} нажатий|{n} toques|{n} touches|{n} Tipps|{n} toc|{n} toques|{n} لمسات|{n} tikken|{n} tapnięć|{n} натискань|{n}タップ|{n} ضربه|{n} 次点按'),

  ob_continue: R('Devam|Continue|Davam'),
  ob_skip: R('Şimdilik ücretsiz devam et|Stay free for now|Hələlik pulsuz davam et'),
  ob_yes: R('Evet|Yes|Bəli'),
  ob_no: R('Hayır|No|Xeyr'),
  ob_welcome_k: R('Steady|Steady|Steady'),
  ob_welcome: R('Önce dilini seç.|Choose your language first.|Əvvəl dilini seç.'),
  ob_welcome_sub: R('Cevapların sadece bu telefonda kalır. Teşhis koymayız.|Answers stay on this phone. We do not diagnose.|Cavabların yalnız bu telefondadır. Diaqnoz qoymuruq.'),
  ob_bring: R('Seni buraya ne getirdi?|What brought you here?|Səni bura nə gətirdi?'),
  ob_bring_sub: R('Birini seçmen yeterli. Doğru ya da yanlış yok.|Pick one. There is no right answer.|Birini seçməyin yetər. Düzgün və ya səhv yoxdur.'),
  ob_bring_wave: R('Bir panik dalgası|A panic wave|Panik dalğası'),
  ob_bring_worry: R('Sürekli kaygı|Constant worry|Daimi narahatlıq'),
  ob_bring_sleep: R('Uykusuzluk|Sleeplessness|Yuxusuzluq'),
  ob_bring_world: R('Her şey uzak ya da gerçek dışı geliyor|Everything feels distant or unreal|Hər şey uzaq və ya qeyri-real gəlir'),
  ob_bring_self: R('Kendimi yabancı hissediyorum|I feel foreign to myself|Özümü yad kimi hiss edirəm'),
  ob_need: R('Bu gece neye ihtiyacın var?|What do you need tonight?|Bu gecə nəyə ehtiyacın var?'),
  ob_need_sub: R('Şimdilik tek bir şey yeter.|One thing is enough for now.|Hələlik bir şey bəsdir.'),
  ob_need_stop: R('Durmak|To pause|Dayanmaq'),
  ob_need_sleep: R('Uyumak|To sleep|Yatmaq'),
  ob_need_sentence: R('Kısa bir cümle|A short sentence|Qısa bir cümlə'),
  ob_need_breath: R('Nefes|Breath|Nəfəs'),
  ob_often: R('Bunu ne sıklıkla yaşıyorsun?|How often does this happen?|Bunu nə qədər tez-tez yaşayırsan?'),
  ob_often_sub: R('Tam sayı gerekmez.|An exact number is not needed.|Dəqiq rəqəm lazım deyil.'),
  ob_often_rare: R('Seyrek|Rarely|Nadirən'),
  ob_often_some: R('Ara sıra|Sometimes|Bəzən'),
  ob_often_most: R('Çoğu gece|Most nights|Çox gecələr'),
  ob_often_always: R('Neredeyse her gün|Almost every day|Demək olar hər gün'),
  ob_part: R('Bölüm 2|Part 2|2-ci hissə'),
  ob_part_title: R('Gece|Night|Gecə'),
  ob_sleep_q: R('Uykuya dalmak zor geliyor mu?|Is it hard to fall asleep?|Yuxuya getmək çətin gəlir?'),
  ob_sleep_sub: R('Saat sözü vermiyoruz. Sadece anlamak için soruyoruz.|We do not promise hours. We only ask to understand.|Saat vəd etmirik. Yalnız başa düşmək üçün soruşuruq.'),
  ob_freq_never: R('Nadiren / hiç|Rarely / never|Nadirən / heç'),
  ob_freq_some: R('Bazen|Sometimes|Bəzən'),
  ob_freq_often: R('Sık sık|Often|Tez-tez'),
  ob_freq_always: R('Neredeyse her gece|Almost every night|Demək olar hər gecə'),
  ob_agree: R('Bu cümleye katılıyor musun?|Do you agree with this?|Bu cümlə ilə razısan?'),
  ob_agree_sub: R('Doğru cevap yok.|There is no right answer.|Düzgün cavab yoxdur.'),
  ob_ag1: R('İşler istediğim gibi gitmeyince içim daralıyor.|I feel tight when things do not go as I planned.|İşlər istədiyim kimi getməyəndə içim daralır.'),
  ob_ag2: R('Bazen etraf gerçek değilmiş gibi geliyor.|Sometimes the room feels unreal.|Bəzən ətraf real deyilmiş kimi gəlir.'),
  ob_hours: R('Gecede ortalama kaç saat uyuyorsun?|How many hours do you sleep on average?|Gecədə orta hesabla neçə saat yatırsan?'),
  ob_hours_sub: R('Tahmin yeter.|A guess is enough.|Təxmin yetər.'),
  ob_h_lt6: R('6 saatten az|Less than 6 hours|6 saatdən az'),
  ob_h_67: R('6–7 saat|6–7 hours|6–7 saat'),
  ob_h_78: R('7–8 saat|7–8 hours|7–8 saat'),
  ob_h_89: R('8–9 saat|8–9 hours|8–9 saat'),
  ob_h_9: R('9 saat veya daha fazla|9 hours or more|9 saat və ya daha çox'),
  ob_wake: R('Gecenin ortasında uyanıyor musun?|Do you wake in the middle of the night?|Gecənin ortasında oyanırsan?'),
  ob_wake_every: R('Her gece|Every night|Hər gecə'),
  ob_wake_most: R('Çoğu gece|Most nights|Çox gecələr'),
  ob_wake_some: R('Ara sıra|Occasionally|Bəzən'),
  ob_wake_rare: R('Nadiren|Rarely|Nadirən'),
  ob_fall: R('Bu gece nasıl uykuya varmak istersin?|How would you like to fall asleep tonight?|Bu gecə necə yatmaq istəyirsən?'),
  ob_fall_sub: R('Birden fazla seçebilirsin. Programa ekleriz.|You can pick more than one. We will add them.|Birdən çox seçə bilərsən. Proqrama əlavə edəcəyik.'),
  ob_fall_med: R('Uyku meditasyonu|Sleep meditation|Yuxu meditasiyası'),
  ob_fall_story: R('Uyku hikâyesi|Sleep story|Yuxu hekayəsi'),
  ob_fall_nature: R('Doğa sesleri|Nature sounds|Təbiət səsləri'),
  ob_medex: R('Meditasyonla aran nasıl?|What is your experience with meditation?|Meditasiya ilə aran necədir?'),
  ob_medex_sub: R('Buna göre öneri sırasını ayarlarız.|This helps us order suggestions.|Buna görə təklif sırasını quracağıq.'),
  ob_medex_none: R('Az ya da hiç yok|Little to none|Az və ya heç yoxdur'),
  ob_medex_some: R('Ara sıra denerim|I try it now and then|Bəzən sınayıram'),
  ob_medex_skip: R('Şimdilik ilgilenmiyorum|Not interested right now|Hələlik maraqlı deyil'),
  ob_hope: R('Endişelenme. Mucize değil; bu gece yanında duracak bir yer.|Don’t worry. Not a miracle; a place that stays with you tonight.|Narahat olma. Möcüzə yoxdur; bu gecə yanında duracaq bir yer.'),
  ob_before: R('Şimdi|Now|İndi'),
  ob_after: R('Birlikte|Together|Birlikdə'),
  ob_b1: R('Gece boyunca düşünmek|Thinking all night|Gecə boyu düşünmək'),
  ob_b2: R('Odada değilmiş gibi olmak|Feeling not in the room|Otaqda deyilmiş kimi olmaq'),
  ob_b3: R('Yarını kurmak|Building tomorrow|Sabahı qurmaq'),
  ob_b4: R('Gerilmiş beden|A tense body|Gərgin bədən'),
  ob_b5: R('Uykunun gelmemesi|Sleep not coming|Yuxunun gəlməməsi'),
  ob_a1: R('Dalgayı izlemek, zorlamamak|Watching the wave, not forcing it|Dalğanı izləmək, məcbur etməmək'),
  ob_a2: R('Şimdiye ait kısa bir cümle|A short present-tense line|İndiki zamana aid qısa cümlə'),
  ob_a3: R('Çene yumuşak, nefes uzun|Soft jaw, long breath|Çənə yumşaq, nəfəs uzun'),
  ob_a4: R('Bir sahne, sonra bırakmak|A scene, then letting go|Bir səhnə, sonra buraxmaq'),
  ob_a5: R('Uyku gelirse gelsin|Sleep if it comes|Yuxu gələrsə gəlsin'),
  ob_analyze: R('Birkaç gün içinde daha yumuşak geceler|Softer nights in a couple of days|Bir neçə günə daha yumşaq gecələr'),
  ob_analyze_sub: R('Bu bir tedavi sonucu değil. Cevaplarına göre yön.|This is not a medical result. A direction from your answers.|Bu müalicə nəticəsi deyil. Cavablarına görə istiqamət.'),
  ob_an_rest: R('Kesintisiz duruş|Uninterrupted presence|Fasiləsiz duruş'),
  ob_an_rest_to: R('daha uzun|longer|daha uzun'),
  ob_an_land: R('Uykuya inmek|Settling into sleep|Yuxuya enmək'),
  ob_an_land_to: R('daha yumuşak|softer|daha yumşaq'),
  ob_plan: R('Sana özel gece planı hazırlanıyor|Your night plan is being prepared|Sənə özəl gecə planı hazırlanır'),
  ob_plan_sub: R('Birkaç saniye. Sahte yorum yok.|A few seconds. No fake reviews.|Bir neçə saniyə. Saxta rəy yoxdur.'),
  ob_p1: R('Biraz bekleyelim…|This may take a few seconds…|Bir az gözləyək…'),
  ob_p2: R('4-2-6 nefes ritmi|4-2-6 breath rhythm|4-2-6 nəfəs ritmi'),
  ob_p3: R('Yumuşak sesler ve gece hikâyeleri|Soft sound and night stories|Yumşaq səslər və gecə hekayələri'),
  ob_p4: R('Şimdiye ait cümleler|Present-tense lines|İndiki zamana aid cümlələr'),
  ob_p5: R('Hazır.|Ready.|Hazırdır.'),
  ob_remind: R('Hatırlatmalar|Reminders|Xatırlatmalar'),
  ob_remind_sub: R('İsteğe bağlı. Sunucu yok; izin verirsen bu telefonda kalır.|Optional. No server; if you allow it, it stays on this phone.|İstəyə bağlı. Server yoxdur; icazə versən bu telefonda qalır.'),
  ob_rem_quote: R('Günün cümlesi|Line of the day|Günün cümləsi'),
  ob_rem_quote_h: R('Uygulama açıkken sabah bir satır.|A morning line while the app is open.|Tətbiq açıq olanda səhər bir sətir.'),
  ob_rem_sleep: R('Uyku hatırlatması|Sleep reminder|Yuxu xatırlatması'),
  ob_rem_sleep_h: R('Gece, istersen uyku sayfasına.|At night, toward Sleep if you want.|Gecə, istəsən Yuxu səhifəsinə.'),
  ob_rem_trial: R('Deneme bitmeden hatırlat|Remind me before the trial ends|Sınaq bitməmiş xatırlat'),
  ob_trial: R('Üç gün ücretsiz dene|Start your three free days|Üç gün pulsuz sına'),
  ob_trial_sub: R('Planın hazır.|Your plan is ready.|Planın hazırdır.'),
  ob_tl1: R('Plan oluşturuldu.|The plan is set.|Plan quruldu.'),
  ob_tl2: R('Bugün — hemen açılır|Today — opens now|Bu gün — dərhal açılır'),
  ob_tl2s: R('SOS her zaman. Üç gün boyunca diğer içerikler de açık.|SOS always. Other content opens for three days.|SOS həmişə. Üç gün ərzində digər məzmun da açıqdır.'),
  ob_tl3: R('2. gün — hatırlatma|Day 2 — a reminder|2-ci gün — xatırlatma'),
  ob_tl3s: R('İstersen, deneme bitmeden bir not.|If you want, a note before it ends.|İstəsən, sınaq bitməmiş bir qeyd.'),
  ob_tl4: R('3. gün — deneme biter|Day 3 — the trial ends|3-cü gün — sınaq bitir'),
  ob_tl4s: R('Sonra ücretsiz katman. SOS kapanmaz. İptal Ayarlar’da.|Then the free tier. SOS stays open. Cancel in Settings.|Sonra pulsuz qat. SOS bağlanmır. Ləğv Ayarlardadır.'),
  ob_cta: R('Üç günlük denemeyi başlat|Start my three free days|Üç günlük sınağı başlat'),
  ob_price: R('3 gün bu telefonda Pro. Sonra aylık $9.99 (gösterim fiyatı). Ödeme sonra. SOS her zaman açık.|3 days of Pro on this phone, then $9.99/mo display price. Payment later. SOS always open.|3 gün bu telefonda Pro açıqdır. Sonra aylıq $9.99 (göstəriş qiyməti). Ödəniş sonra. SOS həmişə açıqdır.'),
  ob_path_sos: R('Panik için SOS|SOS for panic|Panik üçün SOS'),
  ob_path_sos_s: R('Nefes, ses, Geçti.|Breath, sound, It passed.|Nəfəs, səs, Keçdi.'),
  ob_path_sleep: R('Gece uykusu|Night sleep|Gecə yuxusu'),
  ob_path_sleep_s: R('Hikâye, sahne, tohum.|Story, scene, seed.|Hekayə, səhnə, toxum.'),
  ob_path_quote: R('Bir cümle|A sentence|Bir cümlə'),
  ob_path_quote_s: R('Günün cümlesi burada.|Today’s line is here.|Günün cümləsi buradadır.'),
  ob_path_breath: R('Dalga nefesi|Wave breath|Dalğa nəfəsi'),
  ob_path_breath_s: R('4-2-6, sesli.|4-2-6, spoken.|4-2-6, səsli.'),
  ob_path_worry: R('Kaygı kapısı|Worry door|Narahatlıq qapısı'),
  ob_path_worry_s: R('Yarın için bir durak.|A pause for tomorrow.|Sabah üçün bir dayanacaq.'),
  ob_path_world: R('Dünya kapısı|The world door|Dünya qapısı'),
  ob_path_world_s: R('Kenarlar, oda, yer.|Edges, room, ground.|Kənarlar, otaq, yer.'),
  ob_path_self: R('Beden kapısı|The body door|Bədən qapısı'),
  ob_path_self_s: R('Ben buradayım, bu bedende.|I am here, in this body.|Mən buradayam, bu bədəndə.'),
  ob_path_disc: R('Keşfet|Discover|Kəşf et'),
  ob_path_disc_s: R('Bugün yalnızca biri.|Only one, today.|Bu gün yalnız biri.'),
  me_trial: R('Deneme · {n} gün|Trial · {n} days|Sınaq · {n} gün'),
  me_trial_today: R('Deneme · bugün biter|Trial · ends today|Sınaq · bu gün bitir'),
  me_ob_replay: R('Karşılama akışını yeniden göster|Show the welcome flow again|Qarşılama axınını yenidən göstər'),
} as const

const RAW = { ...CORE, ...EXTRA, ...ONBOARD_I18N } as const

export function interpolate(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => String(vars[k] ?? ''))
}

export function translate(key: StringKey, locale: LocaleId, vars?: Record<string, string | number>): string {
  const table = RAW[key]
  const text = table[locale] || table.en || table.tr
  return vars ? interpolate(text, vars) : text
}

export const STRING_TABLE = RAW
