import { R, type LocaleId } from './locales'
import { EXTRA } from './extra-strings'
import { ONBOARD_I18N } from './onboard-i18n'

export type StringKey = keyof typeof RAW

const CORE = {
  nav_home: R('Bugün|Today|Bu gün|Сегодня|Hoy|Oggi'),
  nav_discover: R('Keşfet|Explore|Kəşf et|Обзор|Explorar|Esplora'),
  nav_sleep: R('Uyku|Sleep|Yuxu|Сон|Sueño|Sonno'),
  nav_sounds: R('Sesler|Sounds|Səslər|Звуки|Sonidos|Suoni'),
  nav_more: R('Daha|More|Daha çox|Ещё|Más|Altro'),
  nav_me: R('Profil|Profile|Profil|Профиль|Perfil|Profilo'),

  home_kicker: R('Steady · 6 dil|Steady · 6 languages|Steady · 6 dil|Steady · 6 языков|Steady · 6 idiomas|Steady · 6 lingue'),
  home_headline: R('Buradasın.|You’re here.|Buradasan.|Ты здесь.|Estás aquí.|Sei qui.'),
  home_calm: R('Yavaş. Bugün bir şey yeter.|Slow. One thing is enough today.|Yavaş. Bu gün bir şey bəsdir.|Медленно. Сегодня хватит одного.|Despacio. Hoy basta una cosa.|Piano. Oggi basta una cosa.'),
  disc_calm: R('Bugün yalnızca birini seç.|Choose only one, today.|Bu gün yalnız birini seç.|Сегодня выбери только одно.|Hoy elige solo uno.|Oggi scegline solo uno.'),
  see_all: R('Tümünü göster|Show all|Hamısını göstər|Показать все|Ver todo|Mostra tutto'),
  see_less: R('Daha az|Show less|Daha az|Меньше|Ver menos|Mostra meno'),
  home_sub: R('Panik tek kapı değil. Uyku, nefes, sözler ve hikâyeler burada.|Panic is only one door. Sleep, breath, lines and stories are here.|Panik tək qapı deyil. Yuxu, nəfəs, sözlər və hekayələr buradadır.|Паника — не единственная дверь. Сон, дыхание, слова и истории здесь.|El pánico no es la única puerta. Sueño, respiración, palabras e historias.|Il panico non è l’unica porta. Sonno, respiro, parole e storie.'),
  home_sos: R('Kriz anı|Crisis moment|Böhran anı|Момент кризиса|Momento de crisis|Momento di crisi'),
  home_sos_sub: R('174 Hz · kahverengi gürültü · sesli nefes · kilitlenmez|174 Hz · brown noise · voiced breath · never locked|174 Hz · qəhvəyi küy · səsli nəfəs · kilidlənmir|174 Гц · коричневый шум · голос дыхания · не блокируется|174 Hz · ruido marrón · respiración hablada · nunca se bloquea|174 Hz · rumore bruno · respiro parlato · mai bloccato'),
  home_now: R('Şimdi|Now|İndi|Сейчас|Ahora|Ora'),
  home_trial: R('Deneme|Trial|Sınaq|Проба|Prueba|Prova'),
  home_clarity: R('Netlik|Clarity|Aydınlıq|Ясность|Claridad|Chiarezza'),
  home_free: R('ücretsiz|free|pulsuz|бесплатно|gratis|gratis'),
  home_night: R('Gece|Night|Gecə|Ночь|Noche|Notte'),
  home_story_free: R('Ücretsiz hikâye · sesli okuma|Free story · spoken aloud|Pulsuz hekayə · səsli oxu|Бесплатная история · вслух|Relato gratis · lectura en voz|Racconto libero · letto ad alta voce'),
  home_quote: R('Günün cümlesi|Line of the day|Günün cümləsi|Фраза дня|Frase del día|Frase del giorno'),
  home_lang: R('Dil|Language|Dil|Язык|Idioma|Lingua'),

  disc_title: R('Keşfet|Discover|Kəşf et|Обзор|Descubrir|Scopri'),
  disc_sub: R('Çok yol yok. Seçilmiş içerikler. Teşhis yok.|Not a thousand paths. Chosen pieces. No diagnosis.|Çox yol yoxdur. Seçilmiş məzmun. Diaqnoz yoxdur.|Не тысяча путей. Выбранное. Без диагноза.|No mil caminos. Piezas elegidas. Sin diagnóstico.|Non mille vie. Pezzi scelti. Nessuna diagnosi.'),
  cat_meditate: R('Meditasyonlar|Meditations|Meditasiyalar|Медитации|Meditaciones|Meditazioni'),
  cat_stories: R('Uyku hikâyeleri|Sleep stories|Yuxu hekayələri|Истории для сна|Relatos de sueño|Racconti del sonno'),
  cat_breath: R('Nefes|Breath|Nəfəs|Дыхание|Respiración|Respiro'),
  cat_write: R('Yazılar|Writings|Qeydlər|Записи|Escritos|Scritture'),
  cat_nature: R('Doğa sesleri|Nature sounds|Təbiət səsləri|Звуки природы|Sonidos de la naturaleza|Suoni della natura'),
  cat_quotes: R('Sözler|Lines|Sözlər|Слова|Palabras|Parole'),
  cat_cope: R('Kapılar|Doors|Qapılar|Двери|Puertas|Porte'),
  cat_tones: R('Tonlar|Tones|Tonlar|Тона|Tonos|Toni'),
  cat_more: R('Ve daha fazlası|And more|Və daha çoxu|И ещё|Y más|E altro'),
  cat_sos: R('SOS|SOS|SOS|SOS|SOS|SOS'),
  cat_clarity: R('Günlük netlik|Daily clarity|Gündəlik aydınlıq|Ежедневная ясность|Claridad diaria|Chiarezza quotidiana'),

  quotes_title: R('Sözler|Lines|Sözlər|Слова|Palabras|Parole'),
  quotes_sub: R('Eski metinlerin kendi anlatımımız. Modern kitap kopyası yok.|Our own wording of old public lines. No modern book text.|Köhnə mətnləri öz sözümüzlə yazırıq. Müasir kitab yoxdur.|Старые строки своими словами. Без современных книг.|Textos antiguos con nuestras palabras. Sin libros modernos.|Righe antiche con parole nostre. Niente libri moderni.'),
  quotes_pd: R('Kamu malı|Public domain|İctimai domen|Общественное достояние|Dominio público|Pubblico dominio'),
  quotes_essence: R('Yaklaşım özü · alıntı değil|Approach essence · not a quotation|Yanaşma özü · sitat deyil|Суть подхода · не цитата|Esencia de enfoque · no es cita|Essenza di approccio · non una citazione'),
  quotes_tap: R('Özü aç|Open the essence|Özü aç|Открыть суть|Abrir la esencia|Apri l’essenza'),
  quotes_listen: R('Sesli oku|Read aloud|Səsli oxu|Прочитать вслух|Leer en voz alta|Leggi ad alta voce'),
  quotes_close: R('Kapat|Close|Bağla|Закрыть|Cerrar|Chiudi'),

  more_title: R('Daha fazla|More|Daha çox|Ещё|Más|Altro'),
  more_sub: R('Küçük araçlar. Tedavi iddiası yok.|Small tools. No treatment claim.|Kiçik alətlər. Müalicə iddiası yoxdur.|Малые инструменты. Без претензии на лечение.|Herramientas pequeñas. Sin pretensión de tratamiento.|Piccoli strumenti. Nessuna pretesa di cura.'),
  more_ground: R('5-4-3-2-1 yer|5-4-3-2-1 ground|5-4-3-2-1 yer|5-4-3-2-1 земля|5-4-3-2-1 suelo|5-4-3-2-1 terra'),
  more_gratitude: R('Üç küçük şükran|Three small thanks|Üç kiçik minnətdarlıq|Три малые благодарности|Tres gracias pequeñas|Tre piccoli ringraziamenti'),
  more_bodyscan: R('Beden taraması|Body scan|Bədən tarama|Сканирование тела|Barrido corporal|Scansione del corpo'),
  more_seed: R('Gece tohumu|Night seed|Gecə toxumu|Ночное семя|Semilla nocturna|Seme notturno'),
  more_worry: R('Kaygı penceresi|Worry window|Narahatlıq pəncərəsi|Окно тревоги|Ventana de preocupación|Finestra di preoccupazione'),
  more_values: R('Değer pusulası|Values compass|Dəyər kompası|Компас ценностей|Brújula de valores|Bussola dei valori'),
  more_kind: R('Nazik arkadaş|Kind friend|Zərif dost|Добрый друг|Amigo amable|Amico gentile'),
  more_walk: R('On adım|Ten steps|On addım|Десять шагов|Diez pasos|Dieci passi'),
  more_tension: R('Gerilim bırakışı|Tension drop|Gərginlik buraxılışı|Сброс напряжения|Soltar tensión|Rilasciare la tensione'),
  more_morning: R('Sabah ışığı|Morning light|Səhər işığı|Утренний свет|Luz de mañana|Luce del mattino'),

  me_title: R('Profil|Profile|Profil|Профиль|Perfil|Profilo'),
  me_sub: R('Dil telefon Ayarları’ndan gelir.|Language comes from phone Settings.|Dil telefon Ayarlarından gəlir.|Язык берётся из настроек телефона.|El idioma sale de Ajustes.|La lingua arriva da Impostazioni.'),
  me_tier: R('Durum|Status|Vəziyyət|Статус|Estado|Stato'),
  me_settings: R('Ayarlar|Settings|Ayarlar|Настройки|Ajustes|Impostazioni'),
  me_pro: R('Pro|Pro|Pro|Pro|Pro|Pro'),
  me_free: R('Ücretsiz|Free|Pulsuz|Бесплатно|Gratis|Gratis'),
  me_pin: R('Dört haneli kilit|Four-digit lock|Dörd rəqəmli kilid|Четырёхзначный замок|Candado de cuatro dígitos|Blocco a quattro cifre'),
  me_pin_body: R('SOS kilit ekranından da açılır. PIN yalnızca bu tarayıcıda özetlenir.|SOS still opens from the lock screen. The PIN is hashed in this browser only.|SOS kilid ekranından da açılır.|SOS открывается и с экрана блокировки.|SOS también abre desde la pantalla de bloqueo.|SOS si apre anche dalla schermata di blocco.'),
  me_lock_now: R('Şimdi kilitle|Lock now|İndi kilidlə|Заблокировать|Bloquear ahora|Blocca ora'),
  me_lock_off: R('Kilit kaldır|Remove lock|Kilidi götür|Снять замок|Quitar candado|Rimuovi blocco'),
  me_lock_set: R('Kilit kur|Set lock|Kilid qur|Установить замок|Crear candado|Imposta blocco'),
  me_pin_new: R('Yeni PIN|New PIN|Yeni PIN|Новый PIN|Nuevo PIN|Nuovo PIN'),
  me_pin_again: R('Yeniden gir|Enter again|Yenidən yaz|Повторите|Otra vez|Di nuovo'),
  me_pin_match: R('Onay için aynı dört hane|Same four digits to confirm|Təsdiq üçün eyni dörd rəqəm|Те же четыре цифры|Los mismos cuatro dígitos|Le stesse quattro cifre'),
  me_pin_fail: R('Eşleşmedi. Baştan.|No match. Start over.|Uyğun gəlmədi. Başdan.|Не совпало. Сначала.|No coincide. De nuevo.|Non coincide. Riparti.'),
  me_history: R('Geçti geçmişi|Passed history|Keçdi tarixçəsi|История «прошло»|Historial de Pasó|Cronologia Passato'),
  me_history_locked: R('Kayıtlar tutulur, liste Pro’dadır.|Records are kept; the list is Pro.|Qeydlər saxlanır, siyahı Pro-dadır.|Записи хранятся; список — Pro.|Se guardan; la lista es Pro.|Salvati; l’elenco è Pro.'),
  me_history_empty: R('Henüz Geçti yok.|No Passed yet.|Hələ Keçdi yoxdur.|Пока нет «прошло».|Aún no hay Pasó.|Nessun Passato ancora.'),
  me_approach: R('Rahat beden. Kısa şimdiki zaman cümle. Sahne. Gece tohumu. Bırakış. Şükran. Murphy alıntısı yok.|Relaxed body. Short present-tense line. Scene. Night seed. Release. Thanks. No Murphy quotation.|Rahat bədən. Qısa indiki zaman. Səhnə. Gecə toxumu. Buraxılış. Minnətdarlıq. Murphy yoxdur.|Расслабленное тело. Короткая фраза в настоящем. Сцена. Ночное семя. Отпускание. Благодарность. Без Мёрфи.|Cuerpo relajado. Frase breve en presente. Escena. Semilla nocturna. Soltar. Gracias. Sin Murphy.|Corpo morbido. Frase breve al presente. Scena. Seme notturno. Rilascio. Grazia. Niente Murphy.'),
  me_demo_off: R('Demo Pro’yu kapat|Turn off demo Pro|Demo Pro-nu bağla|Выключить демо Pro|Cerrar demo Pro|Chiudi demo Pro'),
  me_vitrine: R('Pro’yu aç|Open Pro|Pro-nu aç|Открыть Pro|Abrir Pro|Apri Pro'),

  legal_full: R('Steady tıbbi teşhis veya tedavi sunmaz. Başa çıkma araçlarıdır. Krizde yerel acil hat.|Steady does not diagnose or treat. These are coping tools. In crisis call local emergency services.|Steady tibbi diaqnoz və ya müalicə vermir. Öhdəlik alətləridir. Krizdə yerli təcili yardım.|Steady не ставит диагноз и не лечит. Это инструменты совладания. В кризисе — местная служба.|Steady no diagnostica ni trata. Son herramientas de afrontamiento. En crisis, emergencia local.|Steady non diagnostica né cura. Strumenti di fronteggiamento. In crisi, i soccorsi locali.'),
  legal_short: R('Tıbbi tedavi değildir.|Not medical treatment.|Tibbi müalicə deyil.|Это не лечение.|No es tratamiento médico.|Non è una cura medica.'),
  crisis: R('Krizde acil hat|In crisis, emergency line|Krizdə təcili xətt|В кризисе — экстренная линия|En crisis, línea de emergencia|In crisi, linea di emergenza'),
  not_medical: R('Tıbbi teşhis veya tedavi değil.|Not a medical diagnosis or treatment.|Tibbi diaqnoz və ya müalicə deyil.|Не диагноз и не лечение.|No es diagnóstico ni tratamiento.|Né diagnosi né cura.'),

  sos_ready: R('Hazır|Ready|Hazır|Готово|Listo|Pronto'),
  sos_title: R('Dur.|Pause.|Dayan.|Стоп.|Pausa.|Pausa.'),
  sos_sub: R('Önce 3 nesne. Renk. Dokun. Sonra nefes.|First 3 objects. Color. Touch. Then breath.|Əvvəl 3 əşya. Rəng. Toxun. Sonra nəfəs.|Сначала три предмета. Цвет. Коснись. Потом дыхание.|Primero 3 objetos. Color. Tocar. Luego respirar.|Prima 3 oggetti. Colore. Toccare. Poi il respiro.'),
  sos_in: R('Nefes al|Breathe in|Nəfəs al|Вдох|Inhala|Inspira'),
  sos_hold: R('Tut|Hold|Tut|Пауза|Sostén|Tieni'),
  sos_out: R('Ver|Breathe out|Ver|Выдох|Suelta|Espira'),
  sos_line: R('Cümle|Line|Cümlə|Фраза|Frase|Frase'),
  sos_passed: R('Geçti|It passed|Keçdi|Прошло|Pasó|È passato'),
  sos_tap: R('Bu cümleye on kez dokun|Tap this line ten times|Bu cümləyə on dəfə toxun|Нажми эту фразу десять раз|Toca esta frase diez veces|Tocca questa frase dieci volte'),
  sos_done: R('Geçti. Sen buradasın.|It passed. You are here.|Keçdi. Sən buradasan.|Прошло. Ты здесь.|Pasó. Estás aquí.|È passato. Sei qui.'),
  sos_back: R('Ana sayfa|Home|Ana səhifə|Домой|Inicio|Home'),
  sos_stop: R('Sesleri durdur|Stop sounds|Səsləri dayandır|Остановить звуки|Parar sonidos|Ferma i suoni'),
  sos_open_lock: R('SOS — kilitten açılır|SOS — opens from the lock|SOS — kiliddən açılır|SOS — открывается с замка|SOS — abre desde el candado|SOS — si apre dal blocco'),
  sos_lock_title: R('Steady kilitli|Steady is locked|Steady kilidlidir|Steady заблокирован|Steady está cerrado|Steady è bloccato'),
  sos_four: R('Dört hane|Four digits|Dörd rəqəm|Четыре цифры|Cuatro dígitos|Quattro cifre'),
  sos_wave_in: R('Dalga inince Geçti.|When the wave recedes, It passed.|Dalğa enəndə Keçdi.|Когда волна спадает — Прошло.|Cuando baja la ola: Pasó.|Quando l’onda cala: È passato.'),
  sos_tap_btn: R('Dokun|Tap|Toxun|Нажми|Toca|Tocca'),
  sos_thanks: R('Bırakıyorum. Küçük bir şükran yeter. Nefes alabildiğim için.|I release. A small thanks is enough. For being able to breathe.|Buraxıram. Kiçik minnətdarlıq bəsdir. Nəfəs ala bildiyim üçün.|Отпускаю. Малой благодарности довольно. За то, что могу дышать.|Suelto. Basta una pequeña gracia.|Rilascio. Basta un piccolo grazie.'),

  pay_kicker: R('Vitrin|Storefront|Vitrin|Витрина|Escaparate|Vetrina'),
  pay_title: R('Pro|Pro|Pro|Pro|Pro|Pro'),
  pay_sub: R('SOS her zaman açık. Gerisi bu cihazda kalır.|SOS is always open. The rest stays on this device.|SOS həmişə açıqdır. Qalanı bu cihazdadır.|SOS всегда открыт. Остальное на этом устройстве.|SOS siempre está abierto. Lo demás queda en este dispositivo.|SOS è sempre aperto. Il resto resta su questo dispositivo.'),
  pay_open: R('Cihazda Pro’yu aç|Turn on Pro on this device|Cihazda Pro-nu aç|Включить Pro на устройстве|Activar Pro en este dispositivo|Attiva Pro su questo dispositivo'),
  pay_stripe: R('Tarayıcı demosu. App Store aboneliği TestFlight IPA’sında.|Browser demo. App Store subscriptions ship in the TestFlight IPA.|Brauzer demosu. App Store abunəliyi TestFlight IPA-sındadır.|Демо браузера. Подписка App Store — в TestFlight IPA.|Demo del navegador. La suscripción de App Store va en el IPA de TestFlight.|Demo del browser. L’abbonamento App Store è nell’IPA TestFlight.'),
  pay_week: R('Haftalık|Weekly|Həftəlik|Неделя|Semanal|Settimanale'),
  pay_month: R('Aylık|Monthly|Aylıq|Месяц|Mensual|Mensile'),
  pay_year: R('Yıllık|Yearly|İllik|Год|Anual|Annuale'),
  pay_featured: R('önerilen|suggested|tövsiyə|рекомендуем|sugerido|consigliato'),
  pay_note: R('3 gün deneme · vitrin fiyatı|3-day trial · storefront price|3 gün sınaq · vitrin qiyməti|3 дня пробы · витринная цена|Prueba de 3 días · precio vitrina|Prova 3 giorni · prezzo vetrina'),
  pay_year_note: R('3 gün deneme · en sakin tempo|3-day trial · the calmest pace|3 gün sınaq · ən sakit tempo|3 дня пробы · самый спокойный темп|Prueba de 3 días · el ritmo más calmo|Prova 3 giorni · il ritmo più calmo'),
  pay_back: R('Geri dön|Go back|Geri qayıt|Назад|Volver|Indietro'),
  pay_on: R('Pro bu cihazda açık|Pro is on for this device|Pro bu cihazda açıqdır|Pro включён на устройстве|Pro está activo en este dispositivo|Pro è attivo su questo dispositivo'),
  pay_free_k: R('Ücretsiz|Free|Pulsuz|Бесплатно|Gratis|Gratis'),
  pay_pro_k: R('Pro|Pro|Pro|Pro|Pro|Pro'),

  back: R('Geri|Back|Geri|Назад|Atrás|Indietro'),
  play: R('Çal|Play|Oxut|Играть|Reproducir|Riproduci'),
  stop: R('Durdur|Stop|Dayandır|Стоп|Parar|Ferma'),
  speak: R('Sesli oku|Read aloud|Səsli oxu|Вслух|Leer en voz alta|Leggi ad alta voce'),
  speak_stop: R('Okumayı durdur|Stop reading|Oxumanı dayandır|Остановить чтение|Parar lectura|Ferma lettura'),
  leave: R('Bırak|Release|Burax|Отпустить|Soltar|Rilascia'),
  remaining: R('Kalan deneme|Trial left|Qalan sınaq|Остаток пробы|Prueba restante|Prova restante'),
  trial_done: R('Deneme bitti|Trial ended|Sınaq bitdi|Проба окончена|Prueba terminada|Prova finita'),
  trial_done_sub: R('3 dakika doldu. Sınırsız dinleme Pro’da. SOS her zaman açık.|3 minutes are up. Unlimited listening is Pro. SOS still never locks.|3 dəqiqə doldu. Limitsiz dinləmə Pro-dadır. SOS həmişə açıqdır.|3 minutes are up. Unlimited listening is Pro. SOS still never locks.|3 minutes are up. Unlimited listening is Pro. SOS still never locks.|3 minutes are up. Unlimited listening is Pro. SOS still never locks.'),
  playing: R('Çalıyor|Playing|Oxuyur|Играет|Reproduciendo|In riproduzione'),
  ready: R('Hazır|Ready|Hazır|Готово|Listo|Pronto'),
  start_min: R('{n} dk başlat|Start {n} min|{n} dəq başlat|Старт {n} мин|Empezar {n} min|Avvia {n} min'),
  timer_done: R('Süre doldu. Gece tohumu: aynı sahne, gözler kapalı, bırak.|Time is up. Night seed: the same scene, eyes closed, release.|Vaxt bitdi. Gecə toxumu: eyni səhnə, gözlər bağlı, burax.|Время вышло. Ночное семя: та же сцена, глаза закрыты, отпусти.|Se acabó el tiempo. Semilla: la misma escena, ojos cerrados, suelta.|Tempo scaduto. Seme: stessa scena, occhi chiusi, rilascia.'),
  nature_k: R('Doğa sahnesi|Nature scene|Təbiət səhnəsi|Сцена природы|Escena de naturaleza|Scena di natura'),
  breath_k: R('Nefes|Breath|Nəfəs|Дыхание|Respiración|Respiro'),
  voice_start: R('Sesli başlat|Start with voice|Səslə başlat|Начать с голоса|Empezar con voz|Avvia con voce'),
  no_file: R('Hazır okuma sesi. İyileştirme iddiası yok.|Ready reading voice. No healing claim.|Hazır oxu səsi. Müalicə iddiası yoxdur.|Готовый голос чтения. Без претензии на исцеление.|Voz de lectura lista. Sin pretensión de cura.|Voce di lettura pronta. Nessuna pretesa di cura.'),
  tones_title: R('Tonlar|Tones|Tonlar|Тона|Tonos|Toni'),
  sleep_title: R('Uyku|Sleep|Yuxu|Сон|Sueño|Sonno'),
  sleep_sub: R('Orijinal hikâyeler, hazır ses. Yedi gün bilim uykusu Pro. Doğa sahnesi bu telefonda.|Original stories, ready voice. Seven-day science sleep is Pro. Nature stays on this phone.|Orijinal hekayələr, hazır səs. Yeddi günlük elm yuxusu Pro-dur.|Оригинальные истории, готовый голос. Семидневный научный сон — Pro.|Relatos originales, voz lista. El sueño científico de 7 días es Pro.|Racconti originali, voce pronta. Il sonno scienza di 7 giorni è Pro.'),
  lab_k: R('Yedi gece|Seven nights|Yeddi gecə|Семь ночей|Siete noches|Sette notti'),
  practice_title: R('Pratik|Practice|Praktika|Практика|Práctica|Pratica'),
  practice_sub: R('Netlik, meditasyon, nefes, yazı. Çoğu Pro.|Clarity, meditation, breath, writing. Most is Pro.|Aydınlıq, meditasiya, nəfəs, yazı. Çoxu Pro-dur.|Ясность, медитация, дыхание, запись. Большинство — Pro.|Claridad, meditación, respiración, escritura. Casi todo es Pro.|Chiarezza, meditazione, respiro, scrittura. Gran parte è Pro.'),
  treat_kicker: R('Başa çıkma kapıları|Coping doors|Öhdəlik qapıları|Двери совладания|Puertas de afrontamiento|Porte di fronteggiamento'),
  treat_title: R('Kapılar|Doors|Qapılar|Двери|Puertas|Porte'),
  treat_sub: R('Panik dalgadır, anksiyete yarındır, derealizasyon dünyadır, depersonalizasyon bedendir.|Panic is a wave, anxiety is tomorrow, derealization is the world, depersonalization is the body.|Panik dalğadır, narahatlıq sabahdır, derealizasiya dünyadır, depersonallaşma bədəndir.|Паника — волна, тревога — завтра, дереализация — мир, деперсонализация — тело.|El pánico es ola, la ansiedad es mañana, la desrealización es el mundo, la despersonalización es el cuerpo.|Il panico è onda, l’ansia è domani, la derealizzazione è il mondo, la depersonalizzazione è il corpo.'),
  tools: R('Araçlar|Tools|Alətlər|Инструменты|Herramientas|Strumenti'),
  program: R('Program|Program|Proqram|Программа|Programa|Programma'),
  day_n: R('Gün {n}|Day {n}|Gün {n}|День {n}|Día {n}|Giorno {n}'),
  min_n: R('{n} dk|{n} min|{n} dəq|{n} мин|{n} min|{n} min'),
  sec_n: R('{n} sn|{n} s|{n} san|{n} с|{n} s|{n} s'),
  greet_night: R('Gece yarısı|Late night|Gecəyarı|Глубокая ночь|Madrugada|Notte fonda'),
  greet_morn: R('Günaydın|Good morning|Sabahın xeyir|Доброе утро|Buenos días|Buongiorno'),
  greet_day: R('İyi günler|Good day|Günün xeyir|Добрый день|Buen día|Buona giornata'),
  greet_eve: R('İyi akşamlar|Good evening|Axşamın xeyir|Добрый вечер|Buenas tardes|Buonasera'),
  sentence: R('Cümle|Line|Cümlə|Фраза|Frase|Frase'),
  scene: R('Sahne|Scene|Səhnə|Сцена|Escena|Scena'),
  release: R('Bırakış|Release|Buraxılış|Отпускание|Soltar|Rilascio'),
  gratitude: R('Şükran|Thanks|Minnətdarlıq|Благодарность|Gracias|Grazia'),
  night_seed: R('Gece tohumu|Night seed|Gecə toxumu|Ночное семя|Semilla nocturna|Seme notturno'),
  door_panic: R('Panik|Panic|Panik|Паника|Pánico|Panico'),
  door_anxiety: R('Anksiyete|Anxiety|Narahatlıq|Тревога|Ansiedad|Ansia'),
  door_dr: R('Derealizasyon|Derealization|Derealizasiya|Дереализация|Desrealización|Derealizzazione'),
  door_dp: R('Depersonalizasyon|Depersonalization|Depersonallaşma|Деперсонализация|Despersonalización|Depersonalizzazione'),
  list_open: R('Listeyi aç|Open the list|Siyahını aç|Открыть список|Abrir la lista|Apri l’elenco'),
  waves_hidden: R('{n} dalga bu cihazda gizli duruyor.|{n} waves sit hidden on this device.|{n} dalğa bu cihazda gizli durur.|{n} волн скрыты на этом устройстве.|{n} olas quedan ocultas en este dispositivo.|{n} onde restano nascoste su questo dispositivo.'),
  taps_n: R('{n} dokunuş|{n} taps|{n} toxunuş|{n} нажатий|{n} toques|{n} toc'),

  ob_continue: R('Devam|Continue|Davam|Continue|Continue|Continue'),
  ob_skip: R('Şimdilik ücretsiz devam et|Stay free for now|Hələlik pulsuz davam et|Stay free for now|Stay free for now|Stay free for now'),
  ob_yes: R('Evet|Yes|Bəli|Yes|Yes|Yes'),
  ob_no: R('Hayır|No|Xeyr|No|No|No'),
  ob_welcome_k: R('Steady|Steady|Steady|Steady|Steady|Steady'),
  ob_welcome: R('Önce dilini seç.|Choose your language first.|Əvvəl dilini seç.|Choose your language first.|Choose your language first.|Choose your language first.'),
  ob_welcome_sub: R('Cevapların sadece bu telefonda kalır. Teşhis koymayız.|Answers stay on this phone. We do not diagnose.|Cavabların yalnız bu telefondadır. Diaqnoz qoymuruq.|Answers stay on this phone. We do not diagnose.|Answers stay on this phone. We do not diagnose.|Answers stay on this phone. We do not diagnose.'),
  ob_bring: R('Seni buraya ne getirdi?|What brought you here?|Səni bura nə gətirdi?|What brought you here?|What brought you here?|What brought you here?'),
  ob_bring_sub: R('Birini seçmen yeterli. Doğru ya da yanlış yok.|Pick one. There is no right answer.|Birini seçməyin yetər. Düzgün və ya səhv yoxdur.|Pick one. There is no right answer.|Pick one. There is no right answer.|Pick one. There is no right answer.'),
  ob_bring_wave: R('Bir panik dalgası|A panic wave|Panik dalğası|A panic wave|A panic wave|A panic wave'),
  ob_bring_worry: R('Sürekli kaygı|Constant worry|Daimi narahatlıq|Constant worry|Constant worry|Constant worry'),
  ob_bring_sleep: R('Uykusuzluk|Sleeplessness|Yuxusuzluq|Sleeplessness|Sleeplessness|Sleeplessness'),
  ob_bring_world: R('Her şey uzak ya da gerçek dışı geliyor|Everything feels distant or unreal|Hər şey uzaq və ya qeyri-real gəlir|Everything feels distant or unreal|Everything feels distant or unreal|Everything feels distant or unreal'),
  ob_bring_self: R('Kendimi yabancı hissediyorum|I feel foreign to myself|Özümü yad kimi hiss edirəm|I feel foreign to myself|I feel foreign to myself|I feel foreign to myself'),
  ob_need: R('Bu gece neye ihtiyacın var?|What do you need tonight?|Bu gecə nəyə ehtiyacın var?|What do you need tonight?|What do you need tonight?|What do you need tonight?'),
  ob_need_sub: R('Şimdilik tek bir şey yeter.|One thing is enough for now.|Hələlik bir şey bəsdir.|One thing is enough for now.|One thing is enough for now.|One thing is enough for now.'),
  ob_need_stop: R('Durmak|To pause|Dayanmaq|To pause|To pause|To pause'),
  ob_need_sleep: R('Uyumak|To sleep|Yatmaq|To sleep|To sleep|To sleep'),
  ob_need_sentence: R('Kısa bir cümle|A short sentence|Qısa bir cümlə|A short sentence|A short sentence|A short sentence'),
  ob_need_breath: R('Nefes|Breath|Nəfəs|Breath|Breath|Breath'),
  ob_often: R('Bunu ne sıklıkla yaşıyorsun?|How often does this happen?|Bunu nə qədər tez-tez yaşayırsan?|How often does this happen?|How often does this happen?|How often does this happen?'),
  ob_often_sub: R('Tam sayı gerekmez.|An exact number is not needed.|Dəqiq rəqəm lazım deyil.|An exact number is not needed.|An exact number is not needed.|An exact number is not needed.'),
  ob_often_rare: R('Seyrek|Rarely|Nadirən|Rarely|Rarely|Rarely'),
  ob_often_some: R('Ara sıra|Sometimes|Bəzən|Sometimes|Sometimes|Sometimes'),
  ob_often_most: R('Çoğu gece|Most nights|Çox gecələr|Most nights|Most nights|Most nights'),
  ob_often_always: R('Neredeyse her gün|Almost every day|Demək olar hər gün|Almost every day|Almost every day|Almost every day'),
  ob_risk: R('Yoğun bir dönem|A heavy stretch|Ağır bir dövr|A heavy stretch|A heavy stretch|A heavy stretch'),
  ob_risk_sub: R('Bu araçlar tıbbi tedavi yerine geçmez. Şu an yoğunsa acil hat bu ekranda açık. SOS, Steady açılınca durur ve kilitlenmez.|These tools are not medical treatment. If it is heavy now, the emergency line is open on this screen. SOS stays on the home screen and never locks.|Bu alətlər tibbi müalicənin yerini tutmur. İndi ağırdırsa təcili xətt bu ekranda açıqdır. SOS, Steady açılınca durur və kilidlənmir.|These tools are not medical treatment. If it is heavy now, the emergency line is open on this screen. SOS stays on the home screen and never locks.|These tools are not medical treatment. If it is heavy now, the emergency line is open on this screen. SOS stays on the home screen and never locks.|These tools are not medical treatment. If it is heavy now, the emergency line is open on this screen. SOS stays on the home screen and never locks.'),
  ob_risk_tel: R('Acil hat · {n}|Emergency line · {n}|Təcili xətt · {n}|Emergency line · {n}|Emergency line · {n}|Emergency line · {n}'),
  ob_risk_sos: R('Tanı koymayız. İstersen devam et; SOS her zaman ücretsiz kalır.|We do not diagnose. Continue if you want; SOS always stays free.|Diaqnoz qoymuruq. İstəsən davam et; SOS həmişə pulsuz qalır.|We do not diagnose. Continue if you want; SOS always stays free.|We do not diagnose. Continue if you want; SOS always stays free.|We do not diagnose. Continue if you want; SOS always stays free.'),
  ob_part: R('Bölüm 2|Part 2|2-ci hissə|Part 2|Part 2|Part 2'),
  ob_part_title: R('Gece|Night|Gecə|Night|Night|Night'),
  ob_sleep_q: R('Uykuya dalmak zor geliyor mu?|Is it hard to fall asleep?|Yuxuya getmək çətin gəlir?|Is it hard to fall asleep?|Is it hard to fall asleep?|Is it hard to fall asleep?'),
  ob_sleep_sub: R('Saat sözü vermiyoruz. Sadece anlamak için soruyoruz.|We do not promise hours. We only ask to understand.|Saat vəd etmirik. Yalnız başa düşmək üçün soruşuruq.|We do not promise hours. We only ask to understand.|We do not promise hours. We only ask to understand.|We do not promise hours. We only ask to understand.'),
  ob_freq_never: R('Nadiren / hiç|Rarely / never|Nadirən / heç|Rarely / never|Rarely / never|Rarely / never'),
  ob_freq_some: R('Bazen|Sometimes|Bəzən|Sometimes|Sometimes|Sometimes'),
  ob_freq_often: R('Sık sık|Often|Tez-tez|Often|Often|Often'),
  ob_freq_always: R('Neredeyse her gece|Almost every night|Demək olar hər gecə|Almost every night|Almost every night|Almost every night'),
  ob_agree: R('Bu cümleye katılıyor musun?|Do you agree with this?|Bu cümlə ilə razısan?|Do you agree with this?|Do you agree with this?|Do you agree with this?'),
  ob_agree_sub: R('Doğru cevap yok.|There is no right answer.|Düzgün cavab yoxdur.|There is no right answer.|There is no right answer.|There is no right answer.'),
  ob_ag1: R('İşler istediğim gibi gitmeyince içim daralıyor.|I feel tight when things do not go as I planned.|İşlər istədiyim kimi getməyəndə içim daralır.|I feel tight when things do not go as I planned.|I feel tight when things do not go as I planned.|I feel tight when things do not go as I planned.'),
  ob_ag2: R('Bazen etraf gerçek değilmiş gibi geliyor.|Sometimes the room feels unreal.|Bəzən ətraf real deyilmiş kimi gəlir.|Sometimes the room feels unreal.|Sometimes the room feels unreal.|Sometimes the room feels unreal.'),
  ob_hours: R('Gecede ortalama kaç saat uyuyorsun?|How many hours do you sleep on average?|Gecədə orta hesabla neçə saat yatırsan?|How many hours do you sleep on average?|How many hours do you sleep on average?|How many hours do you sleep on average?'),
  ob_hours_sub: R('Tahmin yeter.|A guess is enough.|Təxmin yetər.|A guess is enough.|A guess is enough.|A guess is enough.'),
  ob_h_lt6: R('6 saatten az|Less than 6 hours|6 saatdən az|Less than 6 hours|Less than 6 hours|Less than 6 hours'),
  ob_h_67: R('6–7 saat|6–7 hours|6–7 saat|6–7 hours|6–7 hours|6–7 hours'),
  ob_h_78: R('7–8 saat|7–8 hours|7–8 saat|7–8 hours|7–8 hours|7–8 hours'),
  ob_h_89: R('8–9 saat|8–9 hours|8–9 saat|8–9 hours|8–9 hours|8–9 hours'),
  ob_h_9: R('9 saat veya daha fazla|9 hours or more|9 saat və ya daha çox|9 hours or more|9 hours or more|9 hours or more'),
  ob_wake: R('Gecenin ortasında uyanıyor musun?|Do you wake in the middle of the night?|Gecənin ortasında oyanırsan?|Do you wake in the middle of the night?|Do you wake in the middle of the night?|Do you wake in the middle of the night?'),
  ob_wake_every: R('Her gece|Every night|Hər gecə|Every night|Every night|Every night'),
  ob_wake_most: R('Çoğu gece|Most nights|Çox gecələr|Most nights|Most nights|Most nights'),
  ob_wake_some: R('Ara sıra|Occasionally|Bəzən|Occasionally|Occasionally|Occasionally'),
  ob_wake_rare: R('Nadiren|Rarely|Nadirən|Rarely|Rarely|Rarely'),
  ob_fall: R('Bu gece nasıl uykuya varmak istersin?|How would you like to fall asleep tonight?|Bu gecə necə yatmaq istəyirsən?|How would you like to fall asleep tonight?|How would you like to fall asleep tonight?|How would you like to fall asleep tonight?'),
  ob_fall_sub: R('Birden fazla seçebilirsin. Programa ekleriz.|You can pick more than one. We will add them.|Birdən çox seçə bilərsən. Proqrama əlavə edəcəyik.|You can pick more than one. We will add them.|You can pick more than one. We will add them.|You can pick more than one. We will add them.'),
  ob_fall_med: R('Uyku meditasyonu|Sleep meditation|Yuxu meditasiyası|Sleep meditation|Sleep meditation|Sleep meditation'),
  ob_fall_story: R('Uyku hikâyesi|Sleep story|Yuxu hekayəsi|Sleep story|Sleep story|Sleep story'),
  ob_fall_nature: R('Doğa sesleri|Nature sounds|Təbiət səsləri|Nature sounds|Nature sounds|Nature sounds'),
  ob_medex: R('Meditasyonla aran nasıl?|What is your experience with meditation?|Meditasiya ilə aran necədir?|What is your experience with meditation?|What is your experience with meditation?|What is your experience with meditation?'),
  ob_medex_sub: R('Buna göre öneri sırasını ayarlarız.|This helps us order suggestions.|Buna görə təklif sırasını quracağıq.|This helps us order suggestions.|This helps us order suggestions.|This helps us order suggestions.'),
  ob_medex_none: R('Az ya da hiç yok|Little to none|Az və ya heç yoxdur|Little to none|Little to none|Little to none'),
  ob_medex_some: R('Ara sıra denerim|I try it now and then|Bəzən sınayıram|I try it now and then|I try it now and then|I try it now and then'),
  ob_medex_skip: R('Şimdilik ilgilenmiyorum|Not interested right now|Hələlik maraqlı deyil|Not interested right now|Not interested right now|Not interested right now'),
  ob_hope: R('Endişelenme. Mucize değil; bu gece yanında duracak bir yer.|Don’t worry. Not a miracle; a place that stays with you tonight.|Narahat olma. Möcüzə yoxdur; bu gecə yanında duracaq bir yer.|Don’t worry. Not a miracle; a place that stays with you tonight.|Don’t worry. Not a miracle; a place that stays with you tonight.|Don’t worry. Not a miracle; a place that stays with you tonight.'),
  ob_before: R('Şimdi|Now|İndi|Now|Now|Now'),
  ob_after: R('Birlikte|Together|Birlikdə|Together|Together|Together'),
  ob_b1: R('Gece boyunca düşünmek|Thinking all night|Gecə boyu düşünmək|Thinking all night|Thinking all night|Thinking all night'),
  ob_b2: R('Odada değilmiş gibi olmak|Feeling not in the room|Otaqda deyilmiş kimi olmaq|Feeling not in the room|Feeling not in the room|Feeling not in the room'),
  ob_b3: R('Yarını kurmak|Building tomorrow|Sabahı qurmaq|Building tomorrow|Building tomorrow|Building tomorrow'),
  ob_b4: R('Gerilmiş beden|A tense body|Gərgin bədən|A tense body|A tense body|A tense body'),
  ob_b5: R('Uykunun gelmemesi|Sleep not coming|Yuxunun gəlməməsi|Sleep not coming|Sleep not coming|Sleep not coming'),
  ob_a1: R('Dalgayı izlemek, zorlamamak|Watching the wave, not forcing it|Dalğanı izləmək, məcbur etməmək|Watching the wave, not forcing it|Watching the wave, not forcing it|Watching the wave, not forcing it'),
  ob_a2: R('Şimdiye ait kısa bir cümle|A short present-tense line|İndiki zamana aid qısa cümlə|A short present-tense line|A short present-tense line|A short present-tense line'),
  ob_a3: R('Çene yumuşak, nefes uzun|Soft jaw, long breath|Çənə yumşaq, nəfəs uzun|Soft jaw, long breath|Soft jaw, long breath|Soft jaw, long breath'),
  ob_a4: R('Bir sahne, sonra bırakmak|A scene, then letting go|Bir səhnə, sonra buraxmaq|A scene, then letting go|A scene, then letting go|A scene, then letting go'),
  ob_a5: R('Uyku gelirse gelsin|Sleep if it comes|Yuxu gələrsə gəlsin|Sleep if it comes|Sleep if it comes|Sleep if it comes'),
  ob_analyze: R('Birkaç gün içinde daha yumuşak geceler|Softer nights in a couple of days|Bir neçə günə daha yumşaq gecələr|Softer nights in a couple of days|Softer nights in a couple of days|Softer nights in a couple of days'),
  ob_analyze_sub: R('Bu bir tedavi sonucu değil. Cevaplarına göre yön.|This is not a medical result. A direction from your answers.|Bu müalicə nəticəsi deyil. Cavablarına görə istiqamət.|This is not a medical result. A direction from your answers.|This is not a medical result. A direction from your answers.|This is not a medical result. A direction from your answers.'),
  ob_an_rest: R('Kesintisiz duruş|Uninterrupted presence|Fasiləsiz duruş|Uninterrupted presence|Uninterrupted presence|Uninterrupted presence'),
  ob_an_rest_to: R('daha uzun|longer|daha uzun|longer|longer|longer'),
  ob_an_land: R('Uykuya inmek|Settling into sleep|Yuxuya enmək|Settling into sleep|Settling into sleep|Settling into sleep'),
  ob_an_land_to: R('daha yumuşak|softer|daha yumşaq|softer|softer|softer'),
  ob_plan: R('Sana özel gece planı hazırlanıyor|Your night plan is being prepared|Sənə özəl gecə planı hazırlanır|Your night plan is being prepared|Your night plan is being prepared|Your night plan is being prepared'),
  ob_plan_sub: R('Birkaç saniye. Sahte yorum yok.|A few seconds. No fake reviews.|Bir neçə saniyə. Saxta rəy yoxdur.|A few seconds. No fake reviews.|A few seconds. No fake reviews.|A few seconds. No fake reviews.'),
  ob_p1: R('Biraz bekleyelim…|This may take a few seconds…|Bir az gözləyək…|This may take a few seconds…|This may take a few seconds…|This may take a few seconds…'),
  ob_p2: R('4-2-6 nefes ritmi|4-2-6 breath rhythm|4-2-6 nəfəs ritmi|4-2-6 breath rhythm|4-2-6 breath rhythm|4-2-6 breath rhythm'),
  ob_p3: R('Yumuşak sesler ve gece hikâyeleri|Soft sound and night stories|Yumşaq səslər və gecə hekayələri|Soft sound and night stories|Soft sound and night stories|Soft sound and night stories'),
  ob_p4: R('Şimdiye ait cümleler|Present-tense lines|İndiki zamana aid cümlələr|Present-tense lines|Present-tense lines|Present-tense lines'),
  ob_p5: R('Hazır.|Ready.|Hazırdır.|Ready.|Ready.|Ready.'),
  ob_remind: R('Hatırlatmalar|Reminders|Xatırlatmalar|Reminders|Reminders|Reminders'),
  ob_remind_sub: R('İsteğe bağlı. Sunucu yok; izin verirsen bu telefonda kalır.|Optional. No server; if you allow it, it stays on this phone.|İstəyə bağlı. Server yoxdur; icazə versən bu telefonda qalır.|Optional. No server; if you allow it, it stays on this phone.|Optional. No server; if you allow it, it stays on this phone.|Optional. No server; if you allow it, it stays on this phone.'),
  ob_rem_quote: R('Günün cümlesi|Line of the day|Günün cümləsi|Line of the day|Line of the day|Line of the day'),
  ob_rem_quote_h: R('Uygulama açıkken sabah bir satır.|A morning line while the app is open.|Tətbiq açıq olanda səhər bir sətir.|A morning line while the app is open.|A morning line while the app is open.|A morning line while the app is open.'),
  ob_rem_sleep: R('Uyku hatırlatması|Sleep reminder|Yuxu xatırlatması|Sleep reminder|Sleep reminder|Sleep reminder'),
  ob_rem_sleep_h: R('Gece, istersen uyku sayfasına.|At night, toward Sleep if you want.|Gecə, istəsən Yuxu səhifəsinə.|At night, toward Sleep if you want.|At night, toward Sleep if you want.|At night, toward Sleep if you want.'),
  ob_rem_trial: R('Deneme bitmeden hatırlat|Remind me before the trial ends|Sınaq bitməmiş xatırlat|Remind me before the trial ends|Remind me before the trial ends|Remind me before the trial ends'),
  ob_rem_trial_h: R('iPhone uygulamasında son gün, Steady kapalı olsa da gelir. Tarayıcıda yalnızca açıkken.|On the iPhone app it arrives on the last day even if Steady is closed. In a browser, only while open.|iPhone tətbiqində son gün, Steady bağlı olsa da gəlir. Brauzerdə yalnız açıq olanda.|On the iPhone app it arrives on the last day even if Steady is closed. In a browser, only while open.|On the iPhone app it arrives on the last day even if Steady is closed. In a browser, only while open.|On the iPhone app it arrives on the last day even if Steady is closed. In a browser, only while open.'),
  ob_rem_trial_t: R('Denemen bitmek üzere. SOS her zaman açık.|Your trial is about to end. SOS stays open.|Sınağın bitmək üzrədir. SOS həmişə açıqdır.|Your trial is about to end. SOS stays open.|Your trial is about to end. SOS stays open.|Your trial is about to end. SOS stays open.'),
  ob_trial: R('Üç gün ücretsiz dene|Start your three free days|Üç gün pulsuz sına|Start your three free days|Start your three free days|Start your three free days'),
  ob_trial_sub: R('Planın hazır.|Your plan is ready.|Planın hazırdır.|Your plan is ready.|Your plan is ready.|Your plan is ready.'),
  ob_tl1: R('Plan oluşturuldu.|The plan is set.|Plan quruldu.|The plan is set.|The plan is set.|The plan is set.'),
  ob_tl2: R('Bugün — hemen açılır|Today — opens now|Bu gün — dərhal açılır|Today — opens now|Today — opens now|Today — opens now'),
  ob_tl2s: R('SOS her zaman. Üç gün boyunca diğer içerikler de açık.|SOS always. Other content opens for three days.|SOS həmişə. Üç gün ərzində digər məzmun da açıqdır.|SOS always. Other content opens for three days.|SOS always. Other content opens for three days.|SOS always. Other content opens for three days.'),
  ob_tl3: R('2. gün — hatırlatma|Day 2 — a reminder|2-ci gün — xatırlatma|Day 2 — a reminder|Day 2 — a reminder|Day 2 — a reminder'),
  ob_tl3s: R('İstersen, deneme bitmeden bir not.|If you want, a note before it ends.|İstəsən, sınaq bitməmiş bir qeyd.|If you want, a note before it ends.|If you want, a note before it ends.|If you want, a note before it ends.'),
  ob_tl4: R('3. gün — deneme biter|Day 3 — the trial ends|3-cü gün — sınaq bitir|Day 3 — the trial ends|Day 3 — the trial ends|Day 3 — the trial ends'),
  ob_tl4s: R('Sonra ücretsiz katman. SOS kapanmaz. İptal Ayarlar’da.|Then the free tier. SOS stays open. Cancel in Settings.|Sonra pulsuz qat. SOS bağlanmır. Ləğv Ayarlardadır.|Then the free tier. SOS stays open. Cancel in Settings.|Then the free tier. SOS stays open. Cancel in Settings.|Then the free tier. SOS stays open. Cancel in Settings.'),
  ob_cta: R('Üç günlük denemeyi başlat|Start my three free days|Üç günlük sınağı başlat|Start my three free days|Start my three free days|Start my three free days'),
  ob_price: R('3 gün bu telefonda Pro. Sonra aylık $9.99 (gösterim fiyatı). Ödeme sonra. SOS her zaman açık.|3 days of Pro on this phone, then $9.99/mo display price. Payment later. SOS always open.|3 gün bu telefonda Pro açıqdır. Sonra aylıq $9.99 (göstəriş qiyməti). Ödəniş sonra. SOS həmişə açıqdır.|3 days of Pro on this phone, then $9.99/mo display price. Payment later. SOS always open.|3 days of Pro on this phone, then $9.99/mo display price. Payment later. SOS always open.|3 days of Pro on this phone, then $9.99/mo display price. Payment later. SOS always open.'),
  ob_path_sos: R('Panik için SOS|SOS for panic|Panik üçün SOS|SOS for panic|SOS for panic|SOS for panic'),
  ob_path_sos_s: R('Nefes, ses, Geçti.|Breath, sound, It passed.|Nəfəs, səs, Keçdi.|Breath, sound, It passed.|Breath, sound, It passed.|Breath, sound, It passed.'),
  ob_path_sleep: R('Gece uykusu|Night sleep|Gecə yuxusu|Night sleep|Night sleep|Night sleep'),
  ob_path_sleep_s: R('Hikâye, sahne, tohum.|Story, scene, seed.|Hekayə, səhnə, toxum.|Story, scene, seed.|Story, scene, seed.|Story, scene, seed.'),
  ob_path_quote: R('Bir cümle|A sentence|Bir cümlə|A sentence|A sentence|A sentence'),
  ob_path_quote_s: R('Günün cümlesi burada.|Today’s line is here.|Günün cümləsi buradadır.|Today’s line is here.|Today’s line is here.|Today’s line is here.'),
  ob_path_breath: R('Dalga nefesi|Wave breath|Dalğa nəfəsi|Wave breath|Wave breath|Wave breath'),
  ob_path_breath_s: R('4-2-6, sesli.|4-2-6, spoken.|4-2-6, səsli.|4-2-6, spoken.|4-2-6, spoken.|4-2-6, spoken.'),
  ob_path_worry: R('Kaygı kapısı|Worry door|Narahatlıq qapısı|Worry door|Worry door|Worry door'),
  ob_path_worry_s: R('Yarın için bir durak.|A pause for tomorrow.|Sabah üçün bir dayanacaq.|A pause for tomorrow.|A pause for tomorrow.|A pause for tomorrow.'),
  ob_path_world: R('Dünya kapısı|The world door|Dünya qapısı|The world door|The world door|The world door'),
  ob_path_world_s: R('Kenarlar, oda, yer.|Edges, room, ground.|Kənarlar, otaq, yer.|Edges, room, ground.|Edges, room, ground.|Edges, room, ground.'),
  ob_path_self: R('Beden kapısı|The body door|Bədən qapısı|The body door|The body door|The body door'),
  ob_path_self_s: R('Ben buradayım, bu bedende.|I am here, in this body.|Mən buradayam, bu bədəndə.|I am here, in this body.|I am here, in this body.|I am here, in this body.'),
  ob_path_disc: R('Keşfet|Discover|Kəşf et|Discover|Discover|Discover'),
  ob_path_disc_s: R('Bugün yalnızca biri.|Only one, today.|Bu gün yalnız biri.|Only one, today.|Only one, today.|Only one, today.'),
  me_trial: R('Deneme · {n} gün|Trial · {n} days|Sınaq · {n} gün|Trial · {n} days|Trial · {n} days|Trial · {n} days'),
  me_trial_today: R('Deneme · bugün biter|Trial · ends today|Sınaq · bu gün bitir|Trial · ends today|Trial · ends today|Trial · ends today'),
  me_ob_replay: R('Karşılama akışını yeniden göster|Show the welcome flow again|Qarşılama axınını yenidən göstər|Show the welcome flow again|Show the welcome flow again|Show the welcome flow again'),
} as const

const RAW = { ...CORE, ...EXTRA, ...ONBOARD_I18N } as const

export function interpolate(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => String(vars[k] ?? ''))
}

export function translate(key: StringKey, locale: LocaleId, vars?: Record<string, string | number>): string {
  const table = RAW[key] as Record<string, string> | undefined
  const text = table?.[locale] || table?.en || table?.tr || ''
  return vars ? interpolate(text, vars) : text
}

export const STRING_TABLE = RAW
