#!/usr/bin/env python3
"""Measure the baked narration and write src/lib/voice-durations.ts.

The app shows "N min" on stories, practices and program days. Those numbers
come from here, so they always match the audio that is actually shipped
instead of a guess typed next to the text. Run after every bake; the bake
workflow does.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "public" / "voice" / "manifest.json"
OUT = ROOT / "src" / "lib" / "voice-durations.ts"
KINDS = ("lib:", "prog:")


def seconds(path: Path) -> float:
    probe = shutil.which("ffprobe")
    if probe:
        res = subprocess.run(
            [probe, "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", str(path)],
            capture_output=True,
            text=True,
        )
        try:
            return float(res.stdout.strip())
        except ValueError:
            pass
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        raise SystemExit("need ffprobe or ffmpeg on PATH")
    res = subprocess.run([ffmpeg, "-i", str(path)], capture_output=True, text=True)
    m = re.search(r"Duration: (\d+):(\d+):([\d.]+)", res.stderr)
    if not m:
        return 0.0
    h, mi, s = m.groups()
    return int(h) * 3600 + int(mi) * 60 + float(s)


def main() -> None:
    clips = json.loads(MANIFEST.read_text())["clips"]
    wanted = {
        key: [ROOT / "public" / "voice" / "clips" / part.split("/")[-1] for part in value.split(",")]
        for key, value in clips.items()
        if key.split(":", 1)[1].startswith(KINDS)
    }
    files = sorted({f for parts in wanted.values() for f in parts})
    with ThreadPoolExecutor(max_workers=8) as pool:
        lengths = dict(zip(files, pool.map(lambda f: seconds(f) if f.exists() else 0.0, files)))
    totals = {key: round(sum(lengths[f] for f in parts)) for key, parts in wanted.items()}

    lines = [
        "// Generated by scripts/voice-durations.py from the baked narration. Do not edit.",
        "// Seconds of audio per `${locale}:${clipId}`; clip-minutes.ts turns them into labels.",
        "export const VOICE_SECONDS: Record<string, number> = {",
    ]
    for key in sorted(totals):
        if totals[key] > 0:
            lines.append(f"  {json.dumps(key)}: {totals[key]},")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {sum(1 for v in totals.values() if v > 0)} durations to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
